### DISCUSSION TITLE
Spec discussion: Config layer and CLI interface for alternate state backends

### DISCUSSION THREAD

**Discussion by aaronsteers** [meltano/meltano#6270] [Spec Discussions]
In order to prepare for 

- #5981 

we will need to decide on a yaml and CLI spec for the state backend.

Functional requirements

1. The state backend will need to be configurable per environment.
1. The state backend does not necessarily need to be configured for the `--no-environment` case. (Okay either way, if this is supported or not.)
1. The state backend should be configurable via CLI.
1. The state backend should either expect credentials to be handled by the third party (such as the `boto` library automatically leveraging `AWS_SECRET_ACCESS_KEY_ID`, etc.) or the state backend config would need a way to point to creds without putting those directly in yaml.

Any one or more of these could be used as state backend options in a first iteration:

1. S3 (requires AWS creds)
2. DynamoDB (requires AWS creds)
3. GitHub Gist (requires Github token)

Github gist could be a nice first iteration because it's accessible to anyone with a GitHub account and it is free. Since state files are not updated very frequently, _most_ use cases probably would not run into rate limiting.

The Gist can also be 'secret' in that without the link, others would not be able to locate the gist. (This won't satisfy all users' security requirements but it is a relatively safe option for use cases that are POC or hobbyist in nature.)

## Yaml Spec

As a strawman:

```
...
environments:
  dev:
    state_backend:
      provider: s3
      bucket-name: my-bucket
      aws_region: us-west-2
```

## CLI Spec

If we create this as an environment-level setting, it is possible we could use `meltano config set` for this configuration.

Something like...

```
meltano --environment=dev config set state_backend.provider s3 
meltano --environment=dev config set state_backend.bucket_name my-state-bucket
meltano --environment=dev config set state_backend.aws_region us-west-2
...
```

Or 

```
meltano --environment=dev config set state_backend "{'s3': {'bucket_name': 'my-state-bucket', 'aws_region': 'us-west-2', ...}}
```

## Related

Out of scope, but we'd likely want a similar config paradigm for

- https://github.com/meltano/meltano/issues/2859 

As we make decisions here regarding how configuration should be performed, those should be designed to be comparable to the mechanisms we'd want to design for the secrets backend also.

## Plugin approach

This approach might have some downsides, but one approach would be to use a paradigm of external plugin architecture. The simplest (but perhaps not very optimized approach) would be to allow a plugin to have a capability like `state_backend` and if so, would respond to registered CLI commands (at minimum):

- `get_state`
- `set_state`
- `clear_state`

With optional coverage for `move_state`, and `copy_state`, which otherwise would be performed by using sequences of get/set/clear.

It would then be fairly trivial for community members to write their own state backends and add them via the hub.

If we go this direction, then the plugin would get configured like any other plugin - and then the meltano config would just be:

```
...
environments:
  dev:
    state_backend: <my-plugin-name>
```

Or

```
...
environments:
  dev:
    state_manager: <my-plugin-name>
```

So if the project has plugins called `github-gist-state-manager`, `s3-state-manager`, and `dynamodb-state-manager`, then the config would be:

```
...
environments:
  dev:
    state_manager: github-gist-state-manager
    plugins:
      utilities:
      - name: github-gist-state-manager
         config:
           name_prefix: my-dev-project-
    ...
  staging:
    state_manager: s3-state-manager
    ...
  prod:
    ...
    state_manager: dynamodb-state-manager
```
