### DISCUSSION TITLE
New paradigm for secrets as key-value env var mappings, abstracted from settings

### DISCUSSION THREAD

**Discussion by aaronsteers** [meltano/meltano#6879] [Ideas]
Competing/alternate proposal:

- https://github.com/meltano/meltano/discussions/6886

## Prior thinking

We've been roughly categorizing 'secrets' as a subset of plugin 'config' values. This is problematic for a few different reasons, for instance:

1. It's not very DRY if defined at the plugin setting level.
   - For instance, in the plugin config model, these are all distinct secrets: `TARGET_SNOWFLAKE_PASSWORD`, `TAP_SNOWFLAKE_PASSWORD`, `GREAT_EXPECTATIONS_SF_PASSWORD`, `DBT_PROFILE_SF_PASSWORD`.
2. Users have no control over variable naming if secrets are only a subset of the plugin settings.

## Proposal

Alternatively, we could and probably should consider our 'secrets' abstraction to be more closely analogous to key-value env var mappings.

This is also more similar to how platforms like [GitHub Action Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets) and [Docker Secrets](https://docs.docker.com/engine/reference/commandline/secret_create/#create-a-secret) work, where the secret is a user-provided string, mapped to a protected value.

### Declaring and referencing secrets

If the secrets backend has a secret named `SF_PROD_PASSWORD` for our production Snowflake password, then we can reference it everywhere it is needed. That is probably different than our `SF_STAGING_PASSWORD`, but the names can be anything we want so long as we reference them in the appropriate part of the config that needs them.

### Granting or asserting the presence of necessary secrets

We can optionally require that secrets be named explicitly in `meltano.yml`, or in the `environment` definition. We could alternatively take a 'required env declaration' approach to let users explicitly assert that certain env vars (secrets or otherwise) are present in the stack before execution will proceed.

cc @meltano/engineering

**Comment by tayloramurphy** [comment]
@aaronsteers much of this proposal I think is encapsulated in:

* https://github.com/meltano/meltano/issues/3276

It's not clear to me what you're proposing here that would be too different from that issue. It seems like you're proposing a more generic form of `connections` (namely `secrets`) that can be a write once / reference anywhere model.

One positive in favor of a more descriptive `connections` is that it creates a potentially better UX path for onboarding. We can define a standard model for connecting to databases/warehouses etc and walk users through that configuration and then pass that config on. Instead of having a generic "configure your secrets" and leaving it as an exercise for the user to configure it out how they want.

Am I reading this right or am I missing the plot?

**Reply by aaronsteers** [reply]
@tayloramurphy - As I was spec-ing it out, I was seeing it as very different from `connections`. Specifically, I was imagining this as more aligned with the GitHub secrets - where GitHub doesn't care or try to organize your secrets - and users are free to use alpha-sorting or common name prefixes to organize their own secrets.

Looking at our own org, for example, we have secret keys prefixed with `PYPI_`, `MELTYBOT_`, `SAMPLE_TAP_GITLAB_`, etc. 

As I noted in that issue a while back, I think my biggest concern with that approach is that very many of the settings needed for `connection` definition are _not_ appropriate to be hidden. For instance, the 'connection' definition for a slack site or github organization will contain 'github_project_name' or 'slack_site_name'. Obfuscating those values makes it then difficult to debug or make sense of the connection definition.

So, if the connection contains private and non-private key-value configuration, the connection definition itself won't hold _only_ secrets. One option is to simply map connection definitions to my above proposal, so that connections reference the secret key names and assign those to connection properties. This is essentially the same syntax and pattern of usage as we would have when plugin config reference env var names as secrets.

Another approach that merges these ideas - and probably this was your intention in proposing the linkage here - would be for all 'connection' parameters to contain both secret and non-secret components. Then, we have a two-part reference, with "connection name" and "parameter name" providing the dereferenced value. 

```
connections:
- name: gitlab-bot
  type: api-credential-pair
  parameters:
    site_url: https://gitlab.com
    username: meltybot
    password: *********
```

Presumably, for this to be a replacement for (and not a complement of) the secrets implementation, then `password` here has to be the source of record, and can't point to another reference. If it points to an external reference, then we still have to separately solve that problem of how to store and reference the secrets values.

There's probably a way to make this work, but I don't see an obvious path to do so unless connections are created and managed _outside_ of `meltano.yml` - which feels odd to me, design-wise.

One possible solution is to use Ansible [Vault](https://docs.ansible.com/ansible/latest/user_guide/vault.html) or Mozilla [Sops](https://github.com/mozilla/sops#sops-secrets-operations) to encrypt values directly in the yaml file, but otherwise we would basically need to duplicate the connection definition in yaml and also in the cloud.

I'll kick off a thread about the in-place yaml in-place encryption pattern.

But either way, I don't see the value in adding connections because it doesn't directly solve the problem of how to manage the secrets and how to reference them.

**Reply by tayloramurphy** [reply]
> So, if the connection contains private and non-private key-value configuration, the connection definition itself won't hold only secrets. 

Correct

> Another approach that merges these ideas - and probably this was your intention in proposing the linkage here - would be for all 'connection' parameters to contain both secret and non-secret components.

Yes, this is the general abstraction I was having in mind. 

>  I don't see the value in adding connections because it doesn't directly solve the problem of how to manage the secrets and how to reference them.

I think this is where I'm missing exactly the problem this discussion was intended to solve. It felt adjacent to another problem I think we need to solve for easier onboarding: helping users define their main connection to a database / warehouse and using that connection information in multiple places. 

On a managed version of Meltano I can imagine a flow where we have users tell us how to connect their warehouse and with that information we can give them target-x and autopopulate values for them (all of this could still be tied back to the YAML). 

@aaronsteers let's have a sync conversation on this as I do think I understand what you're trying to go for on the secrets side, but I do believe there's a compelling use case for non-secret values that "we can reference it everywhere it is needed". _Especially_ if it's done in a way that can be treated similar to a plugin that can be inherited, overriden, etc.

**Comment by kgpayne** [comment]
This is super interesting! I didn't see it immediately, but [now see](https://github.com/meltano/meltano/discussions/6879#discussioncomment-3874234) that `secrets` and `connections` are complimentary but separate, and that we'd likely need `secrets` first before `connections` (as connections mix plain and secret values). Not sure how far you've got with a spec @aaronsteers but this is what came to mind for me:

```yaml
# meltano.yml
version: 1
environments:
- name: dev
  secrets:
  - name: pg-host # Maps to SECRET_PG_HOST env var at run time.
    plugin: secrets-chamber # Plugin to use when fetching secrets.
    key: dev/pg-host # Key/identifier in secret backend.
  - name: pg-password
    plugin: secrets-chamber # If only one secrets plugin is defined for a project, maybe this repetition is unnecessary?
    key: dev/pg-password
    alias: I_DONT_LIKE_DEFAULTS # Alias for use in stead of SECRET_PG_PASSWORD
plugins:
  secrets:
  - name: secrets-chamber
    variant: segmentio
    pipurl: git+https://github.com/segmentio/chamber/v2@latest
    config:
      aws_access_key_id: ${AWS_ACCESS_KEY_ID} # These likely come from the `.env` or outside Meltano.
      aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres
    config:
      host: ${SECRET_PG_HOST}
      password: ${I_DONT_LIKE_DEFAULTS}
```

In future, connections might use secrets too:

```yaml
connections:
- name: snowflake
   type: snowflake
   version: 1
   parameters:
    user: USERNAME
    password: ${SECRET_SF_PASSWORD}
```

**Reply by kgpayne** [reply]
As a separate thought, the above scheme would also support the encrypted case (#6886), via a plugin for decrypting keys in stead of retrieving key-values:

```yaml
environments:
- name: dev
  secrets:
  - name: pg-host # Maps to SECRET_PG_HOST env var at run time.
    plugin: secrets-ansible-vault # Plugin to use when fetching secrets.
    key: |
      $ANSIBLE_VAULT;1.2;AES256;dev
      30613233633461343837653833666333643061636561303338373661313838333565653635353162
      3263363434623733343538653462613064333634333464660a663633623939393439316636633863
      61636237636537333938306331383339353265363239643939666639386530626330633337633833
      6664656334373166630a363736393262666465663432613932613036303963343263623137386239
      6330
```

Might also help to define a 'secrets plugin'; I see it as a plugin built with the EDK that supports CRUD get/set/update/delete actions against passed key identifiers.

**Reply by aaronsteers** [reply]
@kgpayne - I do like this approach a lot. 👍 

Given the tight timeline and priorities, along with our focus on lean-ness over extensibility, I'm leaning towards perhaps _not_ trying to have a robust byo-plugin approach to secrets, but instead building handlers for one or more secrets providers with native support in Meltano core itself. So then, we might opt for `provider: chamber` in place of `plugin: secrets-chamber` in your above example.

```
# meltano.yml
version: 1
environments:
- name: dev
  secrets:
  - name: pg-host # Maps to SECRET_PG_HOST env var at run time.
    provider: chamber # Plugin to use when fetching secrets.
    key: dev/pg-host # Key/identifier in secret backend.
  - name: pg-password
    provider: chamber # If only one secrets plugin is defined for a project, maybe this repetition is unnecessary?
    key: dev/pg-password
    alias: I_DONT_LIKE_DEFAULTS # Alias for use in stead of SECRET_PG_PASSWORD
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres
    config:
      host: ${SECRET_PG_HOST}
      password: ${I_DONT_LIKE_DEFAULTS}
```

And, per your code comment, we can simplify further if there's a default backend per environment:

```
# meltano.yml
version: 1
environments:
- name: dev
  default_secrets_backend: chamber
  secrets:
  - name: pg-host # Maps to SECRET_PG_HOST env var at run time.
    key: dev/pg-host # Key/identifier in secret backend.
  - name: pg-password
    key: dev/pg-password
    alias: I_DONT_LIKE_DEFAULTS # Alias for use in stead of SECRET_PG_PASSWORD
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres
    config:
      host: ${SECRET_PG_HOST}
      password: ${I_DONT_LIKE_DEFAULTS}
```

What do you think?

Probably worth calling out that the above presumes that this is a zero-config provider, since we don't have a space for configuring access to the provider itself. But I think that is reasonable: generally those will come pre-configured on the host, OS, or workstation that we're executing from; if not, we probably need a key to access them, which isn't safe to put into yaml, and we don't want to be in a game of inception where we need a secret to unlock the secrets, to unlock the secrets, etc.

Taking the example of a managed/native Meltano secrets backend, the provider is authenticated by `meltano login`, and once you are logged in, we know how to map and extract the secrets in your org/project.

**Reply by aaronsteers** [reply]
Also, as follow-up, I wonder if `name` becomes optional if declaring `alias`, and if the key itself could be the name/alias if we're dealing with secrets that already match the expected all-upper naming convention.

I.e. would all of these definitions be also legal?:

```
secrets:
  # When name is omitted, 'key' is used as 'name'
- key: SF_ACCOUNT # Can be referenced as $SECRET_SF_ACCOUNT
- key: SF_PASSWORD # Can be referenced as $SECRET_SF_PASSWORD
- key: DEV_PG_HOST # Key/identifier in secret backend.
  alias: PG_HOST # Can be referenced as $PG_HOST in plugin config
- key: PG_PASSWORD # Can be referenced as $SECRET_PG_PASSWORD
```

I think at the command line especially, the 'name' seems like a good identity field for `CRUD` operations. But I'm still on the fence if if 'name' and 'key' are both strictly needed. Even if not 'strictly' needed, there may be a benefit of keeping them both separate and both required. I'll keep thinking on this, but let me know if you have thoughts.

Overall, I think this spec can work well. What's also nice is that this is very easy to 'incrementally' adopt. However users are hydrating secrets in their solution today, they could add a secrets declaration block and let Meltano hydrate them - all while keeping the rest of their meltano project unchanged. Conversely, users could _delete_ the entire secrets block and just hyrdrate environment variables themselves without breaking any functionality. Because we're leveraging the env var reference syntax, the rest of the project doesn't need to know or care where the value is coming from, a 'normal' env var or a 'secret'. I also like the separation of `key` from `alias`, as that insulates the project definition from whatever the user, administrator chose to call the secret for organization or management purposes. This proposal also does really well with secrets coming from different providers, since any secret could in theory have it's own `provider` source.

**Reply by aaronsteers** [reply]
In a future where containers and their secrets will be initialized by the cloud orchestrator, and we don't want _every_ task to have access to every single secret, we should also have a way to declare which environments and plugins have access to the declared secret.

Expanding the example from above then:

```yml
environments:
- name: dev
  default_secrets_backend: chamber
  secrets:
  - name: pg-host
    key: dev/pg-host  # Key/identifier in secret backend.
    alias: SECRET_PG_HOST  # The env var that plugins will reference in their config.
    allowed_plugins:  # Only these plugins will have access to the secret `SECRET_PG_HOST` env var:
    - target-postgres
    - dbt-postgres
    - tap-postgres
```

While it isn't immediately obvious from context, there's a benefit of the plugin-level grants appearing inline here rather than inline with the plugin definition: that is, to respect a `CODEOWNERS` ruleset if applicable. Whoever on a Data team is managing the secrets declaration file would _also_ have control over which plugins can leverage those secrets. Granting a secret value to an additional plugin necessarily goes back to the context of the declaration itself - and from that single context we can see every place where the secret is allowed to be used.
