### DISCUSSION TITLE
Allowing vendor-specific annotations in `meltano.yml`

### DISCUSSION THREAD

**Discussion by aaronsteers** [meltano/meltano#7053] [General]
We want to allow vendor-specific annotations for `meltano.yml` files. As of today, users can add extra nodes to the file, and these _probably_ won't break anything - but there is no officially sanctioned key to use for annotations.

This proposal would reserve a specific key ID for annotations, which would have the following behaviors:

1. They would be defined in the JSON Schema, to prevent linters from complaining of their inclusion.
2. They would _by definition_ not change the behavior of Meltano Core itself.
3. They _could_ change behavior of the Meltano project when run through a third party tool, such as Dagster, Airflow, Meltano Cloud, or other tool.
4. They could be used by the end user for custom automations - for instance, if the user wants to create their own plugin that introduce new functionality.
5. They could be added by Meltano itself when building `meltano-manifest.json`, for "fyi" lineage information that (by definition) does change the behavior of execution - for instance, annotating inheritance metadata used during calculation of a specific value.
6. They could be used by documentation tools to add non-operational data that nevertheless is helpful in maintaining the project - for instance, annotating an estimated run time or estimated total row count for a given schedule. (Those could be rendered by something like `meltano-sphinx` when building docs.) 

Proposed keys:

- `extra`
- `meta`
- `annotations`
- `vendor`
- `_extra`
- `_meta`
-  ...
- `+extra`
- `+meta`
-  ...

**Comment by tayloramurphy** [comment]
I'm a big fan of `meta` for clear reasons https://github.com/dbt-labs/dbt-core/pull/2015 😄

**Reply by aaronsteers** [reply]
Starting from [this example](https://github.com/meltano/meltano/blob/main/docs/example-library/meltano-run/meltano.yml), here's a sample with `meta`, for context:

```yml
project_id: 90f75496-2018-4b3a-97ac-9662e11c0094
meta:
  meltano-sphinx:
    html_theme: furo
plugins:
  extractors:
  - name: tap-gitlab
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-gitlab.git
  - name: tap-gitlab-debugging
    inherits_from: tap-gitlab
    # let Meltano Cloud know that it doesn't need this plugin
    meta:
      meltano-cloud:
        ignore: true
  # ...
environments:
- name: dev
- name: staging
- name: prod
  meta:
    meltano-cloud:
      branch: main
    airflow:
      ignore: true
default_environment: dev
```

@tayloramurphy - How does this look for you? ☝️ 

@edgarrmondragon - I adapted your example to use `meta`. Below is another version with `tool` for comparison:

<details>
<summary>Alternate mock-up</summary>

```yml
project_id: 90f75496-2018-4b3a-97ac-9662e11c0094
tool:
  meltano-sphinx:
    html_theme: furo
plugins:
  extractors:
  - name: tap-gitlab
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-gitlab.git
  - name: tap-gitlab-debugging
    inherits_from: tap-gitlab
    # let Meltano Cloud know that it doesn't need this plugin
    tool:
      meltano-cloud:
        ignore: true
  # ...
environments:
- name: dev
- name: staging
- name: prod
  tool:
    airflow:
      ignore: true
default_environment: dev
```

</details>

I think `meta` is really nice because (1) it matches precedent from dbt, and (2) it feels more likely to be a 'no-op' from the Meltano Core side.

Any issues with the proposal to use `meta`, following from the `dbt` example?

**Reply by tayloramurphy** [reply]
@aaronsteers I like that mockup but I want to understand where `meta` _isn't_ going to be. 

* `jobs` and `schedules` seem to be excluded currently - would be useful to have there as well.
* Are you thinking to have `meta` at the same level as `extractors` and `loaders` or only for an individual plugin? My gut says only at the plugin level.
* On the environment level, similarly it'd only be top-level and at the plugin level? How would merging of `meta` work when an environment is applied?
* Does inheriting a plugin also inherit its `meta`?

**Reply by WillDaSilva** [reply]
@tayloramurphy I think the idea (at least as I see it) is that this is for data that Meltano doesn't handle/support, so the field should be permitted as a key of any object within the jsonschema.

> On the environment level, similarly it'd only be top-level and at the plugin level? How would merging of meta work when an environment is applied?

> Does inheriting a plugin also inherit its meta?

For these two questions, I'd say it isn't up to us. How the data within this field is treated should be decided by whatever is processing it, which will never be Meltano (except to forward it into the manifest file).

**Reply by tayloramurphy** [reply]
> How the data within this field is treated should be decided by whatever is processing it, which will never be Meltano (except to forward it into the manifest file).

@WillDaSilva that makes sense to me.

**Comment by edgarrmondragon** [comment]
[`pyproject.toml` uses the TOML `tool` table](https://peps.python.org/pep-0518/#tool-table) to store third-party tool configuration, which I think makes sense for the use cases in points 3 and 4 above.

So, something like:

```yaml
tool:
  meltano-sphinx:
    html_theme: furo
```

**Comment by WillDaSilva** [comment]
I am a big fan of `annotations`. The definition of the word precises matches how we'd be using it with Meltano: to add extra data at arbitrary points within the document without it truly being part of the document. The word puts no constrains on what could go into its section, and also strongly suggests that this is extra data outside of what Meltano itself handles.

I'm not a fan of `meta` because it seems misleading. It's short for metadata, which should be data about the data (where "data" here refers to any particular configuration), rather than extra data.

I think `vendor` is alright because it describes what the section contains: vendor-specific data keyed by the vendor's name. I'm also alright with `tool` for similar reasons, but that could be misleading if some of the subsections where for e.g. an organization rather than a specific tool. The word `vendor` is more general, since I think it's fair to say it could refer to a tool, or an org, or really whatever entity wants this extra data.

So my current ranking of these options would be:
1. `annotations`
2. `vendor`
3. `tool`
4. `meta`

I'm not sure how I feel about `extra`/`extras`.

**Reply by tayloramurphy** [reply]
@WillDaSilva I'm a pretty hard no on `vendor` and `tool`. `extra(s)` would likely be a bad choice as well since we have Plugin extras defined in our docs already https://docs.meltano.com/guide/configuration#plugin-extras

`annotations` has an appeal to me, though I have a bias towards `meta`. I'd be willing to take it to the community to get some feedback on! @aaronsteers thoughts on that?

**Reply by aaronsteers** [reply]
We reviewed today in the Engineering Cloud sync. Generally, the concensus from engineering would be to use `annotations`. Adapted example below with that in context:

```yml
project_id: 90f75496-2018-4b3a-97ac-9662e11c0094
annotations:
  meltano-sphinx:
    html_theme: furo
plugins:
  extractors:
  - name: tap-gitlab
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-gitlab.git
  - name: tap-gitlab-debugging
    inherits_from: tap-gitlab
    # let Meltano Cloud know that it doesn't need this plugin
    annotations:
      meltano-cloud:
        ignore: true
  # ...
environments:
- name: dev
- name: staging
- name: prod
  annotations:
    meltano-cloud:
      branch: main
    airflow:
      ignore: true
default_environment: dev
```

The arguments for `annotations` over `meta`:

- `meta` is very similar to `metadata`, which may be side-by-side together in a plugin definition.
- A common sense interpretation of "meta" is "metadata" which isn't obviously out of scope from the Meltano Core purview. (Especially since other 'metadata' definition is part of the core capabilities/features.)
- The word "annotations" is more obviously that, an annotation and not a core part of the Meltano Core product experience.
