### DISCUSSION TITLE
Spec discussion: Meltano Cloud as an alternative config store backends

### DISCUSSION THREAD

**Discussion by aaronsteers** [meltano/meltano#7055] [Ideas]
Part of a multi-part set of feature releases:

1. https://github.com/meltano/meltano/discussions/6999
1. https://github.com/meltano/meltano/discussions/7055 _(this item)_
1. https://github.com/meltano/meltano/discussions/7056 

----------------------

```yaml
secrets_config:
  # keys: []
  # encryption_key: null
  default_store: vault://...
```

```yaml
secrets_config:
  # keys: []
  # encryption_key: null
  default_store: awskms://...
```

```yaml
secrets_config:
  # keys: []
  # encryption_key: null
  default_store: meltano.cloud
```
