### DISCUSSION TITLE
Spec discussion: allow pointers in yaml to reference settings values in other stores

### DISCUSSION THREAD

**Discussion by aaronsteers** [meltano/meltano#7056] [Ideas]
Part of a multi-part set of feature releases:

1. https://github.com/meltano/meltano/discussions/6999
1. https://github.com/meltano/meltano/discussions/7055
1. https://github.com/meltano/meltano/discussions/7056 (this item)

It would be good to have ability to place pointers to specific settings into our yaml files.

Following from https://github.com/meltano/meltano/discussions/6999 and @edgarrmondragon's comment [below](https://github.com/meltano/meltano/discussions/7056#discussioncomment-4327199), the psuedocode might look like:

```yml
plugins:
  extractors:
  - name: my-tap
    config:
      token: cfg://envvar/MY_TAP_TOKEN?dotenv=true
```

Or perhaps:

```yml
plugins:
  extractors:
  - name: my-tap
    config:
      host: https://path.to.my.host.com  # interpreted as a literal, per usual
      token(): cfg://envvar/MY_TAP_TOKEN?dotenv=true  # interpreted as an expression/pointer
```

**Comment by edgarrmondragon** [comment]
I like this! It would allow a project to be really explicit about where it expects settings to be coming from:

Wdyt of the syntax:

```yaml
plugins:
  extractors:
  - name: my-tap
    config:
      token: cfg://envvar/MY_TAP_TOKEN?dotenv=true
```

I recently saw a similar syntax in Python's logging config:

<blockquote>

```yaml
handlers:
  file:
    \# configuration of file handler goes here

  custom:
    (): my.package.MyHandler
    alternate: cfg://handlers.file
```

The literal string `'cfg://handlers.file'` will be resolved in an analogous way to strings with the `ext://` prefix, but looking in the configuration itself rather than the import namespace. The mechanism allows access by dot or by index, in a similar way to that provided by `str.format`. Thus, given the following snippet:

```yaml
handlers:
  email:
    class: logging.handlers.SMTPHandler
    mailhost: localhost
    fromaddr: my\_app@domain.tld
    toaddrs:
      \- support\_team@domain.tld
      \- dev\_team@domain.tld
    subject: Houston, we have a problem.
```

</blockquotes>

https://docs.python.org/3/library/logging.config.html#access-to-external-objects
