### DISCUSSION TITLE
refactor: Move from `variant`+`name` to a unique `plugin_id`

### DISCUSSION THREAD

**Discussion by MeltyBot** [meltano/meltano#8924] [Spec Discussions]
## Background

In the early days of Meltano, we managed all supported Meltano plugins in a single `discovery.yml` file. At that time, we had <40 taps, whereas this week (2022-11-28) we have 400+ unique plugins on the hub, with about a thousand total registrations variants.

The initial `plugin_name` was expanded to support a `variant` qualifier, which we defaulted to the organization or user name matching the owner ID of the repo in GitHub or GitLab. 

## Reasons to change

- A single `plugin_id` string or `plugin_ref` URL would simplify project maintenance. Plugins would still have `name` values in `meltano.yml` but there'd be a looser expectation around the name having unique significance outside of the `meltano.yml` file itself.

## Proposal

In place of the current {`plugin_name`, `variant`}, adopt a new unique identifier such as `plugin_id` or just use the existing `ref` as the ID.

In place of...

```
plugins:
  extractors:
  - name: tap-github
    variant: meltanolabs
#...
```

We'd have:

```
plugins:
  extractors:
  - name: tap-github
    id: tap-github--meltanolabs
#...
```

Or perhaps better:

```
plugins:
  extractors:
  - name: tap-github
    ref: https://hub.meltano.com/meltano/api/v1/plugins/extractors/tap-github--meltanolabs
#...
```

Or we could let the local lock file name server as the ID, which itself could still reference back to the remote Meltano Hub URL ref:

```
plugins:
  extractors:
  - name: tap-github
    ref: plugins/extractors/tap-github--meltanolabs.lock
#...
```

## Backwards compatibility

Backwards compatibility could be accomplished by making the new ID or Ref field optional, and when missing, calculating it on the fly as `'{plugin_id}--{variant}'` or `'meltano://{plugin_id}:{variant}'` or similar.

---

Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/213

Originally created by @aaronsteers on 2022-03-11 17:28:32

<details>
<summary>Original thread</summary>

Wanted to log this question as related to the new tap-gitlab port. I created the new port as a fresh branch under the MeltanoLabs GitHub project. I'm not sure if I'll be able to 100% match the prior behavior and at the same time, the tap can be "working" well for newer user cases.

The ideal delivery mechanism is probably to get _reasonable_ amount of backwards compatibility but not 100%, and then publish as a variant name like `meltanolabs-2` or similar. This would be a break from our current naming though, since the variant names today are expected to be exactly the same as the org name in GitHub or GitLab.

@tayloramurphy - Thoughts on this?

</details>
