### DISCUSSION TITLE
Meltano support for PEP 723 scripts

### DISCUSSION THREAD

**Discussion by edgarrmondragon** [meltano/meltano#9221] [Ideas]
1. What would it take for Meltano to run scripts with inline dependencies ([PEP 723](https://peps.python.org/pep-0723/))
2. What type use cases would this benefit? Maybe single-file taps?

## Example

This might look something like

```yaml
plugins:
  extractors:
  - name: tap-example
    namespace: tap_example
    executable: ./extractors/tap_example.py
```

```python
# /// script
# dependencies = [
#   "singer-sdk~=0.45.0",
# ]
# ///

from singer_sdk import RESTStream, Tap

...
```

## Links

- https://peps.python.org/pep-0723/
- https://docs.meltano.com/guide/advanced-topics/#running-custom-scripts
- https://github.com/meltano/sdk/pull/2986
