### ISSUE TITLE
Custom extractor did not show when the field "namespace" is mentioned in meltano.yml for model and transform.

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#1775]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/1816

Originally created by @L3houx on 2020-02-27 23:23:23

---

Hi! I had a problem. After you answered me in this [issue](https://gitlab.com/meltano/meltano/issues/1811#notes), I created a brand new project to start from scratch. I was able to get data and the transform with worked well without error, but I'm not able to see my extractor in the integration list. ![image](http://gitlab.com/meltano/meltano/uploads/6cfb435b08f3e0a7c57f38de681ef63c/image.png)
This is my file meltano.yml: 

```
plugins:
  dashboards:
  - name: dashboard-gitlab
    pip_url: git+https://gitlab.com/meltano/dashboard-gitlab.git
  extractors:
  - label: GitLab
    name: tap-gitlab
    pip_url: git+https://gitlab.com/meltano/tap-gitlab.git
  - capabilities:
    - catalog
    - discover
    - properties
    - state
    executable: tap-github
    name: tap-github
    namespace: tap_github
    pip_url: git+https://github.com/L3houx/tap-github.git
    settings:
      - env: GITHUB_API_TOKEN
        name: access_token
      - env: GITHUB_REPO
        name: repository
  loaders:
  - label: PostgreSQL
    name: target-postgres
    pip_url: git+https://github.com/meltano/target-postgres.git
  models:
  - executable: model-github
    name: model-github
    namespace: tap_github
    pip_url: git+https://github.com/L3houx/model-github.git
  - name: model-gitlab
    pip_url: git+https://gitlab.com/meltano/model-gitlab.git
  orchestrators:
  - name: airflow
    pip_url: apache-airflow==1.10.2
  transformers:
  - name: dbt
    pip_url: dbt==0.14.4
  transforms:
  - name: tap-github
    namespace: tap_github
    pip_url: https://github.com/L3houx/test-dbt-tap-github.git
    vars:
      schema: '{{ env_var(''MELTANO_LOAD_SCHEMA'') }}'
  - name: tap-gitlab
    pip_url: https://gitlab.com/meltano/dbt-tap-gitlab.git
    vars:
      schema: '{{ env_var(''MELTANO_LOAD_SCHEMA'') }}'
      ultimate_license: '{{ env_var(''GITLAB_API_ULTIMATE_LICENSE'', False) }}'
project_id: 9eca27af-e383-4c1c-a385-d6695510d82f
schedules:
- extractor: tap-github
  interval: '@once'
  loader: target-postgres
  name: pipeline-1582833278348
  start_date: 2020-02-27 19:54:38.466076
  transform: run
send_anonymous_usage_stats: true
version: 1
```  
I did : `meltano install` and `meltano install --include-related` (like you said), but I wasn't able to see the Github custom extractor in the list. The way I did to see if the transform worked was by installing Gitlab extractor and change the name in the URL to github instead of gitlab but after that, I was unable to get models and create graphs. If I edit the HTML and enable the buttons to get models and create a graph but without editing the HTML I wasn't able.

![image](http://gitlab.com/meltano/meltano/uploads/14a5b348545c51901550be9d5dbba0af/image.png)

![image](http://gitlab.com/meltano/meltano/uploads/987b79ded9685e891f95b90f39f551d8/image.png)

![image](http://gitlab.com/meltano/meltano/uploads/d63206b2daa27e878fd7f5d529921feb/image.png)

I realize that when I add this section in meltano.yml
```
transforms:
  - name: tap-github
    namespace: tap_github
    pip_url: https://github.com/L3houx/test-dbt-tap-github.git
    vars:
      schema: '{{ env_var(''MELTANO_LOAD_SCHEMA'') }}'
```

or 

```
models:
  - name: model-github
    namespace: tap_github
    pip_url: git+https://github.com/L3houx/model-github.git
```

The extractor in the Integrations list disappear and when I remove the namespace section, it appears. I also tried with a custom model and I installed it with the namespace and it did not appear. Once a removed both namespace: tap-github (transform and model), the extractor appears in the list and I was able to use model. 

I'm not sure if it is easy to understand, if not, tell me and I will try to be as clear as possible. 

Thank you and have a nice day.
