### ISSUE TITLE
Automatically create `target-jsonl` `destination_path` directory using new `before_run` command array in `meltano.yml`

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#2141]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/2185

Originally created by @DouweM on 2020-07-20 20:35:12

---

- Script can reference plugin config env vars

```yml
loaders:
- name: target-jsonl
  namespace: jsonl
  before_run:
  - mkdir -p $TARGET_JSONL_DESTINATION_PATH
```
