### ISSUE TITLE
Extractor catalog metadata key `tap-mongodb.projection` for stream is interpreted as key `projection` for property `tap-mongodb`

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#2344]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/2388

Originally created by @DouweM on 2020-10-08 23:40:12

---

See the feature described in https://github.com/singer-io/tap-mongodb#edit-catalog-file.

Side-effect of https://meltano.com/docs/command-line-interface.html#nested-properties.

We can consider changing nested property handling to interpret periods as nested property separators only in top-level `meltano.yml` keys, and assume that periods in lower level keys are there intentionally, so that there's a difference between:

```yaml
metadata:
  my_collection: # entity
    tap-mongodb.projection: '...' # metadata-key: value
```

and 

```yaml
metadata:
  my_collection.tap-mongodb.projection: '...'
```

with the latter being identical to:

```yaml
metadata:
  my_collection: # entity
    tap-mongodb: # property
      projection: '...' # metadata-key: value
```

Of course, the env vars for all of these would still be identical (`TAP_MONGODB__METADATA_MY_COLLECTION_TAP_MONGODB_PROJECTION`), meaning that you couldn't have a `tap-mongodb` property with `projection` metadata key at the same time.
