### ISSUE TITLE
Environment Variable Substitution doesn't work with array values

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#2436]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/2481

Originally created by @cooley1 on 2020-12-16 00:40:22

---

### What is the current *bug* behavior?
Environment variables can't be used in the `meltano.yml` file for arrays.

### What is the expected *correct* behavior?
The yaml parser should traverse arrays to substitute environment variables. It would also be nice to add custom yaml variable support to the parser. (e.g. `custom_var: var` -> `database: '{{ custom_var }}'`)

### Steps to reproduce
- In a `meltano.yml` file try to use an environement variable in an array.

### Relevant logs and/or screenshots
```
plugins:
  extractors:
  - name: tap-mysql
    variant: transferwise
    pip_url: pipelinewise-tap-mysql
    config:
      host: host
      user: root
      database: ${DB_NAME}
    select:
    - ${DB_NAME}-users.id
    - ${DB_NAME}-users.email
    metadata:
      ${DB_NAME}-users:
        replication-method: FULL_TABLE
```
`database: ${DB_NAME}` works because it's an object. But it doesn't work in the select because it's an array.

### Possible fixes
Not sure, sorry.

### Further regression test
_Ensure we automatically catch similar issues in the future_

- [ ] Write additional adequate test cases and submit test results
- [ ] Test results should be reviewed by a person from the team
