### ISSUE TITLE
Additional Metadata for PyPI

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#2815]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/2874

Originally created by @edgarrmondragon on 2021-07-30 22:57:22

---

## Summary

Add more project metadata fields for PyPI.

## Proposed benefits
[//]: # (Concisely summarize the benefits this feature would bring to yourself and other users.)

- More resource links in our PyPI page: https://pypi.org/project/meltano/
- Better SourceRank score: https://libraries.io/pypi/meltano/sourcerank

## Proposal details
[//]: # (In as much detail as you are able, describe the feature you'd like to build or would like to see built.)

[According to the Poetry docs](https://python-poetry.org/docs/pyproject/), we seem to be missing a few optional metadata fields:

- `maintainers`
- `homepage` (https://meltano.com)
- `documentation` (https://meltano.com/docs)
- `keywords`

We can also [add custom URLs](https://python-poetry.org/docs/pyproject/#urls):

```toml
[tool.poetry.urls]
"Issue Tracker" = "https://gitlab.com/meltano/meltano/-/issues"
"Twitter" = "https://twitter.com/meltanodata/"
"Changelog" = "https://gitlab.com/meltano/meltano/-/blob/master/CHANGELOG.md"
"Slack" = "https://join.slack.com/t/meltano/shared_invite/zt-obgpdeba-7yrqKhwyMBfdHDXsZY8G7Q"
"GitHub Mirror" = "https://github.com/meltano/meltano"
"Youtube" = "https://www.youtube.com/meltano"
```

## Best reasons not to build
[//]: # (Will this negatively affect any existing functionality? Do you anticipate any breaking changes versus what may already be working today? Make the counter-argument to your proposal here.)

None that I can think of.

A similar issue for the SDK is https://gitlab.com/meltano/sdk/-/issues/175.
