### ISSUE TITLE
Create a GitHub Action for Meltano ELT

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#2877]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/2936

Originally created by @edgarrmondragon on 2021-09-13 20:12:51

---

## Summary
[//]: # (Concisely summarize the feature you are proposing.)

GitHub Actions are a CI/CD offering with capabilities similar to those of GitLab CI, except that they can be published to the [a marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) where they get more visibility and users can add them to their projects with one click.

This action would be useful for developers that are first trying out Meltano, or don't need a full Kubernetes/cloud deployment with an orchestrator, metrics UIs, etc.

## Proposed benefits
[//]: # (Concisely summarize the benefits this feature would bring to yourself and other users.)

Give users that want to try out Meltano for ELT a way that is quick and easy.

## Proposal details
[//]: # (In as much detail as you are able, describe the feature you'd like to build or would like to see built.)

- A [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) is probably easier but we can consider a [docker action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) too.
  Either way, the action would install the latest or some configurable Meltano version for the user and any other dependencies, and also run `meltano install`.
- Inputs to the job could be: `tap`, `target`, `job_id`, `transform` and `log_level` to compose a command like

  ```shell
  meltano --log-level={log_level} elt {tap} {target} --job_id={job_id} --transform={transform}
  ```

## Best reasons not to build
[//]: # (Will this negatively affect any existing functionality? Do you anticipate any breaking changes versus what may already be working today? Make the counter-argument to your proposal here.)

This only solves ELT and very basic orchestration needs. No fancy UI for jobs and retries are manual.

**Comment by MeltyBot** [comment]
[View 5 previous comments from the original issue on GitLab](https://gitlab.com/meltano/meltano/-/issues/2936)

**Comment by sbalnojan** [comment]
@edgarrmondragon do you have an updated opinion on this one? :-) Also related: https://github.com/brooklyn-data/meltano-on-github-actions.

**Comment by edgarrmondragon** [comment]
@sbalnojan I've been using the official Docker image in my dogfooding, so the value of a dedicated Action was reduced for me.

The template you linked seems to be a bit opinionated in the plugins it includes and it uses the legacy `meltano elt` command. One thing I like of their approach is the use of artifacts to store the systemdb and use state in future runs.

We could probably still ship a docker-based action for Meltano Run.

<details><summary>Workflow using Docker image</summary>

```yaml
name: Meltano Lock Update

on:
  schedule:
  - cron: '37 */24 * * *'
  workflow_dispatch: {}

env:
  MELTANO_CLI_LOG_LEVEL: ${{ github.event.inputs.logLevel || 'warning' }}

permissions:
  contents: write
  pull-requests: write

jobs:
  meltano-lock:
    name: Meltano Lock Update
    runs-on: ubuntu-latest
    container:
      image: meltano/meltano:latest-python3.9

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.1.0

    - name: Check Meltano
      run: |
        meltano --version
    - name: Meltano Lock Update
      run: |
        meltano lock --update --all
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.0
      with:
        title: 'chore: Update Meltano Plugins'
        branch: meltano-lock-update
        commit-message: 'chore: Update Meltano Plugins'
        delete-branch: true
        reviewers: edgarrmondragon
        assignees: edgarrmondragon
        body: |
          Created with `meltano lock --update --all`
```

</details>
