### ISSUE TITLE
Add a `ui` command for the `Airflow` plugin

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#2885]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/2944

Originally created by @aaronsteers on 2021-09-21 20:09:26

---

The Airflow plugin definition does not have any pre-defined commands built. Would be nice to add a `ui` command which just quickly launches the web GUI.

Something like...

```yml
    commands: 
      ui:
         executable: airflow
         args: webserver --port 8080
```

which would go here: https://gitlab.com/meltano/meltano/blob/master/src%2Fmeltano%2Fcore%2Fbundle%2Fdiscovery.yml#L2531
