### ISSUE TITLE
Support Airflow webserver base URL as a known setting

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#2915]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/2974

Originally created by @edgarrmondragon on 2021-10-06 18:45:25

---

From Slack: https://meltano.slack.com/archives/C01TCRBBJD7/p1633464692374100

It'd be useful for some people to declare the base URL for the Airflow Webserver directly in `meltano.yml`. Something like

```yaml
plugins:
  orchestrators:
    - name: airflow
      config:
        webserver.base_url: https://my-meltano-server:8080
```
