### ISSUE TITLE
Reuse installation directory for packages with implicit dependencies

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3000]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3068

Originally created by @edgarrmondragon on 2021-11-17 01:36:01

---

Example:

`sqlfluff` uses a plugin architecture for templaters, e.g. an additional package [`sqlfluff-templater-dbt`](https://github.com/sqlfluff/sqlfluff/tree/main/plugins/sqlfluff-templater-dbt) (changed from the old pip extra `sqlfluff[dbt]`).

The plugin package `sqlfluff-templater-dbt` naturally depends on dbt and so it installs `dbt-core` (but not any adapter packages).

The problem is that having something like:

```yaml
plugins:
  transformers:
    - name: dbt
      pip_url: dbt==0.20.1
  utilities:
    - name: sqlfluff
      namespace: sqlfluff
      pip_url: sqlfluff sqlfluff-templater-dbt dbt-core dbt-postgres
      executable: sqlfluff
```

is a bit wasteful in time and resources by having to

1) create two separate virtualenvs
2) install the same packages more than once

It can also lead to inconsistent versions being used (e.g. different versions of `dbt`).

Ideally, all of `dbt`, `sqlfluff` and `sqlfluff-templater-dbt` should be installed in the same environment.
