### ISSUE TITLE
Alternative yaml config convention

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3076]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3149

Originally created by @kgpayne on 2022-01-10 17:32:04

---

As the Meltano feature-set and average project size grows, managing configuration as either a single large yaml document or with explicit `include_paths` imports may impose an upper-limit on readability/maintainability. This might be overcome by taking a similar approach to Helm or dbt, whereby all files of a certain type below a specified directory are assumed to contain Meltano config objects and are parsed (and therefore referencable). Following the Helm/Kubernetes resource-centric model (and resurrecting and repurposing the `.m5o` file type?), a Loader Plugin might look like:

```yaml
# loaders/athena.m5o
---
version: 1
kind: Loader
metadata:
  name: target-athena
  namespace: target_athena
spec:
  pip_url: git+https://github.com/pnadolny13/target-athena.git@bump_sdk_version
  settings:
  - name: aws_access_key_id
    kind: password
  - name: aws_secret_access_key
    kind: password
  - name: s3_bucket
    kind: string
  - name: athena_database
    kind: string
  - name: s3_staging_dir
    kind: string
  - name: work_group
    kind: string
  - name: add_record_metadata
    kind: boolean
  - name: flatten_records
    kind: boolean
  - name: object_format
    kind: string
  config:
    aws_region: us-east-2
    aws_access_key_id:
      secretKeyRef:
        name: athena-secrets
        key: AWS_ACCESS_KEY_ID
    aws_secret_access_key:
      secretKeyRef:
        name: athena-secrets
        key: AWS_SECRET_ACCESS_KEY
    object_format: jsonl
    temp_dir: .output
    add_record_metadata: true
    flatten_records: true
```

Adding new plugins off the same kind might result in either a new file (sharing the name of the plugin) or a new document in an existing `loaders.m5o` file (using the `---` yaml document syntax). Each resource type would have its own schema definition and be validatable. Plugins registering new resource types will be expected to supply this schema.

This approach lends itself well to [Inventory](https://gitlab.com/meltano/meltano/-/issues/3108) too:

```yaml
# inventory/snowflake.m5o
---
version: 1
kind: Warehouse
metadata:
  name: snowflake
  label: snowflake-prod
spec:
  account: "<snowflake account name>"
  default_database: "<snowflake database name>"
  region: "<warehouse region>"
  warehouse: "<snowflake warehouse name>"

---
version: 1
kind: WarehouseConnection
metadata:
  name: snowflake-connection-dbt
  label: snowflake-prod
spec:
  warehouse: snowflake # references the warehouse above
  database: "analytics"
  username: "dbt"
  password:
    secretKeyRef:
      name: snowflake-secrets
      key: password
  role: "dbt"
  session_parameters: "<session level parameters>"
```
