### ISSUE TITLE
Missing settings in the UI for _state / _catalog and settings in inherited plugins

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3106]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3179

Originally created by @ebnermic on 2022-01-24 18:03:44

---

### What is the current *bug* behavior?
When adding the `_state` or `_catalog` as as setting in a plugin, this setting is recongnized (value is taken into account), but the setting is not shown in the plugin configuration in the UI. Those two settings are extra settings for an extractor plugins. The [state](https://meltano.com/docs/plugins.html#state-extra) and the [catalog](https://meltano.com/docs/plugins.html#catalog-extra) are both documented.

Additionaly, settings in inherited plugins (non inherited settings) are not shown in the plugin configuration in the UI. But once configured over the CLI, the setting is visible in the UI.

### What is the expected *correct* behavior?
All the plugin relaated settings should be shown and editable in the UI (unless set as non editable). 

### Steps to reproduce
Set _state and _catalog as followed for an extractor plugin:
```
settings:
 - name: _state
   kind: string
 - name: _catalog
   kind: string
```

For the problem with inheritent settings you will see it by configurating a target as follows:
```
  - name: target-stitch
    namespace: target_stitch
    pip_url: target-stitch
    executable: target-stitch
    settings:
    - name: client_id
      kind: integer
    - name: small_batch_url
      kind: string
    - name: big_batch_url
      kind: string
  - name: target-stitch-test
    inherit_from: target-stitch
    settings:
      - name: token
        kind: password
```

The token won't be visible when configurating over the UI. But as soon as you set the token over the UI with the following command: 

`meltano config target-stitch-test set token test123`

You will now see the token field in the UI and be able to edit it.
