### ISSUE TITLE
Consider wrapping `dbt init` to add the appropriate profile for a given adapter

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3130]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3203

Originally created by @edgarrmondragon on 2022-02-01 19:48:28

---

### Problem to solve

Creating a `profiles.yml` specific to the dbt adapter, either using the adapter's built-in (e.g. for [`dbt-postgres`](https://github.com/dbt-labs/dbt-core/blob/main/plugins/postgres/dbt/include/postgres/profile_template.yml)) or a custom `profile_template.yml` for each adapter type.

https://docs.getdbt.com/reference/commands/init

### Target audience

Users of dbt _in_ Meltano.

### Further details

`dbt init` is the standard to get started on a new dbt project or setup a personal profile for an existing one.

### Proposal

Having a profile template (for PostgreSQL)

```yaml
# transform/profile_template.yml
fixed:
  host: "{{ env_var('TARGET_POSTGRES_HOST') }}"
  port: "{{ env_var('TARGET_POSTGRES_PORT') | int }}"
  user: "{{ env_var('TARGET_POSTGRES_USER') }}"
  pass: "{{ env_var('TARGET_POSTGRES_PASSWORD') }}"
  dbname: "{{ env_var('TARGET_POSTGRES_DBNAME') }}"
  type: postgres
  schema: public
prompts: {}
```

Then running

```console
$ meltano invoke dbt init
19:30:52  Running with dbt=1.0.1
19:30:52  Setting up your profile.
19:30:52  Profile meltano written to /Users/edgarramirez/projects/try-dbt-init/transform/profile/profiles.yml using project's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
```

results in the following

```yaml
# transform/profile/profiles.yml
meltano:
  outputs:
    dev:
      dbname: '{{ env_var(''TARGET_POSTGRES_DBNAME'') }}'
      host: '{{ env_var(''TARGET_POSTGRES_HOST'') }}'
      pass: '{{ env_var(''TARGET_POSTGRES_PASSWORD'') }}'
      port: '{{ env_var(''TARGET_POSTGRES_PORT'') | int }}'
      schema: public
      type: postgres
      user: '{{ env_var(''TARGET_POSTGRES_USER'') }}'
  target: dev
```

### What does success look like, and how can we measure that?

Starting and configuring a dbt project with Meltano is smoother.

### Regression test
(Ensure the feature doesn't cause any regressions)
- [ ] Write adequate test cases and submit test results
- [ ] Test results should be reviewed by a person from the team

### Links / references

_Please note that this was taken from GitLab, to be changed accordingly_
