### ISSUE TITLE
Transform (DBT) settings of kind:password not setting in .env

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3139]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3213

Originally created by @vischous on 2022-02-03 21:40:37

---

**Setup**
```
  transformers:
  - name: dbt
    pip_url: dbt-postgres==1.0.0
    settings:
    - name: password
      kind: password
    config:
      target: postgres
      host: localhost
      port: 5432
      user: postgres
      dbname: postgres
```

**Run**
1. meltano config dbt set password abcde

Meltano will place the password in `meltano.yml` .

**Fix**
```
  transformers:
  - name: dbt
    namespace: dbt_postgres
    pip_url: dbt-postgres==1.0.0
    settings:
    - name: password
      kind: password
    config:
      target: postgres
      host: localhost
      port: 5432
      user: postgres
      dbname: postgres
```

**Notes**
- Haven't tried this before with transforms. Thought came up after the chat at office hours that I want to run dbt standalone so why not just pass in the configs I need (even if I"m duplicating them for another target and tap. ) 
- Use case is I run dbt standalone, and I'd rather keep profiles.yml in my meltano project in order to define configuration values in one place.  

Slack thread: https://meltano.slack.com/archives/C01TCRBBJD7/p1643923463011509
