### ISSUE TITLE
Provide more control over which plugins are installed by default (faster Prod installs without local/dev plugins)

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3167]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3241

Originally created by @pnadolny13 on 2022-02-11 19:24:04

---

As part of https://gitlab.com/meltano/meltano/-/issues/3231#note_840290255 we discussed having a way to flag plugins as non-prod plugins so our docker images dont get unnecessarily big filled with dev dependencies. Right now you'd have to explicitly run each install to exclude certain plugins, its not the worst experience but a flag like this would make it cleaner.

> Additionally it might be helpful to flag plugins somehow as prod installable, like I dont need SqlFluff, permifrost, superset, Airflow, when packaging so I need to [install each explicitly](https://gitlab.com/meltano/squared/-/merge_requests/55/diffs).

<details><summary>Click to expand background</summary>

@edgarrmondragon had suggested:

>[Poetry's dependency groups](https://python-poetry.org/docs/master/managing-dependencies#dependency-groups) and [pip extras](https://www.python.org/dev/peps/pep-0508/#extras) come to mind as inspiration. Wdyt?

Like poetry `poetry install --no-dev`. Maybe we can use the environments feature for this. Like `exclude_install` could be set in an environment config so in the dev environment all are installed but in prod certain are excluded, defaulting to install all if not defined. Then `meltano --environment=prod install` would exclude the appropriate plugins.

```yaml
environments:
- name: prod
  exclude_install:
    - - sqlfluff
      - permifrost
      - airflow
      - superset
  config:
    plugins:
      extractors:
      - name: tap-google-analytics
        config:
          start_date: '2021-11-08'
```

</details>

-----

## Updated proposal: 2022-04-25 from AJ

* maintain the current behavior with `meltano install` installing everything
* Enable `meltano install` to accept a flag specifying the environment

<details><summary>Click to expand</summary>

```
meltano install --environment=prod
```

This would only install plugins that are explicitly included in the environment with the minimum configuration required being the name:

```yml
environments:
- name: prod
  config:
    plugins:
      extractors:
      # This is being customized so it definitely should be installed
      - name: tap-google-analytics
        config:
          start_date: '2021-11-08'
      # These are not customized but their reference here triggers them
      # to be installed when `prod` environment is requested:
      - name: tap-spotify
      - name: tap-gitlab
      loaders:
      # No changes to the loader but we list it anyway:
      - name: target-snowflake
      # ...
```

</details>

## Update (2022-04-27)

An alternate proposal we came up with here: https://gitlab.com/meltano/meltano/-/issues/3241#note_925253179

1. Add support for `--exclude <plugin-name>` (or `-E <plugin-name>`) which could be added any number of times, either after `meltano install` (which otherwise installs *everything*) and/or `meltano install <plugin-type>` (which otherwise installs everything under a specific category)
1. Allow multiple plugins of different types to be specified inline (just like `pip install` does): `meltano install tap-github tap-slack target-snowflake dbt`
    * If a name collision occurs between plugins, we'd install all plugins with the give name.
