### ISSUE TITLE
Meltano Mappers and Mappings Discussion Issue

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3233]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3310

Originally created by @tayloramurphy on 2022-03-03 19:04:19

---

After a deep discussion with @aaronsteers and @pandemicsyn we've landed on several decisions. 

### User Experience

Starting from the user experience. We want to support users invoking mappers as they would a normal plugin. This means:

`meltano invoke <mapper>` should work and accept data from the STDIN and push data to STDOUT

`meltano run tap-gitlab <mapper> target-snowflake` - this is invoking the plugin in between the tap and target. 

This is different than what is currently implemented - right now you reference a particular mapping name and not the mapper itself. 

We also aim to support locally-scoped mappings for extractors and loaders. These would not be able to be referenced via `meltano run` directly - only via the extractor. 

### YAML Spec for Inheritance-based Mappings

Where we want to end up for the `mappers` spec

```yaml
# meltano.yml
mappers:
- name: transform-field
  namespace: pipelinewise_transform_field
  pip_url: pipelinewise-transform-field
  executable: transform-field    
- name: hide-gitlab-secrets
  inherit_from: transform-field
  config:
    transformations:
      - field_id: "author_email"
        tap_stream_name: "commits"
        type: "MASK-HIDDEN"
      - field_id: "committer_email"
        tap_stream_name: "commits"
        type: "MASK-HIDDEN"
- name: null-created-at
  inherit_from: transform-field
  config:
    transformations:
      - field_id: "created_at"
        tap_stream_name: "accounts"
        type: "SET-NULL"
```

A user could run `meltano invoke hide-gitlab-secrets` and the appropriate config would be passed to the mapper. A user could also do `meltano invoke tap-gitlab | meltano invoke hide-gitlab-secrets` and that should work.

### Local Scoping

To implement locally scoped mappers users would have two options. If the tap is based on the SDK and supports the `stream-maps` capability, users would have to set the configuration in the normal `config` key. _Users can do this today already with SDK-based taps and targets_.

```yaml
- name: tap-github
  capabilities:
    - stream-maps
  config:
    stream_maps:
        - field_id: "created_at"
          tap_stream_name: "accounts"
          type: "SET-NULL"  
```

This would not be referencable on the command line and would assumed to be "always on".

For connectors that do not support the `stream-maps` capability, we would (re-)introduce the `mappings` key as a plugin extra for extractors and loaders. 

Proposed spec

```yaml
extractors:
- name: tap-gitlab
  mappings:
    - name: gitlab-null       # locally unique name of the mapping
      active: false           # new boolean key for whether a mapping is active or not
      mapper: null-created-at # the mapper plugin to use
      config:                 # The config that is passed to the mapper
        transformations:
          - field_id: "created_at"
            tap_stream_name: "accounts"
            type: "SET-NULL"


```

There is an open question on how we would want to merge the config from this. Our options are to keep the default (which we believe is 1 level deep), replace the `config` block entirely, or do a deep merge. The challenge with the 1 level deep merge is that in the above example, the entire `transformations` value would be overwritten. 

Behind the scenes, when a `mapper` is referenced, the data from the tap is sent to the mapper before being sent to any other target. 

Question: Is there a limit to the number of mappings and/or mappers when they are locally scoped?

Key points when referencing a mapper:

* Users could not reference a mapping defined at the extractor or loader level either in the meltano invoke or the meltano run commands. We could separately discuss if we want to overload the colon syntax to invoke a specific mapper via `meltano invoke <tap>:<mapping_name>`
* the `mappings` key is incompatible with the `stream-maps` capability, at least for this proposed implementation (this makes sense as `stream-maps` is a capability _of the tap_ while mappings are config for a separate mapper plugin)

### How does this work with environments?

A key behavior we would want to support is turning mappings on and off depending on the environment. This is accomplished via the `active` key. Environments would be used to override that configuration. Users would not be able to activate a mapper from the command line in `meltano run` (except via the environment).

```yaml
environments:
  - name: prod
    config:
      plugins:
        extractors:
        - name: tap-gitlab
          mappings:
            - name: gitlab-null
              active: true
            - name: sw-region-only
              config:
                transformations: ...          
        mappers:
        - name: null-created-at
          config:
            transformations:
              ...
```

Overwriting the `active` key is new behavior as currently it's only scoped to `config`.

There's also the consideration of priority order. 

If a user overrides configuration of a mapper at the environment level, that would take precedence when the mapper is invoked either via run or invoke (this is expected and standard with environments).

If a user overrides configuration of a mapper that is also referenced as a mapping for an extractor, we would expect no configuration changes to affect the extractor. Said another way, the configuration of a plugin in an environment should not affect the configuration of another plugin in the same environment. 
Said a third time - the locally scoped mapping configuration for an extractor should be determined based on the configuration outside the context of the environment before applying the environment configuration. 

This should avoid the situation of updating global configuration for a plugin in two places (mapper vs extractor).

```yaml
# meltano.yml
mappers:
- name: transform-field
  namespace: pipelinewise_transform_field
  pip_url: pipelinewise-transform-field
  executable: transform-field    
- name: hide-gitlab-secrets
  inherit_from: transform-field
  config:
    transformations:
      - field_id: "author_email"
        tap_stream_name: "commits"
        type: "MASK-HIDDEN"
extractors:
- name: tap-gitlab
  mappings:
    - name: gitlab-secrets       # locally unique name of the mapping
      active: false           # new boolean key for whether a mapping is active or not
      mapper: hide-gitlab-secrets # the mapper plugin to use
      config:                 # The config that is passed to the mapper
        transformations:
          - field_id: "created_at"
            tap_stream_name: "accounts"
            type: "SET-NULL"

environments:
  - name: prod
    config:
      plugins:
        extractors:
        - name: tap-gitlab
          mappings:
            - name: gitlab-secrets
              active: true
        mappers:
        - name: hide-gitlab-secrets
          config:
            transformations:
              - field_id: "committer_email"
                tap_stream_name: "commits"
                type: "MASK-HIDDEN"
```

With the above `meltano.yml` if we do `meltano --environment=prod run tap-gitlab target-snowflake` The expected config is based on the `gitlab-secrets` mapping coming from the environment. The `hide-gitlab-secrets` config defined in the environment would _only_ apply if the the user did `meltano --environment=prod run tap-gitlab hide-gitlab-secrets target-snowflake` or they did `meltano --environment=prod invoke hide-gitlab-secrets`.

### Summarize Remaining Questions:

1. How deep do we want to merge configuration? As a first pass I'm ok with keeping the current default behavior and having a separate discussion to adjust it.

1. Is there a limit to the number of mappings a user can have when they're locally scoped?

1. Is the environment behavior agreed upon and expected?

1. Do we want to overload the colon so that specific mappings could be referencing only within `meltano invoke <tap>:<mapping_name>`?
