### ISSUE TITLE
Support evidence.dev as a plugin

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3264]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3341

Originally created by @edgarrmondragon on 2022-03-17 17:02:14

---

### Problem to solve

[Evidence](https://evidence.dev/) advertises as "Business Intelligence for Modern Data Teams" using just SQL and Markdown.

### Target audience

Any developers that

1. want to integrate a BI tool with support for version control and modern front-end dependencies (Svelte) into their stack,
1. are already using Evidence and other MDS tools (dbt, etc.) but would benefit from managing configuration centrally as part of a Meltano project as well as creating reports in sequence:

   ```shell
   meltano run tap-gitlab target-snowflake dbt:run evidence:build
   ```

   ```mermaid
   graph LR;
   t1[EL] --> t3[Transform];
   t3 --> t5[Build Report Site];
   ```

### Further details

- It is npm-based so the container spec might need to be used.

#### YAML Definition (WIP)

```yaml
plugins:
  utilities:
  - name: evidence
    commands:
      build:
        working_dir: $MELTANO_PROJECT_ROOT/analyses
        command: docker build --name=meltano--evidence .
      init:
        working_dir: $MELTANO_PROJECT_ROOT/analyses
        container_spec:
          image: meltano--evidence
          command: npx degit evidence-dev/template evidence
          volumes:
          - "$MELTANO_PROJECT_ROOT/analyses/:/usr/app/"
      serve:
        container_spec:
          image: meltano--evidence
          command: npm run dev
          volumes:
          - "$MELTANO_PROJECT_ROOT/analyses/evidence:/usr/app/"
```

### What does success look like, and how can we measure that?

Users can use Evidence in their data development workflow.

### Regression test

- [ ] Write adequate test cases and submit test results
- [ ] Test results should be reviewed by a person from the team

### Links / references

- [Hacker News](https://news.ycombinator.com/item?id=28304781)
