### ISSUE TITLE
Top-level 'warehouse' definition in `meltano.yml`.

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3266]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3343

Originally created by @aaronsteers on 2022-03-22 21:18:25

---

## Proposal

1. Allow 'warehouses' to be defined - either under 'plugins' or as a peer to 'plugins'.
   1. If we go the route of warehouses being a type of plugin, these would probably start off as "dummy" plugins, which primarily lend a paradigm for defining the warehouse definition once, as a shared resource for other plugins.
   1. If we go the route of having `warehouses` as peer to `plugins` and `environments`, we lose some of the inheritance and override capabilities that plugins have automatically.
2. Each environment should have exactly one defined `warehouse:` or `primary_warehouse:` entry.
   1. If a warehouse is not defined, then calls to warehouse-related config should fail.
3. We can inject the environment's warehouse settings into plugin's defaults.

## Warehouses as 'passthrough' settings buckets

In v1, a warehouse plugin would pretty much be a passthrough construct:

1. They can all be `--custom` in MVP, meaning the developer can define basically arbitrary strings as 'settings' and we don't need to centrally manage the ontology of each adapter.
2. Any number of settings can be configured or customized according to the user's needs.
3. We'd probably standardize on a few recommended best practice settings names: `database`, `schema`, and perhaps `adapter_type`.

## Warehouses as 'proper' plugins

Over time, variants/forks of a warehouse definition could get 'smarter' and more capable, for instance installing the snowflake CLI.

Note:

- There's probably a counter-argument that `snowflake-cli` would make a better `utility` plugin, rather than a being part of the top-level `warehouse`.

## Warehouses as 'plugins'

The below sample code is derived from the meltano squared repo. This assumes we have the warehouse itself as a custom plugin, able to be defined at the top level under "plugins", with settings overriden.

```yml
version: 1
plugins:
  warehouses:
  - name: snowflake
    config:
      account: meltano
      user: dbt_loader
      raw_db: raw
      raw_schema: raw
      transform_db: marts
      transform_schema: default
      compute_warehouse: loader_wh
  - name: athena
    config: [/*...*/]

  loaders:
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      account: ${WAREHOUSE_ACCOUNT}
      file_format: CSV
      add_metadata_columns: true
      password: ${SNOWFLAKE_PASSWORD}
  - name: target-snowflake-github-search
    inherit_from: target-snowflake
    config:
      default_target_schema: GITHUB_SEARCH

  transformers:
  - name: dbt-snowflake
    pip_url: 'dbt-core~=1.0.0 dbt-snowflake~=1.0.0'
    config:
      target: snowflake
      models: squared
      sf_password: ${WAREHOUSE_PASSWORD}
      sf_account: ${WAREHOUSE_ACCOUNT}
      sf_user: ${WAREHOUSE_USER}
      sf_role: ${WAREHOUSE_ROLE}
      sf_database_raw: ${WAREHOUSE_RAW_DB}_${MELTANO_ENVIRONMENT}  # Renders as `raw_prod` in the prod environment
      sf_database_prep: ${WAREHOUSE_TRANSFORM_DB}_${MELTANO_ENVIRONMENT}
      sf_database_prod: ${WAREHOUSE_TRANSFORM_DB}_${MELTANO_ENVIRONMENT}
      sf_warehouse: ${WAREHOUSE_COMPUTER_WAREHOUSE}
    # ...

  extractors:
  # ... Normal taps defined here.
  - name: tap-snowflake  # for reverse ETL
    namespace: tap_snowflake
    pip_url: git+https://github.com/pnadolny13/pipelinewise-tap-snowflake.git@add_role_support
    executable: tap-snowflake
    capabilities:
    - properties
    - discover
    - state
    config:
      account: ${WAREHOUSE_ACCOUNT}
      user: ${WAREHOUSE_USER}
      password: ${WAREHOUSE_PASSWORD}

environments:
  - name: prod
    primary_warehouse: snowflake
    plugins:
      warehouses:
      - name: snowflake
        config:

```

## Passthrough setting dialect

In the above, I'm borrowing existing paradigm from elsewhere in Meltano so that `${WAREHOUSE_<SETTING_NAME>}` would resolve to the equivalent of jinja psuedocode `${{ this.warehouse.get('setting_name') }}`. 

This works well as long as each environment has a primary warehouse set, and assuming we don't need random access to arbitrary warehouse specs.

(We can alternatively consider if we should build [#3112](https://gitlab.com/meltano/meltano/-/issues/3112) first, in order to provide more expressiveness.)

## Intelligent "warehouse-aware" defaults for other plugins

If a plugin developer knows they want to leverage some generic attribute from the warehouse spec, their default value can leverage the env var defaults which are sensible for that context. For instance, the `account` setting in `target-snowflake` could have a default value of `WAREHOUSE_ACCOUNT`.
