### ISSUE TITLE
docs: Would it be 'good practice' to declare a plugins used/required env vars as custom settings in `meltano.yml`?

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3279]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3356

Originally created by @kgpayne on 2022-03-29 14:35:03

---

In working on [#3105](https://gitlab.com/meltano/meltano/-/issues/3105), using the [squared]() project as example, I have noticed that there is a disparity between settings declared by the `dbt` entry in `discovery.yml` and the settings required to actually invoke dbt in our specific Project:

```yaml
# discovery.yml
transformers:
- name: dbt
  namespace: dbt
  docs: https://meltano.com/docs/transforms.html
  repo: https://github.com/fishtown-analytics/dbt
  pip_url: dbt==0.21.1
  settings:
  - name: project_dir
    value: $MELTANO_PROJECT_ROOT/transform
  - name: profiles_dir
    env: DBT_PROFILES_DIR
    value: $MELTANO_PROJECT_ROOT/transform/profile
  - name: target
    value: $MELTANO_LOAD__DIALECT
  - name: source_schema
    value: $MELTANO_LOAD__TARGET_SCHEMA
  - name: target_schema
    value: analytics
  - name: models
    value: $MELTANO_TRANSFORM__PACKAGE_NAME $MELTANO_EXTRACTOR_NAMESPACE my_meltano_project
```

```yaml
# meltano.yml
plugins:
  transformers:
  - name: dbt
    pip_url: 'dbt-core~=1.0.0 dbt-snowflake~=1.0.0'
    config:
      target: snowflake
      models: squared
      sf_password: ${SNOWFLAKE_PASSWORD}
      sf_account: epa06486
      sf_user: foo
      sf_role: foo
      sf_database_raw: foo
      sf_database_prep: foo
      sf_database_prod: foo
      sf_warehouse: foo
```

Note the extra `sf_*` config values 🤔 These values are required as they are referenced in both our (custom) `profiles.yml` and `dbt_project.yml` files:

```yaml
# profiles.yml
config-version: 2
version: 2
config:
  send_anonymous_usage_stats: True
  use_colors: True
meltano:
  target: "{{ env_var('DBT_TARGET', env_var('SQLFLUFF_TARGET', '')) }}"
  outputs:
    snowflake:
      type: snowflake
      threads: 4
      account: "{{ env_var('DBT_SF_ACCOUNT', env_var('SQLFLUFF_SF_ACCOUNT', '')) }}"
      user: "{{ env_var('DBT_SF_USER', env_var('SQLFLUFF_SF_USER', '')) }}"
      password: "{{ env_var('DBT_SF_PASSWORD', env_var('SNOWFLAKE_PASSWORD')) }}"
      role: "{{ env_var('DBT_SF_ROLE', 'TRANSFORMER') }}"
      database: "{{ env_var('DBT_SF_DATABASE_PREP', 'sqlfluff_placeholder') }}"
      warehouse: "{{ env_var('DBT_SF_WAREHOUSE', 'sqlfluff_placeholder') }}"
      schema: "DEFAULT"
``` 

```yaml
# dbt_project.yml
...
models:
  squared:

    # ------------------
    # Staging
    # ------------------
    staging:
      +database: "{{ env_var('DBT_SF_DATABASE_PREP', 'sqlfluff_placeholder') }}"
      github_search:
        +materialized: table
        +schema: github_search
      google_analytics:
        +materialized: table
        +schema: google_analytics
      gitlab:
        +materialized: table
        +schema: gitlab
      github_labs:
        +materialized: table
        +schema: github_labs
      slack:
        +materialized: table
        +schema: slack
    # ------------------
    # Publish
    # ------------------
    publish:
      +materialized: table
      +database: "{{ env_var('DBT_SF_DATABASE_PROD', 'sqlfluff_placeholder') }}"
      meltano_hub:
        +schema: meltano_hub
    # ------------------
    # Marts
    # ------------------
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_SF_DATABASE_PROD', 'sqlfluff_placeholder') }}"
      telemetry:
        +schema: telemetry
      community:
        +schema: community
```

For readability, maintainability and 'self documentation', it would be useful to have a record of these custom required settings and their meaning (description) in `meltano.yml` by adding them as settings to the `dbt` plugin definition (as you would with a custom plugin/utility):

```yaml
# meltano.yml
plugins:
  transformers:
  - name: dbt
    pip_url: 'dbt-core~=1.0.0 dbt-snowflake~=1.0.0'
    settings:
    # new custom settings, with name, type, description and default values
    - name: sf_password
      description: Snowflake User password, consumed by `profiles.yml`.
      value: ${SNOWFLAKE_PASSWORD}
    - name: sf_user
      description: Snowflake User, consumed by `profiles.yml`.
      value: foo
    ...
    config:
      target: snowflake
      models: squared
      sf_password: ${SNOWFLAKE_PASSWORD}
      sf_account: epa06486
      sf_user: foo
      sf_role: foo
      sf_database_raw: foo
      sf_database_prep: foo
      sf_database_prod: foo
      sf_warehouse: foo
```

As we move to adapter-specific implementations for dbt ([#3105](https://gitlab.com/meltano/meltano/-/issues/3105)), this specific example may largely go away (by making user/account/password etc. required rather than custom values in dbt-snowflake etc.), however in other cases where plugins and utilities support retrieving arbitrary environment variables as input it would be useful to provide guidance about whether these custom env vars could and should be added to `meltano.yml` as custom settings for visibility and Project self-documentation.
