### ISSUE TITLE
Allow defining required environment variables

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3348]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3426

Originally created by @pnadolny13 on 2022-04-20 18:09:54

---

Its common for projects to have a .env file with user or development secrets which is git ignored, along with a sample of that .env that is checked into git for users to know what environment variables to set when they clone the project.

Meltano could allow you to set these as env vars as required so it can fail if they arent set instead of relying on users to read the sample file and export them properly. They can be set at the environment level to allow for variation based on environment.

Squared Project Use Case:

For ELT development the Squared project has isolated environments inside Snowflake that are configured based on some local settings: 
- the [USER_PREFIX](https://gitlab.com/meltano/squared/-/blob/master/data/environments.meltano.yml#L116) set in the meltano.yml which is propagated throughout to create the isolation
- the snowflake password thats stored once in the [.env](https://gitlab.com/meltano/squared/-/blob/master/data/.env.template#L18) so it can be shared by dbt/target-snowflake/great expectations.

The setup instructions tell the user to edit the meltano.yml and set the USER_PREFIX to their name (i.e. pnadolny) but thats not ideal because theres always a diff when trying to commit something. The other option is to remove it from the meltano.yml and set it in the .env file, which works but it not ideal because someone can easily forget to add it and without any validation the dbt configuration ends up writing to `USERDEV._PROD.TABLE_NAME` instead of `USERDEV.PNADOLNY_PROD.TABLE_NAME` because USERDEV is null and is not validated.

```yaml
environments:
- name: userdev
  config:
    plugins:
      extractors:
        ...
  required_env_vars:
    - USER_PREFIX
  env:
    OTHER_HARD_CODED_ENVS: foo
```

```bash
# .env file
USER_PREFIX=pnadolny
```

**Comment by aaronsteers** [comment]
We could likely solve this with a new feature flag that fails execution if an environment variable reference is not available. 

By taking a feature flag approach, any users who really want to silently take an empty string instead of a failure could do so. (Primarily for legacy compatibility reasons, I would think.)

But eventually the default behavior should be: if you reference an environment variable explicitly, that variable shouldn't be null.

We could also add parsing logic so that `:-` is handled to coalesce to another value if the named env var is not declared:

As described here: https://unix.stackexchange.com/a/62337/487180


```yml
environments:
  prod:
    env:
      SAMPLE1: ${DOESNT_EXIST}.   ## hard failure: "Required environment variable `DOESNT_EXIST` doesn't exist."
      SAMPLE2: ${DOESNT_EXIST:-}.   ## returns empty string ('')
      SAMPLE3: ${DOESNT_EXIST:-default}.   ## returns 'default'
```
