### ISSUE TITLE
setting usage stats to false sets it in the dev environment

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6101]
2.0 bug - ran `meltano config meltano set send_anonymous_usage_stats false` and got:

```yaml
environments:
- name: dev
  config:
    send_anonymous_usage_stats: false
```
