### ISSUE TITLE
Ignore setting values when selecting store location and store=auto

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6116]
Given the following meltano.yml

```yaml
default_environment: dev
plugins:
  extractors:
  - name: tap-github
    variant: singer-io
    pip_url: tap-github
    config:
      repository: meltano/meltano
environments:
- name: dev
- name: staging
- name: prod
```

if I run `meltano --environment=prod config tap-github set repository "meltano/meltano meltano/hub"`

I get 

```yaml
default_environment: dev
plugins:
  extractors:
  - name: tap-github
    variant: singer-io
    pip_url: tap-github
    config:
      repository: meltano/meltano meltano/hub
environments:
- name: dev
- name: staging
- name: prod
```

another scenario I tested:

```yaml
default_environment: dev
plugins:
  extractors:
  - name: tap-github
    variant: singer-io
    pip_url: tap-github
environments:
- name: dev
- name: staging
- name: prod
```

`meltano config tap-github set repository "meltano/meltano"`

```yaml
default_environment: dev
plugins:
  extractors:
  - name: tap-github
    variant: singer-io
    pip_url: tap-github
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-github
        config:
          repository: meltano/meltano
- name: staging
- name: prod
```

`meltano --no-environment config tap-github set start_date "some_date"`

```yaml
default_environment: dev
plugins:
  extractors:
  - name: tap-github
    variant: singer-io
    pip_url: tap-github
    config:
      start_date: some_date
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-github
        config:
          repository: meltano/meltano
- name: staging
- name: prod
```

`meltano --environment=prod config tap-github set start_date "some_other_date"`

```yaml
# UNEXPECTED RESULT
default_environment: dev
plugins:
  extractors:
  - name: tap-github
    variant: singer-io
    pip_url: tap-github
    config:
      start_date: some_other_date
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-github
        config:
          repository: meltano/meltano
- name: staging
- name: prod
```

`meltano --environment=prod config tap-github set start_date "some_other_date" --store=meltano_environment`

```yaml
#EXPECTED RESULT
default_environment: dev
plugins:
  extractors:
  - name: tap-github
    variant: singer-io
    pip_url: tap-github
    config:
      start_date: some_other_date
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-github
        config:
          repository: meltano/meltano
- name: staging
- name: prod
  config:
    plugins:
      extractors:
      - name: tap-github
        config:
          start_date: some_other_date
```

### Updated Spec Proposal (AJ, 2022-06-14)

https://github.com/meltano/meltano/issues/6116#issuecomment-1155873908
