### ISSUE TITLE
Verify `meltano install` telemetry fires for malformed plugin entries

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6117]
In #6109 @pnadolny13 noticed that with the following entry no events where fired:

```yaml
  - name: tap-something-invalid
    variant: meltanolabs
    pip_url: git+https://github.com/foo/tap-something-invalid.git
```

I wasn't able to reproduce that at the time and did see two events (started/aborted) come across. We should double check though, its entirely possible that my local dev setup had a seperate issue that was triggering the `aborted` event.
