### ISSUE TITLE
Telemetry - State change not firing

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6123]
Related to https://github.com/meltano/meltano/issues/6032

I havent seen any state change events come through yet and I tried my best to get them to fire locally with no luck. I confirmed I didnt have any anonymous usage settings in my environment, then ran these steps with my pip install version 2.0.0:

1. Init project `MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS='["http://localhost:9090"]' meltano init test_opt_out_1`
1. `cd test_opt_out_1` Note I dont see an analytics.json file in my .meltano folder
```yaml
version: 1
default_environment: dev
project_id: 327b8c41-e2ce-4dce-a70c-fac6adeb42d9
environments:
- name: dev
- name: staging
- name: prod
```
3. Add tap-csv `MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS='["http://localhost:9090"]' meltano add extractor tap-csv`
- I see a structured event fire (unstruct events were added but havent been released yet)
4. Copy/Paste config to tap-csv so it will run without failing
```yaml
version: 1
default_environment: dev
project_id: 327b8c41-e2ce-4dce-a70c-fac6adeb42d9
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-csv
        config:
          files:
          - entity: customers
            path: [MY_PATH]/customers.csv
            keys:
            - id
- name: staging
- name: prod
```
6. Invoke tap-csv `MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS='["http://localhost:9090"]' meltano invoke tap-csv`
- I see unstruct start and complete events plus the legacy struct event
7. Add `send_anonymous_usage_stats: false` to my meltano.yml and run again `MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS='["http://localhost:9090"]' meltano invoke tap-csv` 
- No events fired at all

cc @tayloramurphy @aaronsteers @WillDaSilva @pandemicsyn
