### ISSUE TITLE
Meltano not showing error if database user does not have access to table

### ISSUE THREAD

**Issue by techtangents** [meltano/meltano#6147]
I use Meltano to read from postgres and write to RedShift. I added a new table to the "select" clause - the "subdomain" table shown in the below config. The Meltano postgres user didn't have access to the table. However, this resulted in no errors from Meltano. I did get an error from DBT when it tried to do a transform based on this table, but I would have expected an error during extraction.

I asked this on the Meltano Slack and was given an explanation that this is due to how the "select" clause works. Meltano gets a list of all tables, then filters based on the select list. The input list didn't have the "subdomain" table, so Meltano had nothing to filter.

I wonder if it's possible to finesse this. To do that, I think the select rows would need to be parsed into different types.

1. `*`. If one of these are included, all tables are included.
2. `tablename.*`. If one of these is included, this table is included. Also, Meltano should check that this table name is in the discovered tables and throw an error if not.
3. `*tablename*` - i.e. the glob expression only specifies part of the table name. Any matching tables would be included.

For implementation, you could do a first pass to look for the full table names in point 2 above, and check that all of those are available. Then, proceed with the current filtering algorithm.

```
plugins:
  extractors:
  - name: tap-postgres
    variant: transferwise
    config:
      default_replication_method: FULL_TABLE
  - name: tap-hamilton
    inherit_from: tap-postgres
    load_schema: hamilton_raw_20220422
    select:
    - public-platform.*
    - public-organisation.*
    - public-team.*
    - public-platform_setting.*
    - public-organisation_setting.*
    - public-team_setting.*
    - public-subdomain.*
    - public-tag_definition.*
    - public-tag_value.*
```
