### ISSUE TITLE
meltano.yml removes blank strings when regenerated

### ISSUE THREAD

**Issue by rabidaudio** [meltano/meltano#6168]
I kept seeing this error message after running meltano commands:

```
__init__() missing 1 required positional argument: 'args'
```

Turns out the `args` it's referring to is a plugin command:

```yaml
    commands:
      test:
        args: ''
        executable: pytest
```

After running any command that updates `meltano.yml`, `args: ''` is removed from the config. Same with `args: []`.

Likely an issue of `None` check vs falsey check somewhere in pruning the configuration before saving.

As a workaround, I just set `args: -v` (probably a good choice anyway)
