### ISSUE TITLE
Using MELTANO_PROJECT_ROOT in config setting not expanding

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6175]
Theres a chance I'm using this wrong as I was previously just passing relative references which were working but it surprised me when this didnt work. If I point tap-csv to a file in my project `data/customer.csv` with a relative reference it works fine but with $MELTANO_PROJECT_ROOT it throws an error where its clear that variable wasnt expanded. Is this expected behavior? I see most references in the docs using `MELTANO_PROJECT_ROOT` in env var mappings, not in actual config settings so that could be it.

```yaml
version: 1
default_environment: dev
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-csv
        config:
          files:
          - entity: customers
            path: $MELTANO_PROJECT_ROOT/data/customers.csv
            keys:
            - id
```

Result `Exception: File path does not exist $MELTANO_PROJECT_ROOT/data/customers.csv`.
