### ISSUE TITLE
Disallow calling a `mapper` by name in `meltano run` and alert to use a `mapping` name

### ISSUE THREAD

**Issue by lidong-zhao** [meltano/meltano#6189]
The document misses a step for mapper configuration. Property `mapping_name` has to be added to the mappers extras, and its value need to match with the name under mappings. It doesn't seem been documented anywhere.

```yaml
plugins:
  mappers:
  - name: transform-field
    variant: transferwise
    pip_url: pipelinewise-transform-field
    executable: transform-field
    mapping_name: transform-field-hash
    mappings:
    - name: transform-field-hash
      config:
        transformations:
          - field_id: Name
            tap_stream_name: dbo-Test
            type: MASK-HIDDEN
```

**Comment by tayloramurphy** [comment]
@edgarrmondragon can you confirm this is accurate? In my demo project I didn't have to add `mapping_name` to the plugin definition. Using `meltano run <tap> transform-field-hash <target>` worked fine when I had a config like:

```
plugins:
mappers:
  - name: transform-field
    variant: transferwise
    pip_url: pipelinewise-transform-field
    mappings:
    - name: hash-url-data
      config:
        transformations:
        - field_id: html_url
          tap_stream_name: commits
          type: HASH
```

@lidong-zhao where are you finding this requirement?
