### ISSUE TITLE
Add `env` as first-class attribute of `MeltanoFile` and  `ProjectPlugin` classes (not an `extra`)

### ISSUE THREAD

**Issue by kgpayne** [meltano/meltano#6207]
**Note:** `env` is already a first-class attribute of the `Environment` class.
**Note:** Just adding these will not make inheritance work (as per #5982 and #5983).

Spec:

- `env` is a first-class attribute of `MeltanoFile` accessible via top-level `env:` key in `meltano.yml`)
- `env` is a first-class attribute of `ProjectPlugin` accessible via plugin-scoped `env:` keys in base and environment-specific config
- `env` is settable via the CLI, including with the '.' syntax (e.g. `meltano --no-environment config meltano set env.MY_ENV_VAR value`)
- New attributes are added to jsonschema, tested and documented

Release:

As both #5982 and #5983 depend on an `env` attribute, they should include these changes in their PR to master. This issue will be closed when either of those issues is merged to `main`.

**Comment by aaronsteers** [comment]
@kgpayne - We've closed #5969 in favor of this issue. Can you include the docs as part of this?

(Even writing docs first might not be a bad idea. 😉 )

**Comment by z3z1ma** [comment]
@kgpayne Is this the idea?

just putting some lame pseudo-code yaml to illustrate the question

```yaml
env:
  DATABASE: COOL_DB
  DB_PASS: ${FROM_SHELL_ENV_VAR}
  
plugin:
  transformer:
    config:
      database: ${DATABASE}
      password: ${DB_PASS}
  loader:
    config:
      target_db: ${DATABASE}
      postgres_pass: ${DB_PASS}
```
