### ISSUE TITLE
Can't use default_replication_method INCREMENTAL with tap-postgres

### ISSUE THREAD

**Issue by willjohnson** [meltano/meltano#6282]
With meltano 2.0.3, if I have default_replication_method set as INCREMENTAL with tap-postgres then I get an error.

`meltano config tap-postgres test`

```
2022-06-24T15:26:15.923809Z [info     ] Environment 'dev' is active

Plugin configuration is invalid

AttributeError: 'NoneType' object has no attribute 'get'
```

Changing default_replication_method to either FULL_TABLE or LOG_BASED gets past the error and returns "Plugin configuration is valid"

meltano.yml
```
version: 1
default_environment: dev
project_id: fc0cd1d8-5717-4675-9102-c660d25017d5
plugins:
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres
  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-postgres
        config:
          user: meltano_test_user
          dbname: meltano_test
          filter_schema: src_sample_store
          start_date: '2022-06-24T00:00:00Z'
          default_replication_method: INCREMENTAL 
          metadata:
            meltano_test-src_sample_store:
              replication-key: updated_at
              replication-method: INCREMENTAL
      loaders:
      - name: target-postgres
        config:
          user: meltano_test_user
          dbname: meltano_test_dw
          schema_mapping:
            src_sample_store: dest_sample_store
- name: staging
- name: prod
```
