### ISSUE TITLE
Jobs are not written back to `include_paths` file

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6312]
Steps to reproduce:

1. Add a job manually to an included path:

   ```yaml
   # jobs.meltano.yml
   jobs:
   - name: gh-to-jsonl
     tasks:
     - tap-github target-jsonl
   ```

1. Register the included path

   ```yaml
   # meltano.yml
   include_paths:
   - jobs.meltano.yml
   ```

1. Read operations work as expected:
 
   ```console
   $ meltano job list
   gh-to-jsonl: ['tap-github target-jsonl']
   ```

1. Update operations fail to write the update job back to the original file

   ```console
   $ meltano job set gh-to-jsonl --tasks 'tap-github--inherited target-jsonl'
   Updated job gh-to-jsonl: ['tap-github--inherited target-jsonl']
   ```

   ```yaml
   # meltano.yml
   include_paths:
   - jobs.meltano.yml
   jobs:
   - name: gh-to-jsonl
     tasks:
     - tap-github--inherited target-jsonl
   ```

   ```yaml
   # jobs.meltano.yml
   plugins: {}
   schedules: []
   ```
