### ISSUE TITLE
tap-mysql only INCREMENTAL, LOG_BASED, and FULL TABLE replication methods are supported

### ISSUE THREAD

**Issue by lialzm** [meltano/meltano#6361]
my config

```
version: 1
default_environment: dev
project_id: 11e34570-bed3-4835-961c-aa7a1a44a2aa
plugins:
  extractors:
  - name: tap-mysql
    variant: transferwise
    pip_url: pipelinewise-tap-mysql
  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-mysql
        config:
          host: 127.0.0.1
          database: test
          user: test
          filter_dbs: test
        select:
        - '*.*'
        metadata:
          test_user:
            replication-method: FULL_TABLE
      loaders:
      - name: target-postgres
        config:
          host: 127.0.0.1
          database: test
          user: test
          default_target_schema: public
- name: staging
- name: prod

```
