### ISSUE TITLE
feat: add support for `env` key for `schedules`

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6387]
Related to:

* https://github.com/meltano/meltano/issues/6386

```yaml
schedules:
- name: gitlab
  interval: '@daily'
  job: gitlab
  env:
    DBT_MODELS: +gitlab+
```

Precedence discussion in https://github.com/meltano/meltano/issues/6386#issuecomment-1179138398
