### ISSUE TITLE
Bug: several empty keys are added when the last top-level key is removed via the CLI

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6389]
IN https://github.com/meltano/meltano/pull/6308 I found that if you have an additional meltano.yml file like so:

```yaml
# schedules.meltano.yml
schedules:
- name: run_github_commits
  interval: '@daily'
  job: github_data
```

If you remove that schedule via the CLI that file will look like:

```yaml
# schedules.meltano.yml
plugins: {}
schedules: []
jobs: []
environments: []
```

This isn't ideal because the diff can be confusing. Functionally it's fine, but I'd expect either the final file to either be `schedules: []` or just blank.
