### ISSUE TITLE
feat: support container-based plugins

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6408]
### Problem to Solve

There is a whole world of plugins outside of the Python ecosystem that would benefit from having Meltano act as their foundation. Specific examples include:

* https://www.bytebase.com/ (written in Go)
* https://metriql.com/ (written in Kotlin)
* https://github.com/evidence-dev/evidence (written in Svelte)
* [DuckDB](https://github.com/duckdb/duckdb) (all sorts of languages going on)
* target-clickhouse: https://github.com/meltano/hub/issues/652

The current `container_spec` implementation is insufficient for some of the use cases of these plugins. There may be no pip_url and the user may likely never need or want to interact with the plugin outside of the containerized context. 

The goal of this is to unlock a larger world of possible plugins for Meltano

### Prior Art / Things to Consider

* We only currently support docker https://github.com/meltano/meltano/issues/3246
* https://github.com/meltano/meltano/issues/3181 should be considered as there are taps and targets that are written in other languages 
* https://github.com/meltano/meltano/issues/3300 is a previous issue written by Pat while he was attempting to use Superset w/ Meltano 
* https://github.com/meltano/meltano/issues/3127 will likely need to be considered as part of this
* https://github.com/meltano/meltano/issues/3246 Other container runtimes
* https://github.com/meltano/meltano/issues/3389 what we send into the container environment

### Definition of Done

* Any dockerized tool should be able to be used within Meltano as a utility
  * Bytebase and Lightdash should be used as a test bed for validating. 
* YAML spec is updated to support containerized plugins
* Consideration for other multiple container specs - docker can be used as primary for this
* Documentation updated in Meltano and the Hub to make it clear how to use these plugins

**Comment by aaronsteers** [comment]
> The current `container_spec` implementation is insufficient for some of the use cases of these plugins. There may be no pip_url and the user may likely never need or want to interact with the plugin outside of the containerized context.

@tayloramurphy and @DouweM - I'm not clear what the deficiency is, or if there is any deficiency at all. Non-Python plugins are already _fully_ supported - as evidenced by the evidence.dev integration I built here: https://github.com/aaronsteers/aj-dataops-personal/blob/main/meltano.yml#L193-L246

Are we sure there are limitations or do we just need more 'in the wild' examples of container-based plugins to be added to the hub. If the former and we do have limitations, we should document those as issues to address.

1. This should be closed (I think) as I believe it's already resolved with the current featureset: https://github.com/meltano/meltano/issues/3300
1. This is doable, for sure, but probably should not be prioritized, since won't impact the drive for non-EL plugins: https://github.com/meltano/meltano/issues/3181
1. Non-docker runtimes is worth adding (https://github.com/meltano/meltano/issues/3246), but doesn't change anything from an overall functionality/vision perspective. When we're all feeling confortable that the current implementation is functionally complete, then I think we can certainly pick up the "other container runtimes" spec - which would bring the parity features to Ranger Desktop, containerd, etc. but would not otherwise change underlying behaviors.

**Comment by pnadolny13** [comment]
Another one to add to the list is https://github.com/meltano/meltano/issues/3389 I had feedback on the difficulties I had with environment variables when using container spec. It looks like we agreed it was a bug (?) to be fixed but wasnt prioritized for 2.0.

**Comment by tayloramurphy** [comment]
@aaronsteers I would disagree that non-python plugins are fully supported. The Evidence example you linked is very helpful in helping guide and frame this conversation.

Looking at your example, I think it'd make sense to at a minimum pull `container_spec` to the plugin level and out of commands. This could be a replacement for `pip_url` for non-python plugins and allow for optional overrides at the command level. 

```yaml
  - name: evidence
    namespace: evidence
    container_spec:
      image: evidencedev/devenv:latest
      command: bash
      volumes:
      - $MELTANO_PROJECT_ROOT/analyze/evidence/:/evidence-workspace/
```

This also then simplifies each command to the point where have just `container_spec.command` is extraneous so we might as well support `args` for containerized plugins. So you'd have something like 

```yaml
  - name: evidence
    namespace: evidence
    container_spec:
      image: evidencedev/devenv:latest
      command: bash
      volumes:
      - $MELTANO_PROJECT_ROOT/analyze/evidence/:/evidence-workspace/
    commands:
      pull_image:
        # https://github.com/evidence-dev/docker-devenv
        args: pull evidencedev/devenv:latest
        executable: docker
      help:
        args: --help
      init:
        args: init
      dev:
        args: ""
        container_spec:
          ports:
            '3000': '3000'
      install:
        args: npm install
      build:
        # Not working yet
        args: npm run build
```

In theory, users could have `settings` and `config` defined for their non-python plugin (thinking for things like [Lightdash settings](https://docs.lightdash.com/get-started/setup-lightdash/install-lightdash/#using-docker-compose)). It's not clear what's happening with settings/config in the current implementation. Similarly, I think the point stands that "user may likely never need or want to interact with the plugin outside of the containerized context." and so commands may seem like overkill for the simple use case running a containerized plugin through Meltano. 

I realize there's likely several features I've proposed in there, but going from the docs as a user, I don't think https://docs.meltano.com/concepts/plugins#project-plugins indicates at all that container-based plugins are supported.
