### ISSUE TITLE
feature: support glob patterns for paths in file bundle plugin `update` extra

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#6585]
### Feature scope

CLI (options, error messages, logging, etc.)

### Overview
File bundle plugins can specify a number of files to update with the `update` extra, when `meltano upgrade files` is run.

`meltano.yml`
```yml
version: 1
default_environment: dev
environments:
- name: dev
- name: staging
- name: prod
project_id: fefc3baf-ebb0-4f68-87d1-fe5b3afbe6e8
plugins:
  files:
  - name: files-dbt
    pip_url: git+https://github.com/meltano/files-dbt
    update:
      transform/models/.gitkeep: true
      transform/profile/profiles.yml: true
      transform/.gitignore: true
      transform/dbt_project.yml: true
```

Currently, each file than can be updated by `meltano upgrade files` must have its path declared under `update` individually. This can lead to bloated `meltano.yml` file bundle definitions that specify many files within common directories as upgradable.

### Proposal
Support glob patterns to reduce the number of paths needed to specify all files required for upgrade.

All bundle files:
```yml
    update:
      '**/*': true
```

All bundle `.yml` files:
```yml
    update:
      '**/*.yml': true
```

All bundle `.yml` files under the `transform` directory:
```yml
    update:
      'transform/**/*.yml': true
```
