### ISSUE TITLE
feature: support linking venv or allowing plugins to install package into multiple venvs

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6600]
### Feature scope

Other

### Description

With the new extension/sdk pattern - where an extension gets installed as a utility alongside something that it's wrapping or managing (e.g. superset, airflow, dbt), it would be nice if plugins could install components into discrete venv's or if they could reference or resolve a path to another plugin's venv. 

Having both an extension/wrapper and the thing it's wrapping in the same venv can be challenging. Airflow for example gets installed with a very specific constraints file - which of course means that the airflow wrapper (and the extension sdk) - also has to operate within those constraints.

There are probably a few ways to approach this, but two quick naive ideas:

1. If one plugin requires another, we could inject python venv info into the env at run time - so that the called plugin (airflow_extension), can find the venv/python/bin of the other plugin it depends on (airflow).
2. Support two venv's for plugins, a default venv where the plugin gets and stalled, and a secondary optional venv for deps e.g.
```yaml
  utilities:
  - name: superset
    namespace: superset
    pip_url: ext-superset==0.0.1 #installed as usual
    deps_pip_url: apache-superset==2.0.0 flask=2.1.3 #installed into a secondary venv
    executable: airflow_extension
```
