### ISSUE TITLE
feature: Change logging settings per Meltano environment

### ISSUE THREAD

**Issue by JulesHuisman** [meltano/meltano#6685]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

It would be great to change the logging settings depending on the Meltano environment you are in. For example, in the dev and ci environment we want full coloured logging, while in prod we want simple, non-coloured logging. 

This is currently a bit of a hassle to setup using the `logging.yaml`, and would be great if it was implemented inside the `meltano.yml` file. 

As a first brain dump:
```yaml
logging:
  formatter: structured
  log_level: info
  colors: true
...
environments:
- name: dev
  logging:
    formatter: structured
    log_level: info
    colors: true
  ...
- name: ci
  logging:
    formatter: structured
    log_level: debug
    colors: true
  ...
- name: prod
  logging:
    formatter: json
    log_level: info
    colors: false
  ...
```
