### ISSUE TITLE
feature: handle object type settings with a dedicated submenu in config `list` and `set --interactive`

### ISSUE THREAD

**Issue by kgpayne** [meltano/meltano#6720]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Currently object type settings are handled in the default way the `PluginSettingsService` understands those settings; in their flattened form. E.g. 

```yaml
- name: target-redshift
   variant: transferwise
   pip_url: pipelinewise-target-redshift
   config:
     schema_mapping:  # setting of type object
        what: what what
```

```shell
$ meltano config tap-redshift set --interactive
...
│ 21. schema_mapping: Useful if you want to load multiple streams from one tap to multiple Red...                                                 
│ ...
│ 31. temp_dir: (Default: platform-dependent) Directory of temporary CSV files with RECO...                                                                  │
│ 32. schema_mapping.what:
...
```

Rather than flattening, we could:
- Exclude flattened keys from the settings list
- Construct a sub-experience for interactively configuring objects, allowing users to:
  - set as JSON string
  - add/remove keys
  - set individual key values
  
The latter two experiences essentially construct or edit an underlying JSON/dict representation of the object-type setting value.
