### ISSUE TITLE
bug: A single Environment definition can not be split into multiple YAML files

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6727]
### Meltano Version

2.5.0

### Python Version

NA

### Bug scope

API

### Operating System

Any

### Description

When a Environment (e.g. `prod`) is defined in multiple project files, Meltano fails with the following error message:

```
Plugin with path "environments:prod" already added in file /run/media/atif.imam/data/pycharm_projects/data-integration/source_config/file_1.yml.
```

This is because the multi-file implementation indexes environment by name alone. This means an entire environment definition MUST be contained in a single YAML file and it makes use cases where it's desirable to split plugin configuration in one file per plugin with a common set of environments impossible to accomplish.

From a Slack thread: https://meltano.slack.com/archives/C01TCRBBJD7/p1662443196912219

### Code

```python
<details><summary>YAML files</summary>


# meltano.yml
environments:
- name: dev
- name: uat
- name: prod
send_anonymous_usage_stats: true
project_id: 488164fd-cb5b-4fe1
include_paths:
  - ./source_config/file_1.yml
  - ./source_config/file_2.yml

plugins:
  extractors:
    - name: tap-mysql
      variant: transferwise
      pip_url: pipelinewise-tap-mysql
      config:
        ..
        ..
  loaders:
    - name: target-snowflake
      variant: transferwise
      pip_url: pipelinewise-target-snowflake
      config:
        add_metadata_columns: true
        hard_delete: true
        ..
        ..


```yaml
# file_1.yml
environments:
  - name: prod
    config:
      plugins:
        extractors:
          - name: tap-mysql-db1
              
        loaders:
          - name: target-snowflake-db1
            config:
              s3_key_prefix: snowflake/db1/
  - name: uat
    config:
      plugins:
        extractors:
          - name: tap-mysql-db1
              
        loaders:
          - name: target-snowflake-db1
            config:

plugins:
  extractors:
    - name: tap-mysql-db1
      inherit_from: tap-mysql
  loaders:
    - name: target-snowflake-db1
      inherit_from: target-snowflake
      config:
        default_target_schema: db1
```

```yaml
# file_2.yml
environments:
    - name: prod
      config:
        plugins:
          extractors:
            - name: tap-mysql-db2
                
          loaders:
            - name: target-snowflake-db2
              config:
                s3_key_prefix: snowflake/db2/
    - name: uat
      config:
        plugins:
          extractors:
            - name: tap-mysql-db2
                
          loaders:
            - name: target-snowflake-db2
              config:
  
  plugins:
    extractors:
      - name: tap-mysql-db2
        inherit_from: tap-mysql
    loaders:
      - name: target-snowflake-db2
        inherit_from: target-snowflake
        config:
          default_target_schema: db2
```

</details>
```

**Comment by aaronsteers** [comment]
@edgarrmondragon - Thanks for logging. I can see potential confusion arising from having definitions for a single environment split across files.

Anyone looking at single of those files would not know they are looking at a partial entry.

Also, it might be helpful to have a bit more info on the use case here. Ideally, there should not be a lot of environment-specific overrides and in most cases those should always neatly fit into a single concise file, one per environment.

I'll point out that for brevity and readability, multiple plugins can be configured with a few `env: {}` blocks where those settings align. For instance in the example above, the setting config for `s3_key_prefix` could be rewritten at the top level as `snowflake/$DB_ID/` and similarly `default_target_schema` could be configured in its global definition as `$DB_ID`. Then, the plugins do not need to be enumerated in the environment declaration at all, but instead the environment block could be:

`environments.yml`

```yml
environments:
    - name: prod
      env:
        DB_ID: db1
    - name: uat
      env:
        DB_ID: db2
```

Or as two files:

`environments/prod.yml`

```yml
environments:
    - name: prod
      env:
        DB_ID: db1
```

`environments/uat.yml`

```yml
environments:
    - name: uat
      env:
        DB_ID: db2
```

**Comment by edgarrmondragon** [comment]
@aaronsteers I too I'm wary of allowing environments to be spread across multiple files. Still logged in case anybody searches the issues for `Plugin with path ... already added`. I recommended your one-file-per-environment approach to the user 👍.

**Comment by msardana94** [comment]
Thanks @edgarrmondragon for logging this issue.

@aaronsteers I see your point and agree with your reasoning. I have a use case where environment variables didn't work. Here's a sample prod config

```yaml
plugins:
  extractors:
    - name: tap-mysql-db1
      inherit_from: tap-mysql
      select:
        - db1_live-table1.*
        - db1_live-table2.*
        - db1_live-table2.*
      metadata:
        "*":
          replication-method: LOG_BASED
  loaders:
    - name: target-snowflake-db1
      inherit_from: target-snowflake
      config:
        default_target_schema: db1
        s3_key_prefix: snowflake/db1/
```
For non-prod (uat) environment, the schema/db name is different (db1_uat). So the uat config will look something like this:

```yaml
plugins:
  extractors:
    - name: tap-mysql-db1
      inherit_from: tap-mysql
      select:
        - db1_uat-table1.*
        - db1_uat-table2.*
        - db1_uat-table2.*
      metadata:
        "*":
          replication-method: LOG_BASED
  loaders:
    - name: target-snowflake-db1
      inherit_from: target-snowflake
      config:
        default_target_schema: db1
        s3_key_prefix: snowflake/db1/
```

Now, when we try to use `$DB_ID` as you mentioned in `select` config, it doesn't resolve the value. Is there something I am missing?

Also, we maintain separate files for each mysql data source to make it easier for our analysts to modify these config files as needed (in most cases it is to bring a new table). Having a single file will make contribution slightly difficult due to readability challenges.
