### ISSUE TITLE
feat: enforce consistent default structure of meltano.yml

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6734]
Somewhere in our versions we changed the default appearance of `meltano.yml`

I tested in v2.1 and this was my meltano.yml after init:

```yaml
version: 1
default_environment: dev
project_id: f58355da-fd1a-4ecf-920d-38cdc5267f0b
environments:
- name: dev
- name: staging
- name: prod
```

and in version 2.4 after init:

```yaml
version: 1
default_environment: dev
environments:
- name: dev
- name: staging
- name: prod
project_id: e3ebcf06-644d-475e-be4f-a3c5e0ba9a9e
```

My ideal order would be:

```yaml
version: 1
project_id: e3ebcf06-644d-475e-be4f-a3c5e0ba9a9e
default_environment: dev
environments:
- name: dev
- name: staging
- name: prod
```
