### ISSUE TITLE
feature: add support for env var interpolation in `select` blocks

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6770]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

Per discussion here:

- https://github.com/meltano/meltano/issues/6727#issuecomment-1251272375

In cases where the `select` clause has to name a specific database or schema, and if that database or schema name differs across environments, it would make a plugin definition more DRY if we could support dynamic `select` clauses based on env variables.

## Example case:

```yaml
environments:
  - name: prod
    env:
     SOURCE_DB_ID: db1_live
  - name: uat
    env:
     SOURCE_DB_ID: db1_uat
plugins:
  extractors:
    - name: tap-mysql-db1
      inherit_from: tap-mysql
      select:
        - ${SOURCE_DB_ID}-table1.*
        - ${SOURCE_DB_ID}-table2.*
        - ${SOURCE_DB_ID}-table3.*
      metadata:
        "*":
          replication-method: LOG_BASED
```

### Cached `catalog.json` would not be compatible across environments

A challenge with this approach is that as of now, Meltano doesn't track separate environment-specific catalog files, and with the stream name having the db hardcoded as in the above example, a catalog from one environment simply would not work on any other environment. 

#### Workaround

A workaround for this challenge would be to first deliver one or more of:

- #2856 
- #2848 

Then, the user would be informed that in order to use a dynamic catalog, we recommend disabling caching (preferred) - or else remembering to explicitly delete the cache before/after each switch between environment (much less ideal because it's prone to manual error/omission).

## Related:

- https://github.com/meltano/meltano/discussions/6757
- #2856 
- #2848 
- https://github.com/meltano/meltano/issues/6727

**Comment by sbalnojan** [comment]
Why do we want to limit this to select blocks, is there a technical reason? Seems like this is useful everywhere:  

Carrying this over from Slack, Robert was looking for this, his use case:

```
plugins:
  loaders:
    - name: ga-target-s3-jsonl
      inherit_from: target-s3-jsonl
      env:
        PREFIX: the_prefix_here
      config:
        naming_convention: meltano/${PREFIX}/{stream}/export_date={date:%Y-%m-%d}/{timestamp}-{stream}.json
```


My personal use case for this would be 

```
plugins:
  utilities:
    - ... # JUPYTER PLUGIN
      run_this_model: 
              command: jupyter nbconvert ${NOTEBOOK_TO_RUN}
```

instead of writing multiple commands I thus can simply export a variable & then call my generic "run that model" command.
