### ISSUE TITLE
feature: Support <PLUGIN_NAME>_<SETTING_NAME> convention for Mapper plugins

### ISSUE THREAD

**Issue by cwe5590** [meltano/meltano#6811]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

Mapper plugins should be able to have there settings set via the standard <PLUGIN_NAME>_<SETTING_NAME> convention.

```
  mappers:
  - name: meltano-map-transformer
    variant: meltano
    pip_url: git+https://github.com/MeltanoLabs/meltano-map-transform.git
```

For example, I should be able to set the mappings setting for the above mapper using the following env variables. The current behaviour returns this error `Error: Block filter-properties not found`.

`export MELTANO_MAP_TRANSFORMER_MAPPINGS='[{"name": "filter-properties", "config": {"stream_maps": {"public-cdc_test": {"id": "id", "__else__": null}}}}]'`

**Comment by cwe5590** [comment]
re: https://meltano.slack.com/archives/C01TCRBBJD7/p1664322242831029

**Comment by pnadolny13** [comment]
This came up again in slack today https://meltano.slack.com/archives/C013EKWA2Q1/p1681775564908829

**Comment by pnadolny13** [comment]
Still relevant I actually ran into this again today.

**Comment by edgarrmondragon** [comment]
Bad stalebot

**Comment by ReubenFrankel** [comment]
Ran into this today 😅

**Comment by ReubenFrankel** [comment]
FWIW, I found https://github.com/MeltanoLabs/meltano-map-transform/issues/195 and was able to get it working with `MELTANO_MAP_TRANSFORMER_STREAM_MAPS` and a stub mapping so that I could use it with `meltano run` (mapper name not allowed - see https://github.com/meltano/meltano/pull/9105):

```yml
  mappers:
  - name: meltano-map-transformer
    variant: meltano
    pip_url: meltano-map-transform
    mappings:
    - name: mapping-from-env  # stub mapping to allow env configuration of the mapper and usage in `meltano run`
```

```console
$ export MELTANO_MAP_TRANSFORMER_STREAM_MAPS='{"my_stream": {"__alias__": "my_aliased_stream"}}'
$ meltano run <tap> mapping-from-env <target>
```
