### ISSUE TITLE
feat: support ephemeral plugin commands in jobs

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6816]
Inspired by:

* https://github.com/meltano/meltano/issues/6810

It would be very interesting to support what are essentially "ephemeral" plugin commands. This would enable a user to use command line arguments in the job w/o having to define them in the plugin first:

```yaml
- name: my_custom_job
  tasks:
  - tap-foo target-bar
  - dbt-bigquery invoke:run --select foo+
```

this is one possible solution for this problem though
