### ISSUE TITLE
feature: Support to run jobs with --full-refresh option from airflow

### ISSUE THREAD

**Issue by t-broka** [meltano/meltano#6845]
### Feature scope

Web UI

### Description

Currently, I can add a job with tasks e.g `meltano job add <job_name> --tasks "<tap_name> <target_name>"`. But when I want to run a job with `full-refresh` option, I get an error `The job has invalid task`. Adding the support of `full-refresh` will help us to schedule the job from airflow. 
In production environments, we don't have access into the container (meltano deployed in kubernetes) to run CLI. Hence, it's difficult to run a job with full-refresh option.

**Comment by t-broka** [comment]
re: https://meltano.slack.com/archives/C01TCRBBJD7/p1664898601202939

**Comment by aaronsteers** [comment]
Thanks, @t-broka, for raising.

I think the only hard problem here is determining our CLI convention and yaml convention.

For CLI, one option would be adapt the same args as `meltano run` and then apply those args to all steps in the job. 

For yaml, we have a few options. Because we want to leave space for other options as well, my examples below will specify both `--full-refresh` and `--state-id-suffix`.

```yml
# Option A: We translate flags into yaml job properties applied globally
jobs:
- name: weekly-full-refresh
  full_refresh: true
  state_id_suffix: weekly-full
  tasks:
  - tap-gitlab hide-gitlab-secrets target-postgres
  - dbt-postgres:run
  - custom-utility-plugin
```

```yml
# Option B: We pass arbitrary CLI flags/options to all job tasks
jobs:
- name: weekly-full-refresh
  options:
  - '--full-refresh'
  - '--state-id-suffix=weekly-full'
  tasks:
  - tap-gitlab hide-gitlab-secrets target-postgres
  - dbt-postgres:run
  - custom-utility-plugin
```

```yml
# Option C: We translate CLI args into task-level yaml properties
jobs:
- name: weekly-full-refresh
  tasks:
  - run: tap-gitlab hide-gitlab-secrets target-postgres
    full_refresh: true
    state_id_suffix: weekly-full
  - dbt-postgres:run
  - custom-utility-plugin
```

```yml
# Option D: Stringify CLI args into task-level yaml properties
# This requires parsing later on by Meltano and/or the orchestrator implementation
jobs:
- name: weekly-full-refresh
  tasks:
  - "--full_refresh --state_id_suffix=weekly-full tap-gitlab hide-gitlab-secrets target-postgres"
  - dbt-postgres:run
  - custom-utility-plugin
```

**Comment by tayloramurphy** [comment]
@aaronsteers I'm not a fan of A and B as the flags feel quite disconnected from the tasks. It's not clear if each flag applies to all tasks or not.

My intuition says we should support _both_ C & D. Fully quoting the task item feels natural, but the command prefix (`run: `) seems like it could be _really_ powerful.

**Comment by aaronsteers** [comment]
@tayloramurphy - Yeah, I think the "C" option would make a lot of sense. Basically "assume each line is a string to be passed to `run` unless it's prefixed by another command`.

This has the nice benefit of being neatly copy-pasteable.

```console
# Before the feature
meltano run tap-github target-snowflake
meltano invoke dbt:run --select=foo+  # This doesn't work as a job task
meltano run dbt:test

# After the feature
meltano job create my_new_job --tasks "[tap-github target-snowflake, invoke: dbt:run --select=foo+, dbt:test]
meltano run my_new_job
```

Which creates this yaml:

```yaml
  tasks:
  - tap-github target-snowflake
  - invoke: dbt:run --select=foo+
  - dbt:test
```

Which would be equivalent to:

```yaml
  tasks:
  - run: tap-github target-snowflake
  - invoke: dbt:run --select=foo+
  - run: dbt:test
```

**Comment by tayloramurphy** [comment]
@aaronsteers yep - I quite like that

**Comment by WillDaSilva** [comment]
Still relevant

**Comment by marcossantiago** [comment]
For those with the same issue, as a workaround, I created a custom command in the dbt transform that clears the pipeline state before the sync runs. 

You can list the states with `$ meltano state list`. 

meltano.yaml
```yaml
plugins:
  transformers:
  - name: dbt-redshift
    variant: dbt-labs
    commands:
      clear_state:
        executable: /bin/bash
        args: -c '../scripts/clear_state.sh'

jobs:        
  - name: myjob
    tasks:
    - dbt-redshift:clear_state
    - tap-mysql target-redshift
```


clear_state.sh
```bash
#!/bin/bash
meltano state clear --force --force prod:tap-mysql-to-target-redshift

echo "myjob state cleared!"
```
