### ISSUE TITLE
feature: Set database_uri for different Meltano Environments

### ISSUE THREAD

**Issue by qbatten** [meltano/meltano#6846]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

I would like to be able to set a different Meltano system database_uri ([this setting](https://docs.meltano.com/reference/settings#database_uri)) under an `env` block in meltano.yml. Currently, the only way to change this setting across environments is to change the MELTANO_DATABASE_URI environment variable (&/or .env file variable).

This is not currently possible.

It would look something like this:

```
environments:
- name: dev
  config:
    database_uri: postgresql://test:test@test.com:5432/postgres
    plugins:
      loaders: ...
```

Keeping the system db separate in different environments is helpful for us (I like to limit shared resources between environments bc sharing them makes accidentally overwriting from one environment to the other more likely). Allowing that setting to be included in meltano.yml makes it more visible and transparent to all users, and reduces the amount of manual differentiating that needs to be done in other places.

There is a discussion of this in Slack here: https://meltano.slack.com/archives/C01TCRBBJD7/p1664314402975189
