### ISSUE TITLE
feat: args should be optional for plugin commands

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6884]
I think 'args' is _normally_ needed, so we made it required for `commands`. But there are valid use cases where it can be omitted, and I think we should probably remove this requirement.

For instance, my `evidence` plugin definition declares everything as containerized commands, and the top-level 'args' input is not applicable in that setting.

```yml
plugins:
  utilities:
  - name: evidence
    namespace: evidence
    commands:
      build_image:
        # identical to running `docker build -t=evidence .` from the evidence project dir
        args: build -t=evidence /Users/aj/Source/evidence
        executable: docker
      pull_image:
        # identical to running `docker pull evidence`
        args: pull evidence
        executable: docker
      init:
        args: 
        container_spec:
          image: evidence
          command: init
          volumes:
          - $MELTANO_PROJECT_ROOT/analyze/evidence/:/evidence/project/
      dev:
        container_spec:
          image: evidence
          command: dev
          ports:
            '3000': '3000'
          volumes:
          - $MELTANO_PROJECT_ROOT/analyze/evidence/:/evidence/project/
      build:
        # Not working yet
        container_spec:
          image: evidence
          command: build
```
