### ISSUE TITLE
refactor: Consider making `no_color` a project-level setting

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6940]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

and documenting it in https://docs.meltano.com/reference/settings.

One potential caveat is that project settings can be set in places other that the environment, like `meltano.yml` and `.env`.

This would make it hard to configure things like the console log formatter like

```yaml
# https://docs.meltano.com/guide/logging
version: 1
disable_existing_loggers: false

formatters:
  structured_plain: # log format for structured plain text logs without colored output
    (): meltano.core.logging.console_log_formatter
    colors: False # also disables `rich` traceback formatting
  structured_colored: # log format for structured plain text logs WITH colored output
    (): meltano.core.logging.console_log_formatter
    colors: True # also enables traceback formatting with `rich`
```

which is (and should prob remain!) unaware of the Meltano project and just look for `NO_COLOR` directly in the global environment.

_From conversation with @tayloramurphy._
