### ISSUE TITLE
feature: inherit config settings from other plugins

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6979]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

 ```yml
- name: tap-postgres-testing
   config:
     sqlalchemy_url: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${DBNAME}
```

I'd like to be able to override DBNAME for CI use cases. The issue is that I also need POSTGRES_USER / POSTGRES_PASSWORD today I need to duplicate what these are set to in `target_postgres` but if I could reference the postgres_user like above from another extractor / loader I wouldn't have to!

It's almost like I want to query the meltano.yml manifest. Like ```variable:${meltano.extractors.tap-postgres.user}/${meltano.extractors.tap-postgres.password}```

**Comment by aaronsteers** [comment]
@visch - We've been making progress on improving coverage and usefulness of `env: {}` capabilities, and this would be the first recommendation for workaround.

With your example above, the workaround with today's features would be to declare anything you'd want to share across plugins as a environment variable - and to combine this approach with the 'strict mode' flag so that an undeclared environment variable would fail rather than evaluate to an empty string.

Would something like this work?

```
ff.strict_env_var_mode: true  # Fail if any referenced env vars are undeclared

plugins:
- name: tap-postgres
  config:
    sqlalchemy_url: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${DBNAME}
  # ...
- name: dbt-postgres
  config:
    db_name: ${DBNAME}
  # ...

environments:
- name: cicd
  env:
    DBNAME: $CI_DB_NAME
- name: prod
  env:
    DBNAME: prod
```

To your direct proposal of being able to reference the manifest, I think that's a very interesting positioning. We didn't have the manifest concept when we first drafted this, but we did log a similar issue for jinja-like expression lanugage here:

- #3040
