### ISSUE TITLE
bug: Env var expansion misses lower level when no environment is active

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7023]
### Meltano Version

2.10.0

### Python Version

NA

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

N/A

### Description

Using the following `meltano.yml`:

```yaml
version: 1
project_id: faa14098-8fdc-4336-850e-96db154b7990
send_anonymous_usage_stats: false
env:
  STACKED: ${STACKED}2
plugins:
  utilities:
  - name: echo
    namespace: echo
    executable: echo
    env:
      STACKED: ${STACKED}4
environments:
- name: prod
  config:
    plugins:
      utilities:
      - name: echo
        env:
          STACKED: ${STACKED}5
  env:
    STACKED: ${STACKED}3
```

`STACKED=1 meltano invoke --print-var STACKED echo` -> `STACKED=4`

`STACKED=1 meltano --environment=prod invoke --print-var STACKED echo` -> `STACKED=12345`

In the first case we expect that no environment will be active, and so the value of `STACKED` will be `124`. Instead it appears the plugin env is being expanded without `os.environ` or the project-level env vars being supplied to expand `STACKED`, so it results in `4` at that level, then overwrites the project-level value.

It probably assumes that the environment-level env (level 3) will have `STACKED` defined with the value from the project-level (level 2), but in this case it is empty.

Related:
- https://github.com/meltano/meltano/issues/6253
