### ISSUE TITLE
docs: improve documentation on how container_spec x commands works behind the scenes

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#7028]
I was playing around with containerized commands (see https://github.com/meltano/hub/pull/1044) and found our docs to be a bit lacking, particularly if you're trying to "translate" between instructions you might see on DockerHub vs what's needed for a meltano plugin definition. 

https://docs.meltano.com/reference/plugin-definition-syntax#commandscommand_namecontainer_spec is the most complete definition of what a containerized command is. 

https://docs.meltano.com/reference/command-line-interface#containerized-commands mentions you need to use --containers

and https://docs.meltano.com/concepts/project#containerized-commands just links to the above two. 

... and that's all I could find. 

Documentation that says something like:

"Containerized plugins use `docker <command>` behind the scenes and pass along the metadata in x,y,z fashion. This is similar to docker compose etc etc.

For example, the following meltano plugin definition:

```yaml
commands:
  start:
    args: start
    container_spec:
      env:
        LANG: en_US.utf8
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/15/bin
        POSTGRES_DB: warehouse
        POSTGRES_PASSWORD: warehouse
        POSTGRES_USER: warehouse
      image: postgres:15
      ports:
        "5432": "5432/tcp"
      volumes:
      - "$MELTANO_PROJECT_ROOT/.meltano/utilities/postgres/data/:/var/lib/postgresql/data"
```

Is equivalent to the following docker command:

`docker run something somethnig`.

MongoDB has something like that for docker-compose https://hub.docker.com/_/mongo 

```
$ docker run --name some-mongo -d mongo --serviceExecutor adaptive

And here is the same with a docker-compose.yml file

version: '3.1'
services:
  mongo:
    image: mongo
    command: --serviceExecutor adaptive
```
