### ISSUE TITLE
bug: meltano.yml updates overwrite user-changed indentation

### ISSUE THREAD

**Issue by menzenski** [meltano/meltano#7054]
### Meltano Version

2.10.0

### Python Version

3.9

### Bug scope

Other

### Operating System

Mac OS 12.6 Monterey

### Description

Steps to replicate:

1. Run `meltano init test`
2. `cat test/meltano.yml` output:
```yaml
cat test/meltano.yml
version: 1
default_environment: dev
project_id: b02272c0-d17d-4512-ab23-47ed7c9133ad
environments:
- name: dev
- name: staging
- name: prod
```
3. Format YAML indentation differently:
```yaml
version: 1
default_environment: dev
project_id: b02272c0-d17d-4512-ab23-47ed7c9133ad
environments:
  - name: dev
  - name: staging
  - name: prod
```
4. Run a `meltano` CLI command that updates `meltano.yml` file. In my case I ran `meltano add loader target-jsonl`. 
5. Notice the leading indentation of the `environments` array members in `meltano.yml` has reverted from two spaces to zero:
```yaml
version: 1
default_environment: dev
project_id: b02272c0-d17d-4512-ab23-47ed7c9133ad
environments:
- name: dev
- name: staging
- name: prod
plugins:
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
```

### Code

```python
n/a
```
