### ISSUE TITLE
bug: nested configs are cleared when using space as delimiter and when using `--interactive`

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7132]
### Update (@aaronsteers)

Per the issue thread below, we've identified that the issue is present in the behavior of the CLI syntax with space as delimiter but not when dot is used. The proposal is to make these two function identically:

```bash
meltano config testy-mctest set file_configs.format json       # the expected behavior (does not reset sibling config)
meltano config testy-mctest set file_configs format json       # bug: clears sibling nested config
```

---------

### Original Issue description (@pnadolny13)

When using `--interactive` to update nested settings it overwrites the entry config set. For example:

```yaml
  - name: tap-file
    config:
      file_configs:
        dataset_name: test_file
        format: csv
        path: /my/path/
```

Then I run `meltano config tap-file set --interactive`, navigating to the setting `file_configs.format` (in dot notation) as defined in the plugin definition lock file, updating to `json`, meltano overwrites the whole nested config with only the new value:

```yaml
  - name: tap-file
    config:
      file_configs:
        format: json
```

Slack thread with video showing bug https://meltano.slack.com/archives/C03GKHWS0HM/p1671746236351709

meltano, version 2.12.0

**Comment by edgarrmondragon** [comment]
<details>
<summary>meltano.yml</summary>

```yaml
version: 1
default_environment: dev
project_id: c80de8e4-2d61-4115-a24b-b44460a8d35b
environments:
- name: dev
- name: staging
- name: prod
plugins:
  utilities:
  - name: testy-mctest
    namespace: test
    settings:
    - name: file_configs.dataset_name
    - name: file_configs.format
    - name: file_configs.path
    config:
      file_configs:
        format: json
```

</details>

This correctly changes only the wanted setting:

```console
$ meltano config testy-mctest set file_configs.format json
```

though it sets it as `file_configs.format: json` (which is correct, though perhaps unexpected)

While this results in removing the other settings, just like interactive:

```console
$ meltano config testy-mctest set file_configs format json
```
