### ISSUE TITLE
feature: Support env_var expansion in stream_maps config

### ISSUE THREAD

**Issue by qbatten** [meltano/meltano#7151]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

I would like to be able to use an environment variable in a stream_map config. E.g. I set `MAPPER_HASH_SALT=abcdef` in .env or in my terminal environment, and I can then do the following in my meltano.yml file, and have that value expand correctly to abcdef within the config. This should produce a hashed email column that has abcdef as a salt, and a hash_salt_printout column that contains the value "abcdef" (you'd never do that second part in prod, of course, just giving a silly example that I used in a staging environment to check whether the var was expanding correctly).

```
  mappers:
  - name: meltano-map-transformer
    pip_url: "git+https://github.com/MeltanoLabs/meltano-map-transform.git"
    executable: meltano-map-transform
    mappings:
    - name: redact_email__email
      config:
        stream_maps:
          redact_email__email: &redact_email__email
            email_name_hash: md5(config['hash_salt'] + email_address)
            hash_salt_printout: config['hash_salt']
          public-example_table: *redact_email__email
        stream_map_config:
          hash_salt: $MAPPER_HASH_SALT
```
