### ISSUE TITLE
feature: Plugin `executable` should accept an array or implicitly split the string value

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#7157]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

Similar Docker's `CMD` and `ENTRYPOINT`. This would allow the main plugin command to be more complex without requiring developers to create custom shell scripts just to encapsulate a multi-part command.

## Example

As a user I want to create a custom plugin for testing purposes that just `cat`s the output from a Singer JSON Lines file:

```yaml
plugins:
  extractors:
  - name: test
    namespace: test
    executable: cat singer.jsonl
```

`cat singer.jsonl` is interpreted as a single command:

```
Executable 'cat singer.jsonl' could not be found...
```

## Alternatives explored

One alternative is to use `commands`

```yaml
plugins:
  extractors:
  - name: test
    namespace: test
    commands:
      run:
        executable: cat
        args: singer.jsonl
```

which work with `meltano invoke`, but at least for extractors they don't play well with `meltano run`:

```
$ meltano@stable run test:run target-jsonl
2023-01-06T19:09:26.900323Z [info     ] Environment 'dev' is active
2023-01-06T19:09:38.142174Z [info     ] test: --config: unexpected operator cmd_type=elb consumer=False name=test producer=True stdio=stderr string_id=test
2023-01-06T19:09:39.484808Z [error    ] Extractor failed
```
