### ISSUE TITLE
Many many inherited plugins

### ISSUE THREAD

**Issue by menzenski** [meltano/meltano#7165]
I'm working on adding https://hub.meltano.com/extractors/tap-google-analytics to my project.My organization has many GA accounts/properties/views and I think I will need to inherit the tap-google-analytics plugin 49 times to account for all the views I need to extract. (The tap supports only one view_id).

**Comment by aaronsteers** [comment]
@menzenski - Thank you so much for raising. This is an interesting use case. I read through your description here and your slack thread.

Would a good solution be for the tap to be modified to accept an array of view IDs, and perhaps to add a view ID column to the resulting stream to allow the views to be distinguished from each other?

In other cases we sometimes suggest a [state-id-suffix](https://docs.meltano.com/concepts/environments#state-id-suffix). That might also or alternatively be a decent solution here.

What do you think?

**Comment by menzenski** [comment]
I don't know that there's really something specific that I'm asking for, but some thoughts that have occurred to me:

I made a text file `ga.txt` with one name per line, and ran this to create all the plugins in my meltano project:

```shell
for plugin_name in $(cat ga.txt); do meltano add extractor "$plugin_name" --inherit-from tap-google-analytics; done
```

This seemed to work fine, although it took a couple minutes to execute.

It does seem like there's a convention around the naming of inherited plugins. The examples in [the docs](https://docs.meltano.com/guide/plugin-management#plugin-inheritance) use two hyphens to separate the "base plugin name" from the "inherited plugin name", as in `tap-ga--client-foo`. I wonder if there'd be value in abstracting that into a utility function that could do something like (pseudocode)

```
for name in [client-foo, client-bar, client-baz]: meltano add extractor --inherit-from tap-google-analytics
```

which would yield `tap-google-analytics--client-foo`, `tap-google-analytics--client-bar`, `tap-google-analytics--client-baz` that all inherit from `tap-google-analytics`. This would help give naming consistency without requiring the developer to make sure they've got everything perfectly double-hyphenated themselves.

This could even be expanded to support a structured input format like:

```
name,view_id
client-foo,123123123
client-bar,456456456
```

Maybe this could be invoked such that the inherited plugins are each automatically configured with the appropriate `view_id` value.

I also think the documentation of plugin inheritance could be fleshed out with examples of configuration settings. If I add the `tap-google-analytics` plugin, and then add a plugin `tap-google-analytics--client-foo` that inherits from it, and then I run `meltano config tap-google-analytics set reports my-reports.json`, does the inheriting `tap-google-analytics--client-foo` plugin also get that configured `report` field?

I also haven't started running these yet, but I would like to run all of these taps and write the data to redshift. So it seems like I should expect to either have 49 separate invocations, or to write a job that runs all of them:

```yaml
jobs:
  - name: tap-google-analytics-to-target-redshift
    tasks:
      - tap-google-analytics--client-foo target-redshift
      - tap-google-analytics--client-bar target-redshift
      - tap-google-analytics--client-baz target-redshift
```

This is maybe getting out of meltano "proper" territory and into "orchestrator" territory, but is there a preferred approach here? I don't really care about the order in which these run, I'm more interested in easily defining a way to run them all.

**Comment by aaronsteers** [comment]
Regarding your last question, this "list of lists" syntax will tell the orchestrator that all items can run at the same time:

```yml
jobs: 
- name: tap-google-analytics-to-target-redshift
tasks: 
# Everything in the list can be run concurrently:
- - tap-google-analytics--client-foo target-redshift 
  - tap-google-analytics--client-bar target-redshift 
  - tap-google-analytics--client-baz target-redshift
# Anything below will wait for the above:
- dbt-redshift:run
```

**Comment by aaronsteers** [comment]
> I made a text file `ga.txt` with one name per line, and ran this to create all the plugins in my meltano project:
> 
> ```shell
> for plugin_name in $(cat ga.txt); do meltano add extractor "$plugin_name" --inherit-from tap-google-analytics; done
> ```
> 
> This seemed to work fine, although it took a couple minutes to execute.

One way to tune this (at least slightly) would be to use --no-install. 

https://docs.meltano.com/reference/command-line-interface#parameters

**Comment by menzenski** [comment]
@aaronsteers thank you! These are both great tips.

**Comment by menzenski** [comment]
Another issue that I have run into as I begin testing multiple taps is that the `tap-google-analytics` tap does not seem to output any information that identifies _which_ Google Analytics account/property/view it comes from. I need to be able to distinguish each of the 49 from the others.

It seems like one option is to use an individual report definition for each of the 49, with names that include an identifier. However this would result in one Redshift table per report per plugin which would yield something like 200 tables, and I think that's unwieldy on several levels.

I wonder if this is something that the Stream Maps functionality would be able to help with? I see in [the docs](https://sdk.meltano.com/en/latest/stream_maps.html#property-level-mapping-applications) that this seems to be supported:

> Property-level additions: new properties can be created based on inline user-defined expressions.

but I don't see any examples of how to do this.

Another option would be to update the `tap-google-analytics` plugin to support including this information. Maybe something like a boolean `include_project_identifiers` property that when `true` would add columns for `view_id`, `project_id`, `account_id` in the output? I'm going to look into this.

**Comment by edgarrmondragon** [comment]
@menzenski Stream maps are a good solution for these types of multi-tenant use cases. In `meltano.yml` this would look something like:

```yaml
plugins:
  extractors:
  - name: tap-google-analytics-1
    config:
      stream_maps:
        my_report:
          view_id: ...
          project_id: ...
          account_id: ...
  - name: tap-google-analytics-2
    config:
      stream_maps:
        my_report:
          view_id: ...
          project_id: ...
          account_id: ...
```

The downside is you'd have to do this for every instance of the tap.

**Comment by menzenski** [comment]
oh, neat @edgarrmondragon — that's all I need to do to add those columns in the output?

Am I right in assuming I'd need to then invoke the stream map in between tap and target directly like `meltano run tap-google-analytics-1 my_report target-redshift` ?

**Comment by menzenski** [comment]
I have opened https://github.com/MeltanoLabs/tap-google-analytics/pull/92 with a proposed configuration change to the tap, but I think @edgarrmondragon 's proposed stream map approach is likely going to be better for my use case.

**Comment by edgarrmondragon** [comment]
> Am I right in assuming I'd need to then invoke the stream map in between tap and target directly like `meltano run tap-google-analytics-1 my_report target-redshift` ?

@menzenski nope, the neat thing about `tap-google-analytics` being built on the SDK is that you only need to supply the stream map as config rather than run a mapper in between 🙂.

**Comment by menzenski** [comment]
@edgarrmondragon thanks!

Looking at [the docs](https://sdk.meltano.com/en/latest/stream_maps.html#constructing-the-stream-maps-config-object) some more, it seems that it's necessary to have one `stream_map` per stream, and that with `tap-google-analytics` each report object defined in the JSON reports file is realized as one stream, so I'll end up needing one stream map definition per report, per tap. Is that accurate?

For example, the [`default_report_definition.json`](https://github.com/MeltanoLabs/tap-google-analytics/blob/main/tap_google_analytics/defaults/default_report_definition.json) contains ten reports:

* `website_overview`
* `traffic_sources`
* `pages`
* `locations`
* `monthly_active_users`
* `four_weekly_active_users`
* `two_weekly_active_users`
* `weekly_active_users`
* `daily_active_users`
* `devices`

So I'd end up with

```yaml
plugins:
  extractors:
  - name: tap-google-analytics-1
    config:
      stream_maps:
        website_overview:
          view_id: ...
          project_id: ...
          account_id: ...
        traffic_sources:
          view_id: ...
          project_id: ...
          account_id: ...
        pages:
          view_id: ...
          project_id: ...
          account_id: ...
        locations:
          view_id: ...
          project_id: ...
          account_id: ...
        monthly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        four_weekly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        four_weekly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        two_weekly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        weekly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        daily_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        devices:
          view_id: ...
          project_id: ...
          account_id: ...
  - name: tap-google-analytics-2
    config:
      stream_maps:
        website_overview:
          view_id: ...
          project_id: ...
          account_id: ...
        traffic_sources:
          view_id: ...
          project_id: ...
          account_id: ...
        pages:
          view_id: ...
          project_id: ...
          account_id: ...
        locations:
          view_id: ...
          project_id: ...
          account_id: ...
        monthly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        four_weekly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        four_weekly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        two_weekly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        weekly_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        daily_active_users:
          view_id: ...
          project_id: ...
          account_id: ...
        devices:
          view_id: ...
          project_id: ...
          account_id: ...
```

That feels very verbose :/

Maybe this is something I could use YAML anchors & aliases to do more succinctly? I'm not very familiar with those yet but I've been meaning to try them out.

**Comment by menzenski** [comment]
So maybe I could get down to

```yaml
plugins:
  extractors:
  - name: tap-google-analytics-1
    config:
      stream_maps:
        website_overview: &tap-google-analytics-1-values
          view_id: ...
          project_id: ...
          account_id: ...
        traffic_sources: *tap-google-analytics-1-values
        pages: *tap-google-analytics-1-values
        locations: *tap-google-analytics-1-values
        monthly_active_users: *tap-google-analytics-1-values
        four_weekly_active_users: *tap-google-analytics-1-values
        four_weekly_active_users: *tap-google-analytics-1-values
        two_weekly_active_users: *tap-google-analytics-1-values
        weekly_active_users: *tap-google-analytics-1-values
        daily_active_users: *tap-google-analytics-1-values
        devices: *tap-google-analytics-1-values
  - name: tap-google-analytics-2
    config:
      stream_maps:
          website_overview: &tap-google-analytics-2-values
          view_id: ...
          project_id: ...
          account_id: ...
        traffic_sources: *tap-google-analytics-2-values
        pages: *tap-google-analytics-2-values
        locations: *tap-google-analytics-2-values
        monthly_active_users: *tap-google-analytics-2-values
        four_weekly_active_users: *tap-google-analytics-2-values
        four_weekly_active_users: *tap-google-analytics-2-values
        two_weekly_active_users: *tap-google-analytics-2-values
        weekly_active_users: *tap-google-analytics-2-values
        daily_active_users: *tap-google-analytics-2-values
        devices: *tap-google-analytics-2-values
```

That's actually much better now that I've written it out - not having to copy all those values multiple times would be nice.

**Comment by menzenski** [comment]
I got this working!! 🎉 

It ends up being not quite that simple, as the literal values need to be _doubly-quoted_ in order to set these column values to a literal string. The [docs](https://sdk.meltano.com/en/latest/stream_maps.html#constructing-expressions) mentioned the `simpleval` library and I had to go to the source there to see how to get a literal string.

But this works:

```yaml
plugins:
  extractors:
  - name: tap-google-analytics-1
    config:
      stream_maps:
        website_overview: &tap-google-analytics-1-values
          _view_id: '"123123123"'  # note the double quotes inside the single quotes
          _view_name: '"All Web Site Data"'
          _property_id: '"UA-123123123-1"'
          _property_name: '"My Project"'
          _account_id: '"234234234"'
          _account_name: '"My Account"'
        traffic_sources: *tap-google-analytics-1-values
```

@edgarrmondragon thank you for the tip re: stream maps!
