### ISSUE TITLE
bug: Meltano schema forbids `env` field in `environment[].plugins[]`

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7168]
### Meltano Version

2.13.0

### Python Version

3.10

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

N/A

### Description

[As documented here](https://docs.meltano.com/guide/configuration#specifying-environment-variables), Meltano supports using a plugin-specific environment-specific `env` field:

```yaml
environments:
- name: dev
  env:
    # environment level env
    MY_ENV_VAR: environment_level_env_var
  config:
    plugins:
      extractors:
        - name: tap-google-analytics
          variant: meltano
          env:
            # environment level plugin env
            MY_ENV_VAR: environment_level_plugin_env_var
```

This is not currently permitted by `schemas/meltano.schema.json`.

Relates to:
- #7148, because schema validate is performed during manifest generation
