### ISSUE TITLE
bug: env vars in `meltano.yml` cause exception while running meltano install since v2.13.0

### ISSUE THREAD

**Issue by JanickOtten** [meltano/meltano#7189]
### Meltano Version

2.13.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Windows 10 (using WSL2), same issue occurs on Ubuntu 22.04 VM

### Description

[Slack thread](https://app.slack.com/client/TFG99TU9K/C01TCRBBJD7/thread/C01TCRBBJD7-1674066405.617239)

Using Meltano's Docker image I set up env vars in the `meltano.yml` file to utilize dynamically created database connections (using docker compose) cross-projects. This worked like a charm in `v2.12.0`, however since `v2.13.0` I'm receiving an exception during the meltano install step in the Dockerfile.

This exception occurs:
```
invalid literal for int() with base 10: ''
```

For example, the meltano.yml contains the following loader:

```
loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
    config:
      host: ${DB_HOST}
      port: ${DB_PORT}
      user: ${DB_USER}
      password: ${DB_PASS}
```

And in the docker-compose.yml I set up the env vars:

```
services:
  meltano:
    <<: *meltano-image
    command: ui
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
```

If I remove the env vars from the meltano.yml, the exception doesn't occur.
Also, if I comment out the `meltano install` command from the `Dockerfile`, run the container and `bash` into it, the exception doesn't occur if I manually execute `meltano install`. In that case the env vars are also passed correctly, which I checked using the `meltano config target-postgres list` command.

The `Dockerfile` for reference:

```
# registry.gitlab.com/meltano/meltano:latest is also available in GitLab Registry
ARG MELTANO_IMAGE=meltano/meltano:latest-python3.9
FROM $MELTANO_IMAGE

RUN apt-get update && apt-get install libpq-dev -y

WORKDIR /project

# Install 
# Install any additional requirements
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy over Meltano project directory
COPY . .

RUN meltano install

# Don't allow changes to containerized project files
# ENV MELTANO_PROJECT_READONLY 1

ENTRYPOINT ["meltano"]
```
