### ISSUE TITLE
bug: `meltano config <plugin>` ignores `MELTANO_ENVIRONMENT` environment variable

### ISSUE THREAD

**Issue by menzenski** [meltano/meltano#7280]
### Meltano Version

2.15.0

### Python Version

3.11

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

macOS Monterey 12.6

### Description

We run meltano using environment variables for as much configuration as possible. I have found what I think is a bug, in that I have the meltano environment set via an environment variable, but the `meltano config <plugin>` command ignores it.

Relevant sections of `.env`:
```shell
MELTANO_ENVIRONMENT=dev
```

and `meltano.yml`
```yaml
include_paths:
- ./environments/dev.meltano.yml
plugins:
  extractors:
  - name: tap-spreadsheets-anywhere
    variant: ets
    pip_url: git+https://github.com/ets/tap-spreadsheets-anywhere.git@34f135b45a87b468f3375c72f9d451ae6525fae7
  - name: tap-s3-mongo
    inherit_from: tap-spreadsheets-anywhere
```

and from `environments/dev.meltano.yml`
```yaml
environments:
  - name: dev
    config:
      plugins:
        loaders:
          - name: target-redshift-mongo
            config:
              schema_mapping:
                payments:
                  target_schema: payments
                profiles:
                  target_schema: customers
```

Expected behavior: I expect that running `meltano config target-redshift-mongo` here (with meltano environment set to `dev` via environment variables) includes the schema mapping defined for this plugin in the dev environment.

Observed behavior: It does not include the schema mapping. But, if I pass `--environment=dev` explicitly as a command-line argument, it does include it.

```shell
# note: MELTANO_ENVIRONMENT=dev is set in .env
$ meltano config target-redshift-mongo
2023-02-07T12:43:14.151935Z [info     ] The default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.
{
  "host": "<SECRET>",
  "port": <SECRET>,
  "dbname": "<SECRET>",
  "user": "<SECRET>",
  "password": "<SECRET>",
  "s3_bucket": "<SECRET>",
  "default_target_schema": "<SECRET>",
  "copy_options": "EMPTYASNULL BLANKSASNULL TRIMBLANKS TRUNCATECOLUMNS TIMEFORMAT 'auto' COMPUPDATE OFF STATUPDATE OFF",
  "batch_size_rows": 100,
  "flush_all_streams": false,
  "parallelism": 0,
  "max_parallelism": 16,
  "disable_table_cache": false,
  "add_metadata_columns": true,
  "hard_delete": false,
  "data_flattening_max_level": 0,
  "primary_key_required": false,
  "validate_records": false,
  "skip_updates": false,
  "slices": 1
}
```

```shell
# note: MELTANO_ENVIRONMENT=dev is set in .env
$ meltano --environment=dev config target-redshift-mongo
2023-02-07T12:45:17.010451Z [info     ] Environment 'dev' is active
{
  "host": "<SECRET>",
  "port": <SECRET>,
  "dbname": "<SECRET>",
  "user": "<SECRET>",
  "password": "<SECRET>",
  "s3_bucket": "<SECRET>",
  "default_target_schema": "<SECRET>",
  "copy_options": "EMPTYASNULL BLANKSASNULL TRIMBLANKS TRUNCATECOLUMNS TIMEFORMAT 'auto' COMPUPDATE OFF STATUPDATE OFF",
  "batch_size_rows": 100,
  "flush_all_streams": false,
  "parallelism": 0,
  "max_parallelism": 16,
  "schema_mapping": {
    "payments": {
      "target_schema": "payments"
    },
    "profiles": {
      "target_schema": "customers"
    }
  },
  "disable_table_cache": false,
  "add_metadata_columns": true,
  "hard_delete": false,
  "data_flattening_max_level": 0,
  "primary_key_required": false,
  "validate_records": false,
  "skip_updates": false,
  "slices": 1
}
```

If I change the `default_environment` in `meltano.yml` (so that it's not the same as the environment I have defined in `.env`) I get the same behavior.
