### ISSUE TITLE
tap-mysql with Mysql. Exception: only INCREMENTAL, LOG_BASED, and FULL TABLE replication methods are supported

### ISSUE THREAD

**Issue by Iyanumanuel** [meltano/meltano#7361]
### Meltano Version

2.16.1

### Python Version

3.11.2

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

OSX

### Description

Hi all,
I am facing the following error using tap-mysql with mysql trying to set a replication job or do a config test for the tap using the default transferwise variant from [meltano hub tap-mysql](https://hub.meltano.com/extractors/tap-mysql--transferwise/). The issue was raised when your  project was still on Gitlab [link to gitlab](https://gitlab.com/meltano/meltano/-/issues/3498), but unfortunately the resolver did not mention how it was resolved.  

The output when it is invoked
<img width="497" alt="image" src="https://user-images.githubusercontent.com/44009494/222627840-cdc18a31-c1ba-467e-89b3-5ccc3e4a0920.png">

The output when doing a test
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/44009494/222628606-ea0dc989-e2d7-46db-b647-d431ad19e24e.png">

The output error when doing a run
<img width="834" alt="image" src="https://user-images.githubusercontent.com/44009494/222629802-96778d22-6eaa-4095-8b57-277378a73955.png">

I will paste what the config looks like below, is there something else I need to set in the config.

### Code

```python
Here is what my tap-mysql extractor config looks like:

  extractors:
  - name: tap-mysql
    variant: transferwise
    pip_url: pipelinewise-tap-mysql
    config:
      host: localhost
      user: user
      database: mysql
```

**Comment by tayloramurphy** [comment]
@Iyanumanuel 

try adding this to the config for tap-mysql:

```yaml
  extractors:
  - name: tap-mysql
    variant: transferwise
    pip_url: pipelinewise-tap-mysql
    config:
      host: localhost
      user: user
      database: mysql
   metadata:
     "*":
       replication-method: INCREMENTAL
```
