### ISSUE TITLE
bug: File with log are generated even if configuration doesn't include file handler

### ISSUE THREAD

**Issue by Bakrog** [meltano/meltano#7410]
### Meltano Version

2.16.1

### Python Version

3.11

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Debian - Docker - python:3.11-slim

### Description

Currently I have the following log configuration only declaring a console handler and disabling existing logs but even so running my job still generates an log file at `.meltano/logs/<job_name>/<id>/etl.log`.

```yaml
version: 1
disable_existing_loggers: true

formatters:
  json:
    (): meltano.core.logging.json_formatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    stream: "ext://sys.stderr"

root:
  level: INFO
  propagate: yes
  handlers: [console]
```

This generation of log files can lead to a failure when the process is running on kubernetes because of not enough ephemeral-storage resource. If possible the best scenario would be just send the logs to console and let the container log listener process ship them to the log aggregator.

But as I said before even explicit disabling existing logs and only declaring a console handler doesn't disable the generation of log files.

**Comment by tayloramurphy** [comment]
Thanks for the issue @Bakrog! @WillDaSilva I'm not sure I have as deep an undersatnding of expected behavior when `disable_existing_loggers` is set to `true`. Can you take a look here when you get a chance? cc @aaronsteers @seth-meltano

**Comment by tayloramurphy** [comment]
@Bakrog apologies for the delay here. It looks like `disable_existing_loggers` is disabling the Python logging system whereas the ELT log file is generated via a different method ([code here](https://github.com/meltano/meltano/blob/497c2c4f22dff1577b9c752c4c7e512e9fe49189/src/meltano/cli/elt.py#L240-L249)). 

@WillDaSilva @edgarrmondragon anything I misstated here?

**Comment by edgarrmondragon** [comment]
> @WillDaSilva @edgarrmondragon anything I misstated here?

@tayloramurphy No, you're right. That's part of the elt/run handler that redirects tap and targets logs to a file, and is not affected by high-level logging config. I think it was originally required by the UI to display and allow the user to download ELT logs and debugging in general. There's no way to disable them at the moment.

`disable_existing_loggers` is part of Python's built-in logging management:

<blockquote>

<p><em>disable_existing_loggers</em> - whether any existing non-root loggers are
to be disabled. This setting mirrors the parameter of the same name in
<a class="reference internal" href="#logging.config.fileConfig" title="logging.config.fileConfig"><code class="xref py py-func docutils literal notranslate"><span class="pre">fileConfig()</span></code></a>. If absent, this parameter defaults to <code class="docutils literal notranslate"><span class="pre">True</span></code>.
This value is ignored if <em>incremental</em> is <code class="docutils literal notranslate"><span class="pre">True</span></code>.</p>

</blockquote>

https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig

**Comment by Bakrog** [comment]
Thank you for the reply. So in resume there're no ways to disable the generation of log files by jobs. Is that right?

**Comment by edgarrmondragon** [comment]
> Thank you for the reply. So in resume there're no ways to disable the generation of log files by jobs. Is that right?

No, though you could point the `.meltano` directory that holds the run logs to a mounted volume by setting the [`MELTANO_SYS_DIR_ROOT`](https://docs.meltano.com/concepts/project#meltano-directory) env var.

**Comment by edgarrmondragon** [comment]
@Bakrog can you try the following configuration:

```yaml
version: 1
disable_existing_loggers: true

formatters:
  json:
    (): meltano.core.logging.json_formatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    stream: "ext://sys.stderr"

root:
  level: ERROR  # Note the log level
  propagate: yes
  handlers: [console]
```
