### ISSUE TITLE
bug: Configuration from CLI is not working properly

### ISSUE THREAD

**Issue by drbjim** [meltano/meltano#7515]
### Meltano Version

2.17.1

### Python Version

3.8

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Linux-debian??

### Description

Configurations from running cli is giving an error while from meltano.yml works fine.

configuration - working
```
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      overwrite: true
```

from CLI - not working

```
meltano config target-bigquery set overwrite true
```

gives you an error like below
```
2023-04-12T02:14:10.761972Z [info     ]     return schema.get(property, "") cmd_type=loader name=target-bigquery run_id=f241cfdd-bc93-4025-bc94-293f348f58e3 state_id=2023-04-12T021408--tap-salesforce--target-bigquery stdio=stderr
2023-04-12T02:14:10.762031Z [info     ] AttributeError: 'str' object has no attribute 'get' cmd_type=loader name=target-bigquery run_id=f241cfdd-bc93-4025-bc94-293f348f58e3 state_id=2023-04-12T021408--tap-salesforce--target-bigquery stdio=stderr
```
