### ISSUE TITLE
bug: Variable `MELTANO_LOAD_SCHEMA` is not present in project but still flagged by `MELTANO_FF_STRICT_ENV_VAR_MODE`

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#7548]
### Meltano Version

2.10.0 - 2.17.1

### Python Version

NA

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Any

### Description

Enabling the [`MELTANO_FF_STRICT_ENV_VAR_MODE`](https://docs.meltano.com/reference/settings#ffstrict_env_var_mode) flag in Meltano 2.17.1:

> Environment variable 'MELTANO_LOAD_SCHEMA' referenced but not set. Make sure the environment variable is set.

I'll try to investigate if earlier versions are affected.

**Comment by edgarrmondragon** [comment]
Ok, so this error only appears with `v2.10.0`, when the feature flag was introduced.

Seems to be caused by loaders that don't override `target_schema` to use their own _schema_ setting:

<blockquote>

<p>The value of this extra is usually not set explicitly, since its should correspond to the value of the loader’s own “target schema” setting.
If the name of this setting is not <code class="language-plaintext highlighter-rouge">schema</code>, its value <a href="/guide/configuration#expansion-in-setting-values">can be referenced</a> from the extra’s value using <code class="language-plaintext highlighter-rouge">$MELTANO_LOAD_&lt;TARGET_SCHEMA_SETTING&gt;</code>, e.g. <code class="language-plaintext highlighter-rouge">$MELTANO_LOAD_DESTINATION_SCHEMA</code> for setting <code class="language-plaintext highlighter-rouge">destination_schema</code>.</p>

</blockquote>

(from https://docs.meltano.com/concepts/plugins#target_schema-extra).

I confirmed that fixes the issue for target-duckdb:

```yaml
plugins:
  loaders:
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.4
    config:
      filepath: output/$MELTANO_ENVIRONMENT.duckdb
      default_target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA
    target_schema: $MELTANO_LOAD_DEFAULT_TARGET_SCHEMA
```

So a potential solution would be to make sure all plugins in the Hub either

1) Override the `target_schema` with a reference to their specific _schema_ setting, as above
2) Set `target_schema: null` when the setting is not relevant, e.g. for `target-jsonl`

Wdyt @tayloramurphy @pnadolny13?

---

Another solution, though I don't know at this point how safe it'd be, is to remove the `target_schema` extra altogether since it seems to only be relevant in the context of `meltano elt`.

**Comment by aaronsteers** [comment]
@edgarrmondragon Thanks for digging into this. It sounds like the current behavior of the extra should probably be modified or else (if feasible ) we may want to remove it altogether.

But to better understand this... is the extra telling Meltano the name of the config option that corresponds to the default load schema name, or is this informing Meltano of the value of that setting?

Either way, I'm not seeing a clear business value for this extra existing - but I'm unclear if that's because we indeed don't need it, or if I'm just not properly understanding it's function yet.

Can you foresee any issues if we just removed the extra?

**Comment by tayloramurphy** [comment]
The context for this extra is from the docs:

> A loader’s target_schema [extra](https://docs.meltano.com/guide/configuration#plugin-extras) holds the name of the database schema the loader has been configured to load data into (assuming the destination supports schemas), so that [transformers](https://docs.meltano.com/concepts/plugins#transformers) in the same pipeline can determine the database schema to load data from.

So it's primarily for the benefit of transformation via `meltano elt` which is something we've already heavily moved away from. This is definitely something we can deprecate in the near term as there are better ways of passing this information. Esp if we move to have `elt` just be `el`.

**Comment by edgarrmondragon** [comment]
@aaronsteers Taylor pointed out the context in which the extra is used.

> Presumably, $MELTANO_EXTRACT__LOAD_SCHEMA will still be populated and passed to the target if needed?

Yes, that'd be unaffected by removing the setting.

**Comment by aaronsteers** [comment]
@edgarrmondragon and @tayloramurphy 

Thanks both for the explanation and debug info here.

@edgarrmondragon , can you confirm if this also works?:

```yml
plugins:
  loaders:
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.4
    config:
      filepath: output/$MELTANO_ENVIRONMENT.duckdb
      default_target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA
    target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA
```

This is very similar to your example above, except uses the value seeded by Meltano from the tap namespace ($MELTANO_EXTRACT__LOAD_SCHEMA), and wouldn't require any specific behavior or config value existing in the target.

If the above can work, I think my vote here short term is to go ahead and apply `target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA` everywhere for all target definitions on the Hub.

For 3.0, I think we can consider removing the `target_schema` extra as well as renaming `elt` to `el` - which addresses the issue above regarding downstream transformers.

**Comment by tayloramurphy** [comment]
@edgarrmondragon what do you think of the proposal above? Any other suggested solves for this?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon what do you think of the proposal above? Any other suggested solves for this?

@tayloramurphy The problem I see with using `target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA` is that users of `elt` may be relying on the schema being set to a different value than the extractor's `load_schema`. Consider

```yaml
plugins:
  loaders:
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.4
    config:
      filepath: output/wh.duckdb
      default_target_schema: $MELTANO_ENVIRONMENT_$MELTANO_EXTRACT__LOAD_SCHEMA
    # For illustration. This property would actually exist in the lockfile, not meltano.yml
    target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA  
```

Then the actual target schema would be something like `dev_tap_github`, but dbt would try to reference `tap_github`, if the user doesn't override `target_schema`.

---

So, I think it makes sense to start by updating all loader Hub definitions to ensure they set `target_schema` to a safe value referencing the target's specific schema setting name, or an empty string if not applicable (no one's using the T of `elt` with target-jsonl).

---

I agree though, that we can later deprecate `target_schema` for 3.0 if we are making `elt` -> `el`.
