### ISSUE TITLE
bug: env variable defined in schedule scope does not have any affect

### ISSUE THREAD

**Issue by mertbakir** [meltano/meltano#7741]
### Meltano Version

2.18.0

### Python Version

3.9

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Linux - Ubuntu 22.04

### Description

```yaml
plugins:
  transformers:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core~=1.5.0 dbt-postgres~=1.5.0
    commands:
      run_dynamic_env:
        args: run --target ${DBT_TARGET_ENV}
jobs:
- name: run-dbt--full
  tasks:
  - dbt-postgres:clean dbt-postgres:run_dynamic_env
schedules:
- name: schedule01
  interval: 00 23 * * *
  job: run-dbt--full
  env:
    DBT_TARGET_ENV: target_name
```

I want to create the same schedule for different targets, so I thought I can leverage schedule level env variables but it doesn't work:
Run invocation could not be completed as block failed: Cannot start plugin: Command 'run_dynamic_env' referenced unset environment variable '${DBT_TARGET_ENV}' in an argument. Set the environment variable or update the command definition.

The variable DBT_TARGET_ENV  is not defined anywhere else but only at the schedule level.
When I define it on root plugin level it does not get overridden by the schedule level definition. Same applies to .env file. Meltano picks up the variable from root plugin level and .env file but not from schedule. 

Without the variable I have to define N plugin commands then N jobs then N schedules which makes 3x more definition of the same thing.

**Comment by tayloramurphy** [comment]
@mertbakir I'll pull some folks in here but the first thing I notice is that you're using a `transformer` instead of a `utility` for dbt. That _could_ have something to do how environment variables are handled. 

@cjohnhanson It looks like you added the tests and docs in https://github.com/meltano/meltano/pull/6674/files can you take a look at this issue? Could it have something to do with env var expansion in `commands`?

@pnadolny13 are we using `env` in schedules? Have you seen this behavior?

**Comment by mertbakir** [comment]
@tayloramurphy I just changed it to `utilities` instead of `transformers` but same error occured:

```
Cannot start plugin: Command 'run_dynamic_env' referenced unset environment variable '${DBT_TARGET_ENV}' in an argument. Set the environment variable or update the command definition.
```

**Comment by tayloramurphy** [comment]
@mertbakir thanks for checking. It must be something about expansion in commands.

**Comment by pnadolny13** [comment]
@mertbakir its possible that this is related to https://github.com/meltano/meltano/issues/3171 since args are nested.

**Comment by edgarrmondragon** [comment]
Maybe related to https://github.com/meltano/meltano/issues/8730, though I couldn't reproduce that one.

**Comment by edgarrmondragon** [comment]
I can't reproduce this anymore:

```yaml
plugins:
  utilities:
  - name: eol
    namespace: eol
    pip_url: norwegianblue==0.21.0
    executable: eol
    commands:
      python:
        args: ${EOL_FORMAT}
jobs:
- name: eol-python
  tasks:
  - eol:python
schedules:
- name: daily-eol-python
  interval: "@daily"
  job: eol-python
  env:
    EOL_FORMAT: "--csv"
```

Then `meltano schedule run daily-eol-python` works as expected.
