### ISSUE TITLE
feature: Allow plugins to be re-added to a project

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#8110]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

As discussed in #7907, a `--force` (or similar) flag would enable a plugin to be re-added to the project, regardless of whether or not the plugin already exists. This would essentially be a shortcut for:

```
meltano remove <plugin type> <plugin name>
meltano add <plugin type> <plugin name>
```

This feature would be useful in resetting a plugin definition that perhaps isn't quite working after some user changes, updating a custom plugin that doesn't have a `.lock` file (i.e. added from `--custom` or [`--from-ref`](#7907)), or converting from a custom plugin to the Hub definition once published.

Adding a new plugin with this flag should just `meltano add` as normal.

In terms of flag name and implied behaviour:
- `--force` sort of makes sense for both new and existing plugins, but doesn't really convey *why* you might want to use it
- `--refresh`, `--reset` and `--update` make sense for existing plugins and imply the underlying behaviour, but don't really make sense for new plugins

Open to other suggestions. :slightly_smiling_face:

### Expectations

1. *Given a project with a plugin previously added from Meltano Hub*

    <details>
    <summary><code>meltano.yml</code></summary>
    
    ```yml
    plugins:
      extractors:
      - name: tap-spotify
        variant: matatika
        pip_url: git+https://github.com/Matatika/tap-spotify.git
    ```
    </details>

    <details>
    <summary><code>plugins/extractors/tap-spotify--matatika.lock</code></summary>

    ```json
    {
      "plugin_type": "extractors",
      "name": "tap-spotify",
      "namespace": "tap_spotify",
      "variant": "matatika",
      "label": "Spotify",
      "docs": "https://hub.meltano.com/extractors/tap-spotify--matatika",
      "repo": "https://github.com/Matatika/tap-spotify",
      "pip_url": "git+https://github.com/Matatika/tap-spotify.git",
      "description": "Audio Streaming and Media Services",
      "logo_url": "https://hub.meltano.com/assets/logos/extractors/spotify.png",
      "capabilities": [
        "about",
        "catalog",
        "discover",
        "schema-flattening",
        "state",
        "stream-maps"
      ],
      "settings_group_validation": [
        [
          "client_id",
          "client_secret",
          "refresh_token"
        ]
      ],
      "settings": [
        {
          "name": "client_id",
          "kind": "password",
          "label": "Client ID",
          "description": "App client ID"
        },
        {
          "name": "client_secret",
          "kind": "password",
          "label": "Client Secret",
          "description": "App client secret"
        },
        {
          "name": "flattening_enabled",
          "kind": "boolean",
          "label": "Flattening Enabled",
          "description": "'True' to enable schema flattening and automatically expand nested properties."
        },
        {
          "name": "flattening_max_depth",
          "kind": "integer",
          "label": "Flattening Max Depth",
          "description": "The max depth to flatten schemas."
        },
        {
          "name": "refresh_token",
          "kind": "password",
          "label": "Refresh Token",
          "description": "Refresh token"
        },
        {
          "name": "stream_map_config",
          "kind": "object",
          "label": "Stream Map Config",
          "description": "User-defined config values to be used within map expressions."
        },
        {
          "name": "stream_maps",
          "kind": "object",
          "label": "Stream Maps",
          "description": "Config object for stream maps capability. For more information check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html)."
        }
      ]
    }
    ```
    </details>

    *and a new definition for the plugin (e.g. updated `pip_url`) available on Meltano Hub,*

    <details>
    <summary><code>https://hub.meltano.com/meltano/api/v1/plugins/extractors/tap-spotify--matatika</code></summary>
    
    ```json
    {
      "capabilities":[
        "about",
        "catalog",
        "discover",
        "schema-flattening",
        "state",
        "stream-maps"
      ],
      "description":"Audio Streaming and Media Services",
      "label":"Spotify",
      "logo_url":"https://hub.meltano.com/assets/logos/extractors/spotify.png",
      "name":"tap-spotify",
      "namespace":"tap_spotify",
      "pip_url":"git+https://github.com/Matatika/tap-spotify.git@v0.4.0",
      "repo":"https://github.com/Matatika/tap-spotify",
      "settings":[
        {
          "description":"App client ID",
          "kind":"password",
          "label":"Client ID",
          "name":"client_id"
        },
        {
          "description":"App client secret",
          "kind":"password",
          "label":"Client Secret",
          "name":"client_secret"
        },
        {
          "description":"'True' to enable schema flattening and automatically expand nested properties.",
          "kind":"boolean",
          "label":"Flattening Enabled",
          "name":"flattening_enabled"
        },
        {
          "description":"The max depth to flatten schemas.",
          "kind":"integer",
          "label":"Flattening Max Depth",
          "name":"flattening_max_depth"
        },
        {
          "description":"Refresh token",
          "kind":"password",
          "label":"Refresh Token",
          "name":"refresh_token"
        },
        {
          "description":"User-defined config values to be used within map expressions.",
          "kind":"object",
          "label":"Stream Map Config",
          "name":"stream_map_config"
        },
        {
          "description":"Config object for stream maps capability. For more information check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).",
          "kind":"object",
          "label":"Stream Maps",
          "name":"stream_maps"
        }
      ],
      "settings_group_validation":[
        [
          "client_id",
          "client_secret",
          "refresh_token"
        ]
      ],
      "variant":"matatika",
      "docs":"https://hub.meltano.com/extractors/tap-spotify--matatika"
    }
    ```
    </details>

    *when the plugin is re-added to the project from the Hub,*

    ```
    meltano add --[force|refresh|reset|update] extractor tap-spotify
    ```

    *expect an updated `meltano.yml` entry and `.lock` file*

    <details>
    <summary><code>meltano.yml</code></summary>
    
    ```yml
    plugins:
      extractors:
      - name: tap-spotify
        variant: matatika
        pip_url: git+https://github.com/Matatika/tap-spotify.git@v0.4.0
    ```
    </details>

    <details>
    <summary><code>plugins/extractors/tap-spotify--matatika.lock</code></summary>

    ```json
    {
      "plugin_type": "extractors",
      "name": "tap-spotify",
      "namespace": "tap_spotify",
      "variant": "matatika",
      "label": "Spotify",
      "docs": "https://hub.meltano.com/extractors/tap-spotify--matatika",
      "repo": "https://github.com/Matatika/tap-spotify",
      "pip_url": "git+https://github.com/Matatika/tap-spotify.git@v0.4.0",
      "description": "Audio Streaming and Media Services",
      "logo_url": "https://hub.meltano.com/assets/logos/extractors/spotify.png",
      "capabilities": [
        "about",
        "catalog",
        "discover",
        "schema-flattening",
        "state",
        "stream-maps"
      ],
      "settings_group_validation": [
        [
          "client_id",
          "client_secret",
          "refresh_token"
        ]
      ],
      "settings": [
        {
          "name": "client_id",
          "kind": "password",
          "label": "Client ID",
          "description": "App client ID"
        },
        {
          "name": "client_secret",
          "kind": "password",
          "label": "Client Secret",
          "description": "App client secret"
        },
        {
          "name": "flattening_enabled",
          "kind": "boolean",
          "label": "Flattening Enabled",
          "description": "'True' to enable schema flattening and automatically expand nested properties."
        },
        {
          "name": "flattening_max_depth",
          "kind": "integer",
          "label": "Flattening Max Depth",
          "description": "The max depth to flatten schemas."
        },
        {
          "name": "refresh_token",
          "kind": "password",
          "label": "Refresh Token",
          "description": "Refresh token"
        },
        {
          "name": "stream_map_config",
          "kind": "object",
          "label": "Stream Map Config",
          "description": "User-defined config values to be used within map expressions."
        },
        {
          "name": "stream_maps",
          "kind": "object",
          "label": "Stream Maps",
          "description": "Config object for stream maps capability. For more information check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html)."
        }
      ]
    }
    ```
    </details>

1. *Given a project with a custom plugin previously added*

    <details>
    <summary><code>meltano.yml</code></summary>
    
    ```yml
    plugins:
      extractors:
      - name: tap-spotify
        namespace: tap_spotify
        label: Spotify
        variant: matatika
        repo: https://github.com/Matatika/tap-spotify
        pip_url: git+https://github.com/Matatika/tap-spotify.git
        description: Audio Streaming and Media Services
        logo_url: /assets/logos/extractors/spotify.png
        capabilities:
        - about
        - catalog
        - discover
        - schema-flattening
        - state
        - stream-maps
        settings_group_validation:
        - - client_id
          - client_secret
          - refresh_token
        settings:
        - name: client_id
          kind: password
          label: Client ID
          description: App client ID
        - name: client_secret
          kind: password
          label: Client Secret
          description: App client secret
        - name: flattening_enabled
          kind: boolean
          label: Flattening Enabled
          description: "'True' to enable schema flattening and automatically expand nested\
            \ properties."
        - name: flattening_max_depth
          kind: integer
          label: Flattening Max Depth
          description: The max depth to flatten schemas.
        - name: refresh_token
          kind: password
          label: Refresh Token
          description: Refresh token
        - name: stream_map_config
          kind: object
          label: Stream Map Config
          description: User-defined config values to be used within map expressions.
        - name: stream_maps
          kind: object
          label: Stream Maps
          description: Config object for stream maps capability. For more information
            check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).
    ```
    </details>

    *and a new definition for the plugin (e.g. updated `pip_url`) available locally*

    <details>
    <summary><code>tap-spotify--matatika.yml</code></summary>
    
    ```yml
    capabilities:
    - about
    - catalog
    - discover
    - schema-flattening
    - state
    - stream-maps
    description: Audio Streaming and Media Services
    domain_url: https://developer.spotify.com/documentation/web-api/
    keywords:
    - api
    - meltano_sdk
    label: Spotify
    logo_url: /assets/logos/extractors/spotify.png
    maintenance_status: active
    name: tap-spotify
    namespace: tap_spotify
    pip_url: git+https://github.com/Matatika/tap-spotify.git@v0.4.0
    quality: gold
    repo: https://github.com/Matatika/tap-spotify
    settings:
    - description: App client ID
      kind: password
      label: Client ID
      name: client_id
    - description: App client secret
      kind: password
      label: Client Secret
      name: client_secret
    - description: "'True' to enable schema flattening and automatically expand nested
        properties."
      kind: boolean
      label: Flattening Enabled
      name: flattening_enabled
    - description: The max depth to flatten schemas.
      kind: integer
      label: Flattening Max Depth
      name: flattening_max_depth
    - description: Refresh token
      kind: password
      label: Refresh Token
      name: refresh_token
    - description: User-defined config values to be used within map expressions.
      kind: object
      label: Stream Map Config
      name: stream_map_config
    - description: Config object for stream maps capability. For more information check
        out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).
      kind: object
      label: Stream Maps
      name: stream_maps
    settings_group_validation:
    - - client_id
      - client_secret
      - refresh_token
    variant: matatika
    ```
    </details>

    *when the plugin is re-added to the project from the local path,*

     ```
    meltano add --from-ref tap-spotify--matatika.yml --[force|refresh|reset|update] extractor tap-spotify extractor tap-spotify
    ```

    *expect an updated `meltano.yml` entry*

    <details>
    <summary><code>meltano.yml</code></summary>
    
    ```yml
    plugins:
      extractors:
      - name: tap-spotify
        namespace: tap_spotify
        label: Spotify
        variant: matatika
        repo: https://github.com/Matatika/tap-spotify
        pip_url: git+https://github.com/Matatika/tap-spotify.git@0.4.0
        description: Audio Streaming and Media Services
        logo_url: /assets/logos/extractors/spotify.png
        capabilities:
        - about
        - catalog
        - discover
        - schema-flattening
        - state
        - stream-maps
        settings_group_validation:
        - - client_id
          - client_secret
          - refresh_token
        settings:
        - name: client_id
          kind: password
          label: Client ID
          description: App client ID
        - name: client_secret
          kind: password
          label: Client Secret
          description: App client secret
        - name: flattening_enabled
          kind: boolean
          label: Flattening Enabled
          description: "'True' to enable schema flattening and automatically expand nested\
            \ properties."
        - name: flattening_max_depth
          kind: integer
          label: Flattening Max Depth
          description: The max depth to flatten schemas.
        - name: refresh_token
          kind: password
          label: Refresh Token
          description: Refresh token
        - name: stream_map_config
          kind: object
          label: Stream Map Config
          description: User-defined config values to be used within map expressions.
        - name: stream_maps
          kind: object
          label: Stream Maps
          description: Config object for stream maps capability. For more information
            check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).
    ```
    </details>

1. *Given a project with a plugin previously added from Meltano Hub*

    <details>
    <summary><code>meltano.yml</code></summary>
    
    ```yml
    plugins:
      extractors:
      - name: tap-spotify
        variant: matatika
        pip_url: git+https://github.com/Matatika/tap-spotify.git
    ```
    </details>

    <details>
    <summary><code>plugins/extractors/tap-spotify--matatika.lock</code></summary>

    ```json
    {
      "plugin_type": "extractors",
      "name": "tap-spotify",
      "namespace": "tap_spotify",
      "variant": "matatika",
      "label": "Spotify",
      "docs": "https://hub.meltano.com/extractors/tap-spotify--matatika",
      "repo": "https://github.com/Matatika/tap-spotify",
      "pip_url": "git+https://github.com/Matatika/tap-spotify.git",
      "description": "Audio Streaming and Media Services",
      "logo_url": "https://hub.meltano.com/assets/logos/extractors/spotify.png",
      "capabilities": [
        "about",
        "catalog",
        "discover",
        "schema-flattening",
        "state",
        "stream-maps"
      ],
      "settings_group_validation": [
        [
          "client_id",
          "client_secret",
          "refresh_token"
        ]
      ],
      "settings": [
        {
          "name": "client_id",
          "kind": "password",
          "label": "Client ID",
          "description": "App client ID"
        },
        {
          "name": "client_secret",
          "kind": "password",
          "label": "Client Secret",
          "description": "App client secret"
        },
        {
          "name": "flattening_enabled",
          "kind": "boolean",
          "label": "Flattening Enabled",
          "description": "'True' to enable schema flattening and automatically expand nested properties."
        },
        {
          "name": "flattening_max_depth",
          "kind": "integer",
          "label": "Flattening Max Depth",
          "description": "The max depth to flatten schemas."
        },
        {
          "name": "refresh_token",
          "kind": "password",
          "label": "Refresh Token",
          "description": "Refresh token"
        },
        {
          "name": "stream_map_config",
          "kind": "object",
          "label": "Stream Map Config",
          "description": "User-defined config values to be used within map expressions."
        },
        {
          "name": "stream_maps",
          "kind": "object",
          "label": "Stream Maps",
          "description": "Config object for stream maps capability. For more information check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html)."
        }
      ]
    }
    ```
    </details>

    *and a definition for the plugin available locally*

    <details>
    <summary><code>tap-spotify--matatika.yml</code></summary>
    
    ```yml
    capabilities:
    - about
    - catalog
    - discover
    - schema-flattening
    - state
    - stream-maps
    description: Audio Streaming and Media Services
    domain_url: https://developer.spotify.com/documentation/web-api/
    keywords:
    - api
    - meltano_sdk
    label: Spotify
    logo_url: /assets/logos/extractors/spotify.png
    maintenance_status: active
    name: tap-spotify
    namespace: tap_spotify
    pip_url: git+https://github.com/Matatika/tap-spotify.git
    quality: gold
    repo: https://github.com/Matatika/tap-spotify
    settings:
    - description: App client ID
      kind: password
      label: Client ID
      name: client_id
    - description: App client secret
      kind: password
      label: Client Secret
      name: client_secret
    - description: "'True' to enable schema flattening and automatically expand nested
        properties."
      kind: boolean
      label: Flattening Enabled
      name: flattening_enabled
    - description: The max depth to flatten schemas.
      kind: integer
      label: Flattening Max Depth
      name: flattening_max_depth
    - description: Refresh token
      kind: password
      label: Refresh Token
      name: refresh_token
    - description: User-defined config values to be used within map expressions.
      kind: object
      label: Stream Map Config
      name: stream_map_config
    - description: Config object for stream maps capability. For more information check
        out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).
      kind: object
      label: Stream Maps
      name: stream_maps
    settings_group_validation:
    - - client_id
      - client_secret
      - refresh_token
    variant: matatika
    ```
    </details>

    *when the plugin is re-added to the project from the local path,*

     ```
    meltano add --from-ref tap-spotify--matatika.yml --[force|refresh|reset|update] extractor tap-spotify extractor tap-spotify
    ```

    *expect an updated `meltano.yml` entry*

    <details>
    <summary><code>meltano.yml</code></summary>
    
    ```yml
    plugins:
      extractors:
      - name: tap-spotify
        namespace: tap_spotify
        label: Spotify
        variant: matatika
        repo: https://github.com/Matatika/tap-spotify
        pip_url: git+https://github.com/Matatika/tap-spotify.git
        description: Audio Streaming and Media Services
        logo_url: /assets/logos/extractors/spotify.png
        capabilities:
        - about
        - catalog
        - discover
        - schema-flattening
        - state
        - stream-maps
        settings_group_validation:
        - - client_id
          - client_secret
          - refresh_token
        settings:
        - name: client_id
          kind: password
          label: Client ID
          description: App client ID
        - name: client_secret
          kind: password
          label: Client Secret
          description: App client secret
        - name: flattening_enabled
          kind: boolean
          label: Flattening Enabled
          description: "'True' to enable schema flattening and automatically expand nested\
            \ properties."
        - name: flattening_max_depth
          kind: integer
          label: Flattening Max Depth
          description: The max depth to flatten schemas.
        - name: refresh_token
          kind: password
          label: Refresh Token
          description: Refresh token
        - name: stream_map_config
          kind: object
          label: Stream Map Config
          description: User-defined config values to be used within map expressions.
        - name: stream_maps
          kind: object
          label: Stream Maps
          description: Config object for stream maps capability. For more information
            check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).
    ```
    </details>

1. *Given a project with a custom plugin previously added*

    <details>
    <summary><code>meltano.yml</code></summary>
    
    ```yml
    plugins:
      extractors:
      - name: tap-spotify
        namespace: tap_spotify
        label: Spotify
        variant: matatika
        repo: https://github.com/Matatika/tap-spotify
        pip_url: git+https://github.com/Matatika/tap-spotify.git
        description: Audio Streaming and Media Services
        logo_url: /assets/logos/extractors/spotify.png
        capabilities:
        - about
        - catalog
        - discover
        - schema-flattening
        - state
        - stream-maps
        settings_group_validation:
        - - client_id
          - client_secret
          - refresh_token
        settings:
        - name: client_id
          kind: password
          label: Client ID
          description: App client ID
        - name: client_secret
          kind: password
          label: Client Secret
          description: App client secret
        - name: flattening_enabled
          kind: boolean
          label: Flattening Enabled
          description: "'True' to enable schema flattening and automatically expand nested\
            \ properties."
        - name: flattening_max_depth
          kind: integer
          label: Flattening Max Depth
          description: The max depth to flatten schemas.
        - name: refresh_token
          kind: password
          label: Refresh Token
          description: Refresh token
        - name: stream_map_config
          kind: object
          label: Stream Map Config
          description: User-defined config values to be used within map expressions.
        - name: stream_maps
          kind: object
          label: Stream Maps
          description: Config object for stream maps capability. For more information
            check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).
    ```
    </details>

    *and a definition for the plugin available on Meltano Hub,*

    <details>
    <summary><code>https://hub.meltano.com/meltano/api/v1/plugins/extractors/tap-spotify--matatika</code></summary>
    
    ```json
    {
      "capabilities":[
        "about",
        "catalog",
        "discover",
        "schema-flattening",
        "state",
        "stream-maps"
      ],
      "description":"Audio Streaming and Media Services",
      "label":"Spotify",
      "logo_url":"https://hub.meltano.com/assets/logos/extractors/spotify.png",
      "name":"tap-spotify",
      "namespace":"tap_spotify",
      "pip_url":"git+https://github.com/Matatika/tap-spotify.git",
      "repo":"https://github.com/Matatika/tap-spotify",
      "settings":[
        {
          "description":"App client ID",
          "kind":"password",
          "label":"Client ID",
          "name":"client_id"
        },
        {
          "description":"App client secret",
          "kind":"password",
          "label":"Client Secret",
          "name":"client_secret"
        },
        {
          "description":"'True' to enable schema flattening and automatically expand nested properties.",
          "kind":"boolean",
          "label":"Flattening Enabled",
          "name":"flattening_enabled"
        },
        {
          "description":"The max depth to flatten schemas.",
          "kind":"integer",
          "label":"Flattening Max Depth",
          "name":"flattening_max_depth"
        },
        {
          "description":"Refresh token",
          "kind":"password",
          "label":"Refresh Token",
          "name":"refresh_token"
        },
        {
          "description":"User-defined config values to be used within map expressions.",
          "kind":"object",
          "label":"Stream Map Config",
          "name":"stream_map_config"
        },
        {
          "description":"Config object for stream maps capability. For more information check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).",
          "kind":"object",
          "label":"Stream Maps",
          "name":"stream_maps"
        }
      ],
      "settings_group_validation":[
        [
          "client_id",
          "client_secret",
          "refresh_token"
        ]
      ],
      "variant":"matatika",
      "docs":"https://hub.meltano.com/extractors/tap-spotify--matatika"
    }
    ```
    </details>

    *when the plugin is re-added to the project from the Hub,*

    ```
    meltano add --[force|refresh|reset|update] extractor tap-spotify
    ```

    *expect an updated `meltano.yml` entry and `.lock` file*

    <details>
    <summary><code>meltano.yml</code></summary>
    
    ```yml
    plugins:
      extractors:
      - name: tap-spotify
        variant: matatika
        pip_url: git+https://github.com/Matatika/tap-spotify.git
    ```
    </details>

    <details>
    <summary><code>plugins/extractors/tap-spotify--matatika.lock</code></summary>

    ```json
    {
      "plugin_type": "extractors",
      "name": "tap-spotify",
      "namespace": "tap_spotify",
      "variant": "matatika",
      "label": "Spotify",
      "docs": "https://hub.meltano.com/extractors/tap-spotify--matatika",
      "repo": "https://github.com/Matatika/tap-spotify",
      "pip_url": "git+https://github.com/Matatika/tap-spotify.git",
      "description": "Audio Streaming and Media Services",
      "logo_url": "https://hub.meltano.com/assets/logos/extractors/spotify.png",
      "capabilities": [
        "about",
        "catalog",
        "discover",
        "schema-flattening",
        "state",
        "stream-maps"
      ],
      "settings_group_validation": [
        [
          "client_id",
          "client_secret",
          "refresh_token"
        ]
      ],
      "settings": [
        {
          "name": "client_id",
          "kind": "password",
          "label": "Client ID",
          "description": "App client ID"
        },
        {
          "name": "client_secret",
          "kind": "password",
          "label": "Client Secret",
          "description": "App client secret"
        },
        {
          "name": "flattening_enabled",
          "kind": "boolean",
          "label": "Flattening Enabled",
          "description": "'True' to enable schema flattening and automatically expand nested properties."
        },
        {
          "name": "flattening_max_depth",
          "kind": "integer",
          "label": "Flattening Max Depth",
          "description": "The max depth to flatten schemas."
        },
        {
          "name": "refresh_token",
          "kind": "password",
          "label": "Refresh Token",
          "description": "Refresh token"
        },
        {
          "name": "stream_map_config",
          "kind": "object",
          "label": "Stream Map Config",
          "description": "User-defined config values to be used within map expressions."
        },
        {
          "name": "stream_maps",
          "kind": "object",
          "label": "Stream Maps",
          "description": "Config object for stream maps capability. For more information check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html)."
        }
      ]
    }
    ```
    </details>
