### ISSUE TITLE
feature: Support `meltano test` for taps

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8112]
### Feature scope

CLI (options, error messages, logging, etc.)

## Problem

The `meltano test` CLI uses plugin commands to run tests for one or more plugins. However It's not working great at the moment for taps because Meltano doesn't know that it also needs to pass other options, like `--config`, so it fails if config is required.

## Proposal

* Add a new boolean `pass_plugin_args` field to the `Command` object.
* Update `PluginInvoker.exec_args` to call `self.plugin.exec_args`, if `command_config.pass_plugin_args` is true.

https://github.com/meltano/meltano/blob/d59a7c93f6c2d49abe8b1f6d094f60ed19bab54e/src/meltano/core/plugin_invoker.py#L292-L298

This will allow Meltano to call `tap-example --config ... --test` under the hood.

With that, the following config

```yaml
plugins:
  extractors:
  - name: tap-stackexchange
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-stackexchange.git
    commands:
      test:
        pass_plugin_args: true
        args: --test
```

should allow `meltano test tap-stackexchange` to work as expected.
