### ISSUE TITLE
bug: state is not stored for new streams

### ISSUE THREAD

**Issue by florian-ernst-alan** [meltano/meltano#8316]
### Meltano Version

3.1.0, 3.2.0

### Python Version

3.10

### Bug scope

Other

### Operating System

MacOS 14

### Description

When a new LOG_BASED table is selected in Meltano (on a Postgres extractor, pipelinewise variant), its state is not recorded. Every subsequent run performs a full refresh of the new stream (with sync method `logical_initial`)

Here is my config:
```yml
version: 1
default_environment: default
project_id: 465bbe08-aa73-4db8-9e1b-891756fac617
environments:
- name: default
plugins:
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres
    config:
      host: redacted.rds.amazonaws.com
      port: 5432
      user: redacted
      password: redacted
      dbname: metabase
      default_replication_method: LOG_BASED
    load_schema: meltano__metabase_2
    select:
    - public-metabase_fieldvalues.*
#    - public-login_history.* ## Make the 1st import without it, and the 2nd import with it
  loaders:
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      ### Setup ###
      account: redacted
      dbname: TURING
      user: CIRCLE_CI_FOR_SYNCED_VIEWS
      password: redacted
      warehouse: ALANERS_WH
      file_format: func.my_parquet_format
      s3_bucket: backend-snapshot-copy
      s3_key_prefix: snowflake-imports/
      stage: backend.my_s3_stage
      ### Performance ###
      batch_size_rows: 500000
      # To make sure a potential crash doesn't force us to get back to the beginning, make sure we send batches at least every 5 minutes
      batch_wait_limit_seconds: 300
      # Use from 1 to 16 cores
      parallelism: 0
      parallelism_max: 16
      ### Misc ###
      add_metadata_columns: true
      hard_delete: true
```

The `public-login_history` table was commented for the first 2 runs, and then uncommented for the 3d and 4th run:
* [First run logs (1 table)](https://gist.github.com/florian-ernst-alan/3d0eef5d32d19584d0f605e863e16596)
* [Second run logs (1 table)](https://gist.github.com/florian-ernst-alan/ecac144310b199cc867030394a4c36be)
* [Third run logs (2 tables)](https://gist.github.com/florian-ernst-alan/fcb18d8dd95c19863dd54f60318a5ac3)
* [Fourth run logs (2 tables)](https://gist.github.com/florian-ernst-alan/ef698bb96f932e36c5b5b8d005db5cbf)

Here is the state after the different runs:
```jsonl
"After the 1st run:"
{"bookmarks": {"public-metabase_fieldvalues": {"last_replication_method": "LOG_BASED", "lsn": 24943838426952, "version": 1702315148321, "xmin": null}}

"After the 2nd run:"
{"currently_syncing": null, "bookmarks": {"public-metabase_fieldvalues": {"last_replication_method": "LOG_BASED", "lsn": 24943895763968, "version": 1702315148321, "xmin": null}}}

"After the 3d run (in which public-login_history was selected):"
{"currently_syncing": null, "bookmarks": {"public-metabase_fieldvalues": {"last_replication_method": "LOG_BASED", "lsn": 24943895789464, "version": 1702315148321, "xmin": null}}}

"After the 4th run (in which public-login_history was also selected):"
{"currently_syncing": null, "bookmarks": {"public-metabase_fieldvalues": {"last_replication_method": "LOG_BASED", "lsn": 24943895875056, "version": 1702315148321, "xmin": null}}}
```

I reproduced it with lot of tables, and everytime I get the same problem. **Performing a full refresh solves the issue**, but that's not a scalable solution.

**Why is that happening?**
