### ISSUE TITLE
bug: HTTPHandler doesn't respect formatter, only produces logs in key=val format

### ISSUE THREAD

**Issue by BillyUdders** [meltano/meltano#8375]
### Meltano Version

3.2.0

### Python Version

3.11

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Mac OS X, Linux

### Description

Using the below http-logging.yaml with meltano `el` command like so: `meltano --log-config http-logging.yaml el tap-name target-name` does not produce JSON formatted log messages.

```
version: 1
disable_existing_loggers: false
formatters:
  json:
    (): meltano.core.logging.json_formatter
handlers:
  http:
    class: logging.handlers.HTTPHandler
    level: INFO
    formatter: json
    host: 'localhost:3000'
    url: '/log'
    method: 'POST'
root:
  level: DEBUG
  propagate: true
  handlers: [http]
```

When I run the command I get log messages with a body sent to my echo server running that look like this:

```
name=meltano.cli.elt&msg=%7B%27name%27%3A+%27meltano%27%2C+%27run_id%27%3A+%27424571c7-e70d-4473-a5c8-381fed100276%27%2C+%27state_id%27%3A+%272024-01-23T1
60909--tap-n-target-names%27%2C+%27event%27%3A+%27Extract+%26+load+complete%21%27%2C+%27level%27%3A+%27info%27%2C+%27timestamp%27%3A+%272024-01-23T
16%3A09%3A23.403021Z%27%7D&args=%28%29&levelname=INFO&levelno=20&pathname=%my_path_name$24
hon3.11%2Fsite-packages%2Fmeltano%2Fcli%2Felt.py&filename=elt.py&module=elt&exc_info=None&exc_text=None&stack_info=None&lineno=509&funcName=_run_extract_load&created=1706026163.4030552&msecs=403.0&relativeCreated=14806.555271148682&thread=8064847872&threadName=MainThread&processName=MainProcess&process=73440&_logger=%3C_FixedFindCallerLogger+meltano.cli.elt+%28DEBUG%29%3E&_name=info
```

Which isn't JSON but also quite hard to parse and noisy. I've double/triple checked this with Logstash running in a docker container on my local machine, and in a pod in an EKS cluster.
