### ISSUE TITLE
feature: Error Tracking plugin

### ISSUE THREAD

**Issue by danilofuchs** [meltano/meltano#8708]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

I would like to log Meltano errors to Sentry, to be notified when our periodic ELT breaks.

Currently we have to manually investigate logs.

Would be nice if there was a hook for plugins to intercept errors raised by other plugins

**Comment by danilofuchs** [comment]
I am trying to setup Sentry as a logger handler in logging.yaml, but I am having trouble understanding the error:

## Option 1: Use `SentryHandler` directly from the SDK
```yaml
version: 1
disable_existing_loggers: false

formatters:
  structured_colored:
    (): meltano.core.logging.console_log_formatter
    colors: True

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured_colored
    stream: "ext://sys.stderr"
  sentry:
    class: sentry_sdk.integrations.logging.SentryHandler
    level: INFO

root:
  level: DEBUG
  propagate: yes
  handlers: [console, sentry]
```
Does not work as the SDK is not initialized from the YAML file ([Sentry will not support this](https://github.com/getsentry/sentry-python/issues/1216))

## Option 2: Custom Logger

I implemented the following:
```
sentry_logger/
   - __init__.py
logging.yaml
meltano.yaml
plugins/
...
```

```python
# __init__.py
import sentry_sdk
from sentry_sdk.integrations.logging import SentryHandler, LoggingIntegration

sentry_sdk.init(
    dsn="https://dsn.io",
    integrations=[
        LoggingIntegration(event_level=None)  # Disable automatic logging integration
    ],
)

__all__ = ["SentryHandler"]
```

```yaml
version: 1
disable_existing_loggers: false

formatters:
  structured_colored:
    (): meltano.core.logging.console_log_formatter
    colors: True

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured_colored
    stream: "ext://sys.stderr"
  sentry:
    class: sentry_logger.SentryHandler
    level: INFO

root:
  level: DEBUG
  propagate: yes
  handlers: [console, sentry]
```

The meltano error message is not clear at all, not sure what the issue is exactly:

```
Unable to configure handler 'sentry'
```

**Comment by edgarrmondragon** [comment]
For Option 2, you might want to either:

1. Installer the logger in the same virtual env as Meltano
2. Use `PYTHONPATH` to tell the interpreter to make it importable at runtime, e.g. `PYTHONPATH=$PWD meltano config meltano list`

**Comment by edgarrmondragon** [comment]
> Would be nice if there was a hook for plugins to intercept errors raised by other plugins

Also, curious to know how you imagine this.

**Comment by edgarrmondragon** [comment]
... and FWIW I'd love to make Meltano more extensible in a few aspects. For example, https://github.com/meltano/meltano/pull/8367 would introduce add-ons for state backends and settings, but we could also do this for log forwarders, setup and teardown hooks, notifications, etc.

**Comment by danilofuchs** [comment]
> For Option 2, you might want to either:
> 
> 1. Installer the logger in the same virtual env as Meltano
> 2. Use `PYTHONPATH` to tell the interpreter to make it importable at runtime, e.g. `PYTHONPATH=$PWD meltano config meltano list`

I'll see if this works, thanks!

**Comment by danilofuchs** [comment]
> > Would be nice if there was a hook for plugins to intercept errors raised by other plugins
> 
> Also, curious to know how you imagine this.

Not sure if adding a new plugin type would be overkill

I imagine we could declare a `error_tracker` field to utility plugins, a function which receives an error and its stack, and decides whether to throw

Or an `error_tracker` field on the meltano config itself

Not sure how these ideas are compatible with Meltano philosophies

**Comment by danilofuchs** [comment]
Hello @edgarrmondragon!

The `$PYTHONPATH` solution worked for setting up the Sentry Logger (option 2)!

The end result:

```
sentry_logger/
   - __init__.py
logging.yaml
meltano.yaml
requirements.txt
Dockerfile
plugins/
...
```

```python
# __init__.py
import sentry_sdk
from sentry_sdk.integrations.logging import SentryHandler, LoggingIntegration
import os

sentry_sdk.init(
    dsn="https://dsn.io",
    environment=os.environ["MELTANO_ENVIRONMENT"],
)

__all__ = ["SentryHandler"]
```

```yaml
# logging.yaml
version: 1
disable_existing_loggers: false

formatters:
  structured_colored:
    (): meltano.core.logging.console_log_formatter
    colors: True

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured_colored
    stream: "ext://sys.stderr"
  sentry:
    class: sentry_logger.SentryHandler
    level: INFO

root:
  level: DEBUG
  propagate: yes
  handlers: [console, sentry]
```

```
# requirements.txt
sentry-sdk==2.14.0
```

```dockerfile
# Dockerfile

...
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./sentry_logger ./sentry_logger
ENV PYTHONPATH /project
...
```

Now the issue is that all error logs from taps are logged as `level: info`, thus Sentry does not detect them as issues:

![image](https://github.com/user-attachments/assets/91164af8-3b6d-4ba6-b7a7-f00482209fda)

I assume this could be fixed through https://github.com/meltano/meltano/issues/8555
