### ISSUE TITLE
bug: Plugin auto installer doesn't work for tasks that are specified like dbt:run

### ISSUE THREAD

**Issue by visch** [meltano/meltano#8715]
### Meltano Version

3.5.0

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Ubuntu 20.04.5

### Description

The autoinstall feature is nice https://github.com/meltano/meltano/pull/8482 but it doesn't work for all scenarios. Plugins that are calling a task in a job don't seem to have their plugin pulled out and installed properly

Steps to reproduce:
1. Put the meltano.yml below into a directory
2. Run ` meltano lock --update --all`
3. Run `meltano run test_task_fail_install` , it'll install tap and target postgres but not dbt and fail with
```
2024-08-20T17:59:17.000114Z [info     ] Environment 'dev' is active
Error: Block dbt:run not found
```

meltano.yml
```yaml
version: 1
default_environment: dev
project_id: test_plugin_autoinstall
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
  loaders:
  - name: target-postgres
    variant: meltanolabs
    pip_url: meltanolabs-target-postgres
  transformers:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-postgres~=1.3.0
jobs:
  - name: test_task_fail_install
    tasks:
    - tap-postgres target-postgres dbt:run
```

### Link to Slack/Linen

https://meltano.slack.com/archives/C069CQNHDNF/p1724171940518529
