### ISSUE TITLE
bug: Schedule env vars not passed to Meltano invocation with Airflow DAG

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8730]
### Meltano Version

3.5.1

### Python Version

3.12

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

NA

### Description

The command in question is

```shell
meltano schedule run <schedule>
```

https://github.com/meltano/airflow-ext/blob/f0a9d3a0608773721a2a937c8642f4d380f42d26/files_airflow_ext/orchestrate/meltano.py#L98-L102

### Link to Slack/Linen

https://meltano.slack.com/archives/C069CQNHDNF/p1724586137192449

**Comment by edgarrmondragon** [comment]
I can't reproduce this. Use `env` in a schedule definition and setting a plugin-level config there works as expected.

<details><summary>meltano.yml</summary>
<p>

```yaml
version: 1
default_environment: dev
project_id: 065f56c4-8058-4518-a620-7d628526532c
environments:
- name: dev
- name: staging
- name: prod
send_anonymous_usage_stats: false
plugins:
  extractors:
  - name: tap-pypistats
    namespace: tap_pypistats
    variant: edgarrmondragon
    pip_url: tap-pypistats==0.0.3
    settings_group_validation:
    - - packages
    settings:
    - kind: array
      label: Packages
      name: packages
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
venv:
  backend: uv
jobs:
- name: pypistats-to-jsonl
  tasks:
  - tap-pypistats target-jsonl
schedules:
- name: weekly-pypistats
  interval: '@weekly'
  job: pypistats-to-jsonl
  env:
    TAP_PYPISTATS_PACKAGES: '["uv"]'
```

</p>
</details>
