### ISSUE TITLE
docs: Document a logging example to log at DEBUG level but excluding extractor/loader stdout

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8760]
Essentially this

```yaml
version: 1
disable_existing_loggers: no
loggers:
  # Disable logging of tap and target stdout
  meltano.core.block.extract_load:
    level: INFO
root:
  level: DEBUG
  handlers: [console]
```

But it would be nice to add it as a quick guide to the docs.
