### ISSUE TITLE
feature: Improve Documentation for Environments not supporting Project Level settings

### ISSUE THREAD

**Issue by haleemur** [meltano/meltano#8806]
### Feature scope

Other

### Description

It is currently not possible to configure project level settings per environment. This isn't easy to find in the documentation.

e.g.

the following will not store state to a local file in the dev environment and store state on azure blob storage in the test & prod environments. As a work around, we can control alternative behaviour by specifying appropriate sets of environment variables for each environment.

```yaml
version: 1
project_id: blah
default_environment: dev
environments:
  - name: dev
    config:
      state_backend:
        uri: 'file:///${MELTANO_SYS_DIR_ROOT}/state'
  - name: test
    config:
      state_backend:
        uri: 'azure://${AZURE_STORAGE_CONTAINER}/state'
        azure:
          connection_string: $MELTANO_STATE_BACKEND_AZURE_CONNECTION_STRING
  - name: prod
    config:
      state_backend:
        uri: 'azure://${AZURE_STORAGE_CONTAINER}/state'
        azure:
          connection_string: $MELTANO_STATE_BACKEND_AZURE_CONNECTION_STRING
```
