### ISSUE TITLE
feature: Meltano should generate a User-Agent header that plugins can easily reference in config

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#9044]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Similar to how `MELTANO_PROJECT_ROOT` is used here[^1]:

```yaml
- description: The path on your local filesystem where you would like the DuckDB database
    file and it's associated write-ahead log to be written.
  kind: string
  label: Path
  name: path
  value: ${MELTANO_PROJECT_ROOT}/output/warehouse.duckdb
```

some plugins would benefit from Meltano passing a default User-Agent setting. For example[^2]:

```yaml
- description: User agent string
  kind: string
  label: User Agent
  name: user_agent
  value: $MELTANO_USER_AGENT  # e.g. Meltano/3.7.0
```

All search results: https://github.com/search?q=repo%3Ameltano%2Fhub+user_agent+language%3AYAML&type=code&l=YAML.

[^1]: https://github.com/meltano/hub/blob/4f2047ee3b5e7d2a1df8e3f61980d4bc32b5f96a/_data/meltano/utilities/dbt-duckdb/jwills.yml#L76-L81
[^2]: https://github.com/meltano/hub/blob/4f2047ee3b5e7d2a1df8e3f61980d4bc32b5f96a/_data/meltano/extractors/tap-hellobaton/dluftspring.yml#L48-L51
