### ISSUE TITLE
bug: Airflow 2.7.0 and higher not working with Meltano because of the `airflow.cfg` issues

### ISSUE THREAD

**Issue by dan4ikV** [meltano/meltano#9177]
### Meltano Version

3.6.0

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Description

Meltano uses `airflow --help` to generate the `airflow.cfg` file when invoking airflow commands. However, as mentioned in https://github.com/apache/airflow/discussions/33951 discussion, this behavior was considered a bug in airflow and since version 2.7.0 the `airflow --help` command does not generate a config file anymore, and instead `airflow config` was introduced for that.
Meltano seems to attempt to generate the `airflow.cfg` using the `airflow --help` command on every airflow command invocation and, moreover, deletes the file afterwards. So even if we manually generate the `airflow.cfg`, it get's deleted on the first command invocation and all the subsequent commands fail with:
```
[Errno 2] No such file or directory: '/project/.meltano/run/airflow/airflow.cfg'
```

### Code

```yaml
version: 1

plugins:
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres

  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
    
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow-providers-postgres psycopg2==2.9.10 apache-airflow==2.10.5 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.10.txt
```
