### ISSUE TITLE
bug: Meltano should guide the user to adding `namespace` for custom plugins

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#9199]
### Meltano Version

3.7.1

### Python Version

NA

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

NA

### Description

When a user adds a custom plugin manually `(i.e. not with `meltano add --custom`),

```yaml
# meltano.yml
plugins:
  utilities:
  - name: my-util
    pip_url: ./utilities/my_util
    executable: my_util
```

users encounter confusing errors

```yaml
$ meltano invoke my-util
Utility 'my-util' is not known to Meltano. Try running `meltano lock --update --all` to ensure your plugins are up to date.
```

```yaml
$ meltano lock --update --all
Utility 'my-util' is not known to Meltano. Check https://hub.meltano.com/ for available plugins.
```

### Code

```yaml
# meltano.yml
plugins:
  utilities:
  - name: my-util
    pip_url: ./utilities/my_util
    executable: my_util
```

### Link to Slack/Linen

https://meltano.slack.com/archives/C06A1M1507J/p1744058543902489

### Related

* https://github.com/meltano/meltano/issues/3296
* https://github.com/meltano/meltano/issues/8337
* https://github.com/meltano/meltano/issues/3116
* https://github.com/meltano/meltano/issues/7305
