### ISSUE TITLE
bug: Selection criteria not respected by `--full-refresh`

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#9238]
### Meltano Version

3.6.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Description

Currently, if the `--full-refresh` flag is provided for `meltano run`/`meltano el`, all state is cleared regardless of the selection criteria. If I want to full refresh a specific stream, I expect the following to work without clearing state for other streams:

```
reuben@reuben-Inspiron-14-5425:~/Documents/taps/tap-iterable-msdk$ meltano state get test:tap-iterable-to-target-snowflake | jq
2025-04-28T23:19:16.645771Z [info     ] The default environment 'test' will be ignored for `meltano state`. To configure a specific environment, please use the option `--environment=<environment name>`.
2025-04-28T23:19:16.700900Z [warning  ] Running state operation for environment 'test' outside of an environment
2025-04-28T23:19:16.701837Z [info     ] Environment 'test' is active  
{
  "singer_state": {
    "bookmarks": {
      "email_open": {
        "replication_key": "createdAt",
        "replication_key_value": "2025-04-28 23:15:59 +00:00"
      },
      "email_send": {
        "replication_key": "createdAt",
        "replication_key_value": "2025-04-28 23:14:29 +00:00"
      }
    }
  }
}
reuben@reuben-Inspiron-14-5425:~/Documents/taps/tap-iterable-msdk$ TAP_ITERABLE__SELECT='["email_subscribe.*"]' meltano run --full-refresh tap-iterable target-snowflake

...

reuben@reuben-Inspiron-14-5425:~/Documents/taps/tap-iterable-msdk$ meltano state get test:tap-iterable-to-target-snowflake | jq
2025-04-28T23:21:55.083213Z [info     ] The default environment 'test' will be ignored for `meltano state`. To configure a specific environment, please use the option `--environment=<environment name>`.
2025-04-28T23:21:55.133690Z [warning  ] Running state operation for environment 'test' outside of an environment
2025-04-28T23:21:55.134564Z [info     ] Environment 'test' is active  
{
  "singer_state": {
    "bookmarks": {
      "email_subscribe": {
        "replication_key": "createdAt",
        "replication_key_value": "2025-04-28 23:18:04 +00:00"
      }
    }
  }
}
```

### Code

```yaml
version: 1
send_anonymous_usage_stats: true
project_id: tap-iterable
default_environment: test
environments:
- name: test
plugins:
  extractors:
  - name: tap-iterable
    namespace: tap_iterable
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    - about
    - stream-maps
    settings_group_validation:
    - [api_key]

    settings:
    - name: api_key
      label: API key
      description: Iterable API key
      sensitive: true
    - name: region
      kind: options
      label: Region
      description: Iterable region
      options:
      - label: US
        value: US
      - label: EU
        value: EU
    - name: start_date
      kind: date_iso8601
      label: Start date
      description: Timestamp in ISO 8601 format to get data from (inclusive)
    - name: end_date
      kind: date_iso8601
      label: End date
      description: Timestamp in ISO 8601 format to get data up to (inclusive)

  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-snowflake
    variant: meltanolabs
    pip_url: meltanolabs-target-snowflake
```
