### ISSUE TITLE
bug: Env var interpolations are not expanded in inherited plugins

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#9299]
### Meltano Version

3.7.7

### Python Version

3.13

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Linux

### Description

<blockquote>
Not sure if this is a bug or not, but running into an issue when using inherit_from with the target-postgres plugin. If I run target-postgres directly with the env variable, it works:

However, if I try and run the extension, it complains about an invalid string literal for `PORT`, so I have to hard code the port. It's only the port that is not being pulled in correctly, which is also odd.

Not the end of the world, but I did find it strange.

</blockquote>

### Code

```yaml
plugins:
  loaders:
  - name: target-postgres
    config:
      host: ${DB_HOST}
      port: ${DB_PORT}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      database: ${DB_DATABASE}
      default_target_schema: ${DB_SCHEMA}

  - name: target-postgres--extension
    inherit_from: target-postgres
    config:
      activate_version: false
      add_record_metadata: false
```

### Link to Slack/Linen

https://meltano.slack.com/archives/C068YBQQF1V/p1748992573211319
